.gitignore, Cargo.lock, signer-core/Cargo.toml, signer-core/src/secrets.rs
Solution: Started using `RedeemAddress` from `chain-core`
=> Problem: Signer shows wrong addresses (https://github.com/crypto-com/chain/issues/20)

.travis.yml
=> Problem: tarpaulin code coverage taking too long

chain-abci/benches/hashes.rs, chain-abci/benches/tx.rs, chain-core/src/common/merkle.rs
Solution: migrated the benchmarking code to use the new chain-core
=> Problem: microbenchmarks don't compile (CRO-83)

.travis.yml, client-index/src/tendermint/types/status.rs
Solution: chained the CI script such that fmt ruleset should be enforced
=> Problem: CI fmt checks silently ignored

Cargo.lock, client-common/Cargo.toml, client-common/src/balance/transaction_change.rs, client-index/Cargo.toml, client-index/src/index/rpc_sled_index.rs, client-index/src/service/address_service.rs, client-index/src/tendermint/rpc_client.rs, client-index/src/tendermint/types/block.rs, client-index/src/tendermint/types/genesis.rs, client-index/src/test/mock_client.rs
Solution: Added block height and time in transaction storage
=> Problem: (CRO-54) Client does not store block height and time

Cargo.lock, chain-abci/Cargo.toml, chain-core/Cargo.toml, chain-core/src/common/mod.rs, chain-core/src/init/address.rs, chain-core/src/tx/data/access.rs, chain-core/src/tx/data/address.rs, chain-core/src/tx/data/attribute.rs, chain-core/src/tx/data/input.rs, chain-core/src/tx/data/mod.rs, chain-core/src/tx/data/output.rs, chain-core/src/tx/mod.rs, chain-core/src/tx/witness/mod.rs, chain-core/src/tx/witness/tree.rs, client-core/Cargo.toml, signer-core/Cargo.toml
Solution: Implemented serde traits for chain-core types
=> Problem: (CRO-58) No way to serialize chain-core types in json

Cargo.lock, client-common/src/error.rs, client-core/Cargo.toml, client-core/src/key/private_key.rs, client-core/src/wallet.rs, client-core/src/wallet/default_wallet_client.rs, client-index/src/index.rs, client-index/src/index/default_index.rs, client-index/src/service.rs
Solution: Added functions to create new transactions
=> Problem: (CRO-56) No way to create new transaction from wallet client

client-core/src/service/wallet_service.rs, client-core/src/wallet.rs, client-core/src/wallet/default_wallet_client.rs
Solution: Added wallets() function to wallet client
=> Problem: No way to get list of all wallets from client

CONTRIBUTING.md, README.md
Solution: migrated to gitter and updated the links in documentation
=> Problem: chat not integrated with github permissions

README.md, client-rpc/README.md
Solution: Added documentation for client JSON-RPC server
=> Problem: (CRO-108) Missing client JSON-RPC server documentation

Cargo.lock, chain-abci/Cargo.toml, chain-core/Cargo.toml, client-core/Cargo.toml, signer-core/Cargo.toml
Solution: the fork was updated with upstream changes in rust-secp256k1 and secp256k1-zkp
and the revision was changed accordingly in dependencies
=> Problem: outdated secp256k1 fork

client-rpc/src/main.rs, client-rpc/src/server.rs
**Solution**: Moved `storage_dir` and `tendermint_url` to command line options with default values
=> Problem: (CRO-105) hardcoded configuration in client JSON-RPC

Cargo.lock, Cargo.toml, chain-core/src/common/mod.rs, chain-core/src/tx/data/address.rs, client-cli/Cargo.toml, client-cli/src/command.rs, client-cli/src/command/address_command.rs, client-cli/src/command/transaction_command.rs, client-cli/src/command/wallet_command.rs, client-cli/src/main.rs, client-common/src/error.rs
Solution: Added a CLI layer on client backend
=> Problem: (CRO-59) No CLI for interacting with client backend

chain-core/src/tx/fee/mod.rs, client-cli/src/main.rs, client-common/src/tendermint/types/genesis.rs, client-core/src/lib.rs, client-core/src/transaction_builder.rs, client-core/src/transaction_builder/default_transaction_builder.rs, client-core/src/wallet.rs, client-core/src/wallet/default_wallet_client.rs, client-rpc/src/server.rs, client-rpc/src/wallet_rpc.rs
Solution: Modified UTXO selection algorithm to take fee into account
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crypto-com/chain/80)
=> Problem: (CRO-112) Client does not add fee during UTXO selection

README.md, dev-utils/src/commands/genesis_command.rs
Solution: updated the genesis command to use the `compute_app_hash` instead
=> Problem: dev-utils generates an incorrect app_hash for genesis.json

chain-abci/src/app/commit.rs, chain-abci/src/app/mod.rs
Solution: added an explicit clear in commit handler + extended the test assertions
=> Problem: delivered_txs not cleared after commit persistence

client-cli/src/command.rs, client-cli/src/main.rs, client-core/README.md, client-core/src/lib.rs
Solution: Added a CLI command to do this
- Also added some documentation
=> Problem: (CRO-117) No way to resynchronise client's DB with chain from CLI

client-cli/src/command.rs, client-cli/src/main.rs, client-common/src/error.rs, client-common/src/storage.rs, client-common/src/storage/memory_storage.rs, client-common/src/storage/unauthorized_storage.rs, client-core/src/service/key_service.rs, client-core/src/service/wallet_service.rs, client-core/src/transaction_builder.rs, client-core/src/transaction_builder/default_transaction_builder.rs, client-core/src/transaction_builder/unauthorized_transaction_builder.rs, client-core/src/wallet/default_wallet_client.rs, client-index/src/index.rs, client-index/src/index/unauthorized_index.rs, client-rpc/src/server.rs, client-rpc/src/wallet_rpc.rs
Solution: Created a builder for DefaultWalletClient which creates WalletClient based on permissions given during building
=> Problem: (CRO-115) Client requires tendermint RPC connection even for non-tendermint ops

chain-core/src/common/merkle_tree.rs, chain-core/src/common/mod.rs
**Solution**: Implemented merkle tree with inclusion proofs
**Note**: I haven't integrated it with current usages of merkle tree. I wanted to get it reviewed before doing that.
=> Problem: (CRO-121) No easy to use implementation of merkle tree

.gitignore, Cargo.lock, client-cli/src/command/address_command.rs, client-core/Cargo.toml, client-core/src/service.rs, client-core/src/service/root_hash_service.rs, client-core/src/service/wallet_service.rs, client-core/src/transaction_builder/default_transaction_builder.rs, client-core/src/wallet.rs, client-core/src/wallet/default_wallet_client.rs, client-rpc/src/wallet_rpc.rs
**Solution**: 
- Merged related functions of `WalletClient` and `MultiSigWalletClient` into `WalletClient`.
- This PR does not add any new functionality. It only modifies the structure of code to ease future development.
=> Problem: (CRO-128) Code structure won't support integrating MuSig with transaction builder

chain-core/src/init/coin.rs
Solution: added a quickcheck property that verifies that sum and comparison work as expected
=> Problem: missing test for coin sums+comparisons (CRO-168)

client-common/src/storage.rs, client-common/src/storage/memory_storage.rs, client-common/src/tendermint/rpc_client.rs, client-core/src/key/private_key.rs, client-core/src/key/public_key.rs, client-core/src/service/key_service.rs, client-core/src/service/multi_sig_session_service.rs, client-core/src/service/root_hash_service.rs, client-core/src/service/wallet_service.rs, client-core/src/signer/default_signer.rs, client-core/src/wallet/default_wallet_client.rs, client-index/src/index/default_index.rs, client-index/src/service/address_service.rs, client-index/src/service/balance_service.rs, client-index/src/service/global_state_service.rs, client-index/src/service/transaction_service.rs, client-index/src/service/unspent_transaction_service.rs
**Solution**: 
- Modified code in `client-*` crates with Rust idiomatic constructs to reduce branching and complexity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crypto-com/chain/136)
=> Problem: (CRO-172) Increasing code complexity in client-* crates

client-common/src/error.rs, client-core/src/key/public_key.rs, client-core/src/signer.rs, client-core/src/signer/default_signer.rs, client-core/src/signer/unauthorized_signer.rs, client-core/src/transaction_builder/default_transaction_builder.rs, client-core/src/unspent_transactions.rs
Solution: Ran `cargo fix` to fix Rust edition
=> Problem: Code does not follow Rust 2018 specs

chain-abci/benches/hashes.rs, chain-abci/benches/tx.rs
Solution: adapted the microbenchmarks to the latest changes
=> Problem: abci microbenchmarks don't compile with the latest repo

chain-abci/benches/tx.rs, chain-abci/src/app/app_init.rs, chain-abci/src/app/mod.rs, chain-abci/src/app/query.rs, chain-abci/src/app/validate_tx.rs, chain-abci/src/storage/account/mod.rs, chain-abci/src/storage/tx.rs, chain-abci/tests/abci_app.rs, chain-core/src/init/config.rs, chain-core/src/state/account.rs, chain-core/src/state/mod.rs, chain-core/src/tx/mod.rs, client-network/src/network_ops/default_network_ops_client.rs, dev-utils/src/commands/genesis_command.rs
Solution: renamed chain-core's Account to StakedState
=> Problem: chain-core's `Account` is confusing, as there are no Account-to-Account operations

Cargo.lock, client-common/src/lib.rs, client-common/src/transaction.rs, client-core/src/wallet/default_wallet_client.rs, client-index/Cargo.toml, client-index/src/index.rs, client-index/src/index/default_index.rs, client-index/src/index/unauthorized_index.rs, client-index/src/service.rs, client-index/src/service/transaction_change_service.rs, client-index/src/service/transaction_service.rs, client-rpc/src/wallet_rpc.rs
Solution: Added support for all the types of transactions (payment and network ops) in client-index
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crypto-com/chain/151)
=> Problem: (CRO-132) New account/staking details are not handled properly in client-index

Cargo.lock, chain-abci/Cargo.toml, chain-core/Cargo.toml, chain-tx-validation/Cargo.toml, client-core/Cargo.toml, client-index/Cargo.toml
Solution: synced up the dependency with the latest fork's revision
=> Problem: sgx-patched fork of secp256k1

Cargo.lock, Cargo.toml, enclave-protocol/Cargo.toml, enclave-protocol/src/lib.rs
Solution: (WIP) added a basic crate with a few data types for requests and responses
=> Problem: no protocol for exchanges with the enclave wrapper (CRO-182)

.travis.yml, Cargo.lock, chain-abci/Cargo.toml, chain-abci/cli.yml, chain-abci/src/app/app_init.rs, chain-abci/src/app/commit.rs, chain-abci/src/app/mod.rs, chain-abci/src/app/query.rs, chain-abci/src/app/validate_tx.rs, chain-abci/src/enclave_bridge/mock.rs, chain-abci/src/enclave_bridge/mod.rs, chain-abci/src/lib.rs, chain-abci/src/main.rs, chain-abci/src/storage/account/mod.rs, chain-abci/src/storage/account/tree.rs, chain-abci/src/storage/tx.rs, chain-abci/tests/abci_app.rs, chain-tx-validation/src/lib.rs
Solution:
- added a basic client proxy (trait + ZMQ implementation)
sanity check on connection + basic transfer tx processing
- added a mock bridge (unfortunately, workspace compilation can't be feature-guarded, so it's not isolated) for tests + enhanced tests to check directly the tx validation crate's call (as the current error feedback is limited / TODO)
=> Problem: no ZMQ client connection in chain abci app (CRO-201)

Cargo.lock, client-cli/src/command.rs, client-cli/src/command/transaction_command.rs, client-network/Cargo.toml, client-network/src/network_ops.rs, client-network/src/network_ops/default_network_ops_client.rs
Solution: Implemented automatic withdrawal amount calculation based on fee algorithm
=> Problem: (CRO-212) Can create withdraw transactions with unnecessary high fees

Cargo.lock, client-rpc/Cargo.toml, client-rpc/src/server.rs, client-rpc/src/wallet_rpc.rs
Solution: Changed jsonrpc-derive version to 12.1 and made necessary changes to successfully compile
=> Problem: (CRO-193) Latest jsonrpc-derive fails to compile

client-rpc/src/wallet_rpc.rs
**Solution**: Exposed all the multi-sig functions in client-rpc
**Note**: Signatures of some of the exposed functions can change and new functions can be added when we start implementing UI on top of it.
=> Problem: (CRO-142) Multi-sig functions are not exposed in client-rpc

Cargo.lock, Cargo.toml, chain-abci/Cargo.toml, chain-abci/src/app/mod.rs, chain-abci/tests/abci_app.rs, chain-tx-filter/Cargo.toml, chain-tx-filter/src/lib.rs
Solution: created a dedicated crate that wraps assumed block-level filtering functionality and converted abci to use it
@devashishdxt this should help with CRO-215
=> Problem: TX filter functionality is spread out / hidden inside ABCI (CRO-216)

Cargo.lock, chain-abci/src/app/query.rs, chain-core/src/tx/mod.rs, chain-tx-validation/Cargo.toml, chain-tx-validation/src/lib.rs, enclave-protocol/src/lib.rs
Solution: moved TxWithOutputs to chain core and return directly in query responses
=> Problem: mock query dec doesn't return withdrawtx

Cargo.lock, chain-abci/src/app/app_init.rs, chain-abci/src/app/mod.rs, chain-tx-filter/Cargo.toml, chain-tx-filter/src/lib.rs
Solution: extended the block filter to accept staked state addresses
=> Problem: not easy to filter out staking ops history (CRO-215)

client-core/src/wallet.rs, client-core/src/wallet/default_wallet_client.rs, client-index/src/handler.rs, client-index/src/handler/default_transaction_handler.rs, client-index/src/index.rs, client-index/src/index/default_index.rs, client-index/src/index/unauthorized_index.rs, client-index/src/lib.rs, client-index/src/service.rs, client-network/src/network_ops/default_network_ops_client.rs, client-rpc/src/client_rpc.rs
Solution: This is first of a series of PRs which will slowly extract out all the transaction synchronization code from transaction index
=> Problem: (CRO-215) Transaction synchronization code is tightly coupled with transaction index

chain-core/src/init/address.rs, chain-core/src/init/mod.rs
Solution: removed the network constant from init module
=> Problem: fail to compile chain-core on sgx env

PHILOSOPHY.md
Solution: transcribed some of the internal intro slides
=> Problem: missing design philosophy doc

client-core/src/wallet.rs, client-core/src/wallet/default_wallet_client.rs, client-index/src/index.rs, client-index/src/index/default_index.rs, client-index/src/index/unauthorized_index.rs, client-index/src/lib.rs, client-index/src/synchronizer.rs, client-rpc/src/client_rpc.rs
Solution: Removed all the duplicate code related to synchronization from `DefaultIndex`. Added remaining synchronization code in `ManualSynchronizer`.
=> Problem: (CRO-215) Duplicate code in DefaultIndex implementation

client-common/src/block_header.rs, client-common/src/tendermint/types/block.rs, client-index/Cargo.toml, client-index/src/handler/default_block_handler.rs, client-index/src/synchronizer.rs
Solution: Modified `BlockHandler` and `ManualSynchronizer` to handle unencrypted transactions
=> Problem: (CRO-215) Client does not handle unencrypted transaction in a block (deposit and unbond)

Cargo.lock, client-cli/src/command.rs, client-core/src/transaction_builder/default_transaction_builder.rs, client-core/src/wallet/default_wallet_client.rs, client-rpc/Cargo.toml, client-rpc/src/client_rpc.rs, client-rpc/src/server.rs
Solution: Added `TransactionCipher` in `TransactionBuilder` and started using it for transaction encryption.
=> Problem: (CRO-215) TransactionBuilder is not integrated with TransactionCipher

chain-core/src/tx/fee/mod.rs
Solution: simplified the fee calculation in "calculate_for_txaux"
=> Problem: inconsistent fee calculation between client and abci (CRO-255)

README.md
<p align="center">
</p>
<h1 align="center"><a href="https://crypto.com">Crypto.com<a> Chain</h1>
<p align="center">
<a href="https://travis-ci.org/crypto-com/chain"><img label="Build Status" src="https://travis-ci.org/crypto-com/chain.svg?branch=master" /></a>
<a href="https://codecov.io/gh/crypto-com/chain"><img label="Code Coverage" src="https://codecov.io/gh/crypto-com/chain/branch/master/graph/badge.svg" /></a>
<a href="https://gitter.im/crypto-com/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge"><img label="Gitter" src="https://badges.gitter.im/crypto-com/community.svg" /></a>
</p>
1. [Description](#description)
2. [Contributing](#contributing)
3. [License](#license)
4. [Building](#building)<br />
4.1. [Build Prerequisites](#build-prerequisites)<br />
4.2. [Build …
=> Problem: CRO-66 Outdated README documentation

client-core/src/service/wallet_service.rs, client-core/src/wallet.rs, client-core/src/wallet/default_wallet_client.rs
Solution: Added "view keys" in client. Currently, each wallet can have only one view key.
=> Problem: (CRO-215) Client does not have a concept of view keys

Cargo.lock, client-cli/src/command.rs, client-core/src/transaction_builder/default_transaction_builder.rs, client-index/src/cipher/abci_transaction_cipher.rs, client-network/Cargo.toml, client-network/src/network_ops/default_network_ops_client.rs, client-rpc/src/client_rpc.rs, client-rpc/src/server.rs
Solution: Integrated `NetworkOpsClient` with `TransactionCipher`
=> Problem: (CRO-215) NetworkOpsClient is not integrated with TransactionCipher

client-cli/src/command.rs, client-cli/src/command/transaction_command.rs, client-common/src/key/public_key.rs, client-common/src/tendermint/types/block_results.rs
**Solution**: Integrated client-cli with latest changes in client-core and client-index
**Note**: After merging this PR, CLI end-to-end flow will start working.
=> Problem: (CRO-215) Client CLI does not work with private transactions

client-network/src/network_ops.rs, client-rpc/src/client_rpc.rs, client-rpc/src/server.rs
Solution: Integrated client-rpc with latest changes in client-core and client-index
=> Problem: (CRO-215) Client RPC does not work with private transactions

Cargo.lock, client-rpc/Cargo.toml
Solution: Updated jsonrpc-* version to 13.0
=> Problem: Client uses old jsonrpc-* version

README.md, chain-core/src/init/address.rs, chain-core/src/init/network.rs, chain-core/src/tx/data/address.rs, integration-tests/prepare.sh
Solution: Added devnet in Network enum and human readable part of bech32 address according to proposed convention
=> Problem: (CRO-254) No network for devnet/local testing + reflect a new name

README.md
=> Problem: missing links to technical docs

client-cli/src/command.rs, client-cli/src/command/address_command.rs, client-cli/src/command/transaction_command.rs, client-cli/src/command/wallet_command.rs, client-cli/src/main.rs, integration-tests/prepare.sh
Solution: Added passphrase confirmation during new wallet creation
=> Problem: (CRO-238) No passphrase confirmation in client cli during new wallet creation

client-core/src/wallet/default_wallet_client.rs, client-index/src/service/address_service.rs
Solution: Started using BTreeMap for unspent transactions and BTreeSet for transaction ids
=> Problem: (CRO-265) Using Vec instead of BTreeSet in AddressDetails

enclave-protocol/src/lib.rs
=> Problem: (CRO- 282) Duplicate elements in the example

chain-core/src/state/account.rs, chain-core/src/tx/data/input.rs, chain-core/src/tx/data/mod.rs, chain-core/src/tx/mod.rs, chain-core/src/tx/witness/mod.rs, enclave-protocol/src/lib.rs
Solution: Added maximum size of binary encoded data for transaction and also put limits on number of inputs
=> Problem: (CRO-247) Transaction broadcast is prone to DoS attacks

.travis.yml, enclave-protocol/src/lib.rs, integration-tests/docker-compose.yml, integration-tests/prepare.sh
Solution: Updated prepare script based on latest build steps
Pre-requisite: https://github.com/crypto-com/chain-tx-enclave/pull/16
=> Problem: (CRO-285) Integration test is not working

client-rpc/src/rpc/wallet_rpc.rs
Solution: Added wallet_getViewKey RPC
=> Problem: (CRO-306) Missing wallet_getViewKey RPC

client-common/src/error.rs, client-core/src/service/root_hash_service.rs, client-core/src/wallet/default_wallet_client.rs, client-rpc/src/rpc/multisig_rpc.rs
Solution: Added `multiSig_createAddress` RPC
=> Problem: (CRO-313) Missing create multisig address rpc

client-rpc/src/rpc/wallet_rpc.rs
Solution: Added txid return in the RPC
=> Problem: (CRO-315) Missing txid return in wallet_sendToAddress RPC

client-rpc/src/rpc/multisig_rpc.rs, client-rpc/src/rpc/staking_rpc.rs, client-rpc/src/rpc/wallet_rpc.rs
Solution: Use consistent `ToString` and `FromStr` for de/serialization
=> Problem: (CRO-321) Incorrect de/serialization for address in client-rpc

chain-abci/src/app/app_init.rs, chain-abci/src/app/commit.rs, chain-abci/src/enclave_bridge/mock.rs, enclave-protocol/src/lib.rs
Solution: extended the protocol to send a message on block commits (to flush the data) and added a sanity cross-check on the initial connection
=> Problem: no integrity check between abci<->tx-validation-enclave (CRO-314)

client-common/src/balance/balance_change.rs, client-common/src/balance/transaction_change.rs, client-rpc/src/rpc/wallet_rpc.rs, integration-tests/client-rpc/test/wallet-transaction.test.ts
Solution: Removed intermediate structure and modified serde impl of transaction change
=> Problem: (CRO-321) Unnecessary intermediate structure for de/serialization of transaction change

Cargo.lock, client-common/Cargo.toml, client-common/src/storage/sled_storage.rs
Solution: Fixed breaking changes of Sled 0.25
=> Problem: (CRO-327) Sled 0.25 fails to compile

chain-core/src/state/account.rs, client-rpc/src/rpc/staking_rpc.rs
Solution: Added staking state RPC
=> Problem: (CRO-339) Missing staking state RPC

client-rpc/src/rpc/transaction_rpc.rs, enclave-protocol/src/lib.rs
Solution: explicitly imported Box
=> Problem: enclave-protocol fails to compile on enclave

README.md
- Redirected *"Send Your First Transaction"* section ;
- Merged  *"Start a Basic Lite Node"* section into [Local Full Node Development](https://crypto-com.github.io/getting-started/local_full_node_development.html#local-full-node-development) instruction.
=> Redirecting "Send Your First Transaction"

client-cli/src/command/transaction_command.rs, client-common/src/error.rs, client-common/src/tendermint/client.rs, client-common/src/tendermint/rpc_client.rs, client-common/src/tendermint/types.rs, client-common/src/tendermint/types/broadcast_tx_result.rs, client-core/src/wallet.rs, client-core/src/wallet/default_wallet_client.rs, client-index/src/cipher/abci_transaction_cipher.rs, client-index/src/handler/default_transaction_handler.rs, client-index/src/index.rs, client-index/src/index/default_index.rs, client-index/src/index/unauthorized_index.rs, client-index/src/synchronizer.rs, client-network/src/network_ops/default_network_ops_client.rs, client-rpc/src/rpc/multisig_rpc.rs, client-rpc/src/rpc/staking_rpc.rs, client-rpc/src/rpc/wallet_rpc.rs, integration-tests/client-rpc/test/core/rpc.ts, integration-tests/client-rpc/test/core/utils.ts
Solution: Added error handling and new error type
=> Problem: (CRO-353) Tendermint ClientPRC does not handle enclave error

Cargo.lock, client-common/src/tendermint/client.rs, client-common/src/tendermint/rpc_client.rs, client-index/Cargo.toml, client-index/src/cipher/abci_transaction_cipher.rs, client-index/src/handler/default_transaction_handler.rs, client-index/src/index/default_index.rs, client-index/src/synchronizer.rs, client-network/src/network_ops/default_network_ops_client.rs, client-rpc/src/rpc/multisig_rpc.rs, client-rpc/src/rpc/wallet_rpc.rs
Solution: Divided batch RPC calls in chunks of size 100 requests per call
=>  Problem: (CRO-355) No limit on number of requests in a batch RPC call to tendermint

client-core/src/service/multi_sig_session_service.rs, client-core/src/transaction_builder.rs, client-core/src/transaction_builder/default_transaction_builder.rs, client-core/src/transaction_builder/unauthorized_transaction_builder.rs, client-core/src/wallet.rs, client-core/src/wallet/default_wallet_client.rs, client-rpc/src/rpc/multisig_rpc.rs
Solution: Added broadcast RPC call with underlying implementation
=> Problem: (CRO-324) Missing broadcast step in multi-sig signing flow

chain-core/src/init/network.rs, chain-core/src/tx/data/access.rs, chain-core/src/tx/data/attribute.rs, chain-core/src/tx/data/output.rs
Solution: added fixed constants;
added comments
removed unneeded methods + feature-guarded for warnings
=> Problem: naming convention (network name, network id, ...) is not up to date (CRO-371 CRO-358)

client-rpc/src/rpc/wallet_rpc.rs
Solution: Added wallet_listPublicKeys RPC
=> Problem: (CRO-297) Missing list public keys RPC

client-cli/src/command/address_command.rs, client-cli/src/command/wallet_command.rs, client-common/src/tendermint/rpc_client.rs, client-common/src/tendermint/types/query.rs, client-index/src/cipher/abci_transaction_cipher.rs, client-network/src/network_ops/default_network_ops_client.rs
Solution: Added response messages. Also changed parsing of ABCI query response to handle errors in a better way.
=> Problem: (CRO-385) No message when no items found in `list` commands in client cli

client-cli/src/command/transaction_command.rs, client-cli/src/main.rs
**Solution**: Changed client to accept amount in CRO
**Note**: As a long term solution to this, we should change `FromStr` implementation of `Coin`.
=> Problem: (CRO-374) CLI uses base units for amounts

Cargo.lock, client-common/src/error.rs
Solution: Converted `Error` into `Send + Sync`
=> Problem: (CRO-398) New `Error` type in client is not `Send + Sync`

integration-tests/README.md
Solution: Add the instructions
=> Problem: (CRO-401) Missing test running instructions for integration tests local mode

CHANGELOG.md, Cargo.lock, chain-core/Cargo.toml, chain-tx-filter/Cargo.toml, chain-tx-validation/Cargo.toml, client-cli/Cargo.toml, client-common/Cargo.toml, client-core/Cargo.toml, client-index/Cargo.toml, client-network/Cargo.toml, client-rpc/Cargo.toml, dev-utils/Cargo.toml, enclave-protocol/Cargo.toml
Solution: WIP unified version numbers of the current repository crates and updated the changelog with more information about to expect
=> Problem: no "official" alpha binary release (CRO-150)

client-index/src/auto_sync.rs, client-index/src/auto_sync_core.rs, client-index/src/auto_sync_data.rs, client-rpc/src/rpc/sync_rpc.rs
Solution: Added a RPC call to stop sync for a wallet
=> Problem: (CRO-396) No way to remove a wallet from auto-sync

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Solution: added a PR template with an explicit checklist
=> Problem: non-obvious contribution guidelines to newcomers

client-cli/src/command/transaction_command.rs, client-cli/src/main.rs
Solution: Added an environment variable `CRYPTO_CHAIN_ID` to set `chain_id`
=> Problem: (CRO-418) Client CLI has no option to change network and network ID

chain-core/Cargo.toml, chain-core/src/init/address.rs, chain-core/src/state/account.rs, chain-core/src/tx/data/address.rs, chain-core/src/tx/data/mod.rs, chain-core/src/tx/data/output.rs, chain-core/src/tx/mod.rs
Solution: added more feature-guards for unused or unneeded functionality in chain-core
=> Problem: incomplete feature-guard for tx-enclave (fails to compile)

integration-tests/prepare.sh
Solution: Configure Tendermint to index all transaction tags
=> Problem: (CRO-423) Integration test does not index all transaction tag

client-cli/src/command.rs, client-common/src/storage.rs, client-common/src/storage/memory_storage.rs, client-common/src/storage/sled_storage.rs, client-common/src/storage/unauthorized_storage.rs, client-index/src/service/address_service.rs, client-index/src/synchronizer.rs, client-rpc/src/rpc/sync_rpc.rs
Solution: Added delete call while doing force sync
=> Problem: (CRO-415) Old data is not deleted when doind force sync

SECURITY.md
Solution: added the new contact details
=> Problem: outdated security policy contact information

client-core/src/synchronizer.rs, client-core/src/synchronizer/auto_sync.rs, client-core/src/synchronizer/auto_sync_core.rs, client-core/src/synchronizer/auto_sync_data.rs, client-core/src/synchronizer/auto_synchronizer.rs, client-rpc/src/rpc/sync_rpc.rs
Solution: add sync_info api
add unlocked wallets in autosync info
add state
=> Problem: (CRO-403) auto-sync connection state not signalled to the API caller

enclave-protocol/src/lib.rs
Solution: refined the IntraEnclaveResponse type
=> Problem: deposit stake validation response can't be returned from the enclave (CRO-386)

CONTRIBUTING.md
Solution: Changed `satify` to `satisfy`
=> Problem: Typo in Chain Contribution guideline

Cargo.lock, NOTICE, chain-tx-filter/Cargo.toml, chain-tx-filter/src/filter.rs, chain-tx-filter/src/lib.rs
Solution:
- adapted the ethbloom implementation from ETC using bit-vec
- added a quickcheck property to verify that the new implementation matches the ethbloom one
=> Problem: ethbloom brings a transitive std dependency (CRO-426)

chain-abci/src/app/mod.rs, chain-tx-filter/src/filter.rs, chain-tx-filter/src/lib.rs, enclave-protocol/src/lib.rs
Solution: added a reset + refined the check tx request validation
=> Problem: inconvenient API for static tx filter in enclaves

chain-tx-filter/src/lib.rs
Solution: added Into implementation
=> Problem: cannot convert the top level filter wrapper to byte array

chain-tx-filter/src/filter.rs, chain-tx-filter/src/lib.rs, enclave-protocol/src/lib.rs
Solution: exposed the raw data via a custom method instead
=> Problem: filter's Into implementations move ownership

client-core/src/synchronizer/auto_sync_core.rs, client-core/src/synchronizer/auto_sync_data.rs, client-core/src/synchronizer/auto_synchronizer.rs
Solution: add reset state to ready after disconnection
=> Problem:(CRO-447) there is no reset state after disconnection in autosync

chain-abci/src/app/mod.rs, chain-abci/src/enclave_bridge/mock.rs
Solution: changed the end block handling to send the enclave request
+ updated the mock
=> Problem: tx filter not retrieved from the enclave (CRO-364)

chain-abci/src/app/mod.rs, chain-abci/tests/abci_app.rs
Solution: added additional key-value pairs to the valid transaction event
=> Problem: transactions not tagged with fee + account

client-core/src/synchronizer/auto_sync_core.rs
Soluton: modify "polling get blocks" to check correctly, and added unit-test
=> Problem:(CRO-468) autosync don't work correctly when status reply is not delivered

chain-abci/src/storage/account/mod.rs, chain-abci/src/storage/tx.rs, chain-core/src/state/account.rs, client-network/src/network_ops/default_network_ops_client.rs
Solution: Added `jailed_until` in `StakedState`
=> Problem: (CRO-461) Staked state does not store jailing information

.travis.yml, chain-abci/src/storage/tx.rs, chain-abci/tests/abci_app.rs, chain-core/src/state/account.rs, chain-tx-validation/src/lib.rs, client-cli/src/command/transaction_command.rs, client-common/src/tendermint/types/block.rs, client-core/src/handler/default_block_handler.rs, client-core/src/synchronizer/manual_synchronizer.rs, client-network/src/network_ops.rs, client-network/src/network_ops/default_network_ops_client.rs, client-rpc/src/rpc/staking_rpc.rs
Solution: Added StakedAddress to UnbondTx
=> Problem: (CRO-474) UnbondTx has same TxId across different wallet

chain-abci/src/storage/tx.rs, chain-tx-validation/src/lib.rs, client-common/src/tendermint/types/block.rs
Solution: Added a check in transaction verification to check for jailed accounts
=> Problem: (CRO-461) Can create network transaction when account is jailed

chain-abci/src/app/mod.rs
Solution: Added a check for setting validator power of jailed accounts to zero.
Note: Code added in this PR is logically unreachable. I'm only adding these to double-check before modifying validator set.
=> Problem: (CRO-454) Jailed account may get added to validator set

Cargo.lock, chain-abci/Cargo.toml, chain-abci/src/app/app_init.rs, chain-abci/src/app/mod.rs, chain-abci/src/lib.rs, chain-abci/src/liveness.rs, chain-abci/src/main.rs, chain-abci/tests/abci_app.rs, chain-core/Cargo.toml, chain-core/src/state/tendermint.rs
Solution: Added `LivenessTracker` in chain node state
=> Problem: (CRO-469) No way to measure liveness of a validator

Cargo.lock, chain-abci/Cargo.toml, chain-abci/src/app/app_init.rs, chain-abci/src/app/mod.rs, chain-abci/tests/abci_app.rs, chain-core/src/init/config.rs, chain-core/src/state/tendermint.rs
Solution: Change liveness tracker in `end_block` based on power change in block.
=> Problem: (CRO-452) Liveness tracker is not changed if a validator is added/removed from validator set

chain-tx-enclave/tx-validation/Dockerfile
Solution: replace ubuntu repo server with something else
restore newline
=> Probem:(CRO-486) building docker fails in intergration test

.travis.yml, install_kcov.sh, install_zeromq.sh
Soluton: add precompiled packages to save time
=> Problem:(CRO-472) slow CI builds

Cargo.lock, client-core/Cargo.toml, client-rpc/Cargo.toml
Solution: Changed `jsonrpc-core`/`jsonrpc-http-server` version to `14.0`
=> Problem: (CRO-482) jsonrpc-core/http-server 14.0 fails to compile

.drone.yml, prepare.sh
Solution: add drone.io  config
add prepare.sh
=> Problem:(CRO-483) There is no dedicated ci builder

.drone.yml, Cargo.lock, bors.toml
Solution: added additional drone pipeline that executes the basic tx-validation test in HW mode
=> Problem: HW-mode SGX tests not executed in CI (CRO-204)

chain-abci/src/app/app_init.rs, chain-abci/src/app/jail_account.rs, chain-abci/tests/abci_app.rs, chain-core/src/init/config.rs, chain-core/src/tx/fee/mod.rs, chain-core/tests/verify_config.rs, dev-utils/example-dev-conf.json, dev-utils/src/commands/genesis_command.rs, dev-utils/src/commands/genesis_dev_config.rs, integration-tests/prepare.sh
Solution: Added network parameters for `slashing_config` in `genesis.json`
=> Problem: (CRO-455) No initial network parameters for slashing configuration

.drone.yml
Solution: extended the drone pipeline with the current tx-query mini-integration test
=> Problem: cross-enclave tests not executed on CI (CRO-204)

chain-core/src/tx/fee/mod.rs
Solution: Modified `FromStr` implementation to correctly calculate fractional part.
Note: Current implementation parses `"0.1"` to `0.001` and `"0.15"` to `0.015`. Fixed implementation parses `"0.1"` to `0.100` and `"0.15"` to `0.150`.
=> Problem: Incorrect FromStr implementation of Milli

chain-abci/src/app/mod.rs, chain-abci/tests/abci_app.rs
Solution: Add non-live validators to slashing queue
=> Problem: (CRO-456) Non-live validators are not slashed

chain-abci/src/app/commit.rs, chain-abci/src/app/mod.rs, chain-abci/src/app/query.rs, chain-abci/src/enclave_bridge/mock.rs, chain-abci/src/storage/tx.rs, chain-abci/tests/abci_app.rs, chain-core/src/tx/mod.rs, chain-tx-enclave/tx-query/app/src/test/mod.rs, chain-tx-enclave/tx-query/enclave/src/lib.rs, chain-tx-enclave/tx-validation/app/src/enclave_u/mod.rs, chain-tx-enclave/tx-validation/app/src/server/mod.rs, chain-tx-enclave/tx-validation/app/src/test/mod.rs, chain-tx-enclave/tx-validation/enclave/src/validate.rs, client-common/src/tendermint/types/block.rs, client-core/src/cipher/default.rs, client-core/src/cipher/mock_abci_transaction_obfuscation.rs, client-core/src/transaction_builder/default_transaction_builder.rs, client-network/src/network_ops/default_network_ops_client.rs, client-rpc/src/rpc/wallet_rpc.rs, enclave-protocol/src/lib.rs
Solution: created a restricted tx data type for enclave requests
and ported relevant parts of codebase to it
=> Problem: enclave protocol accepts all tx types

chain-core/src/state/tendermint.rs, chain-core/src/tx/fee/mod.rs
Solution: Implemented [Babylonian Method](https://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Babylonian_method) to calculate square root.
=> Problem: (CRO-503) No way to calculate square root of Milli

chain-abci/src/app/mod.rs, chain-abci/src/app/slash_accounts.rs, chain-abci/tests/abci_app.rs, chain-core/src/init/config.rs, chain-core/src/tx/fee/mod.rs
Solution: Implimented proportional slashing as outlined in https://github.com/cosmos/cosmos-sdk/blob/sunny/prop-slashing-adr/docs/architecture/adt-014-proportional-slashing.md
=> Problem: (CRO-503) Slashing rate is not proportional to number of failing validators

chain-abci/src/app/commit.rs
Solution:  abci send apphash for empty blocks
=> Problem:(CRO-517) chain-abci doesn't send app_hash if there are no transactions

chain-core/src/tx/fee/mod.rs
Solution: 
Adding testes with quickcheck 
@tomtau  I added one more check for **a+b = 0 iff a=b=0**  -Line 343
=>  Problem:(CRO-514) No robust tests for Milli arithmetic operations

.gitignore
=> Problem: .idea files may be accidentally committed

client-cli/src/command.rs, client-core/src/service/wallet_state_service.rs, client-core/src/wallet.rs, client-core/src/wallet/default_wallet_client.rs, client-network/src/network_ops.rs, client-network/src/network_ops/default_network_ops_client.rs
Solution: Added balance checks when creating network ops transactions
=> Problem: (CRO-294) Client can generate invalid transactions

.drone.yml
Solution: restricted the execution + updated signature
=> Problem: drone integration test pipeline not authorized

client-core/src/service/hd_key_service.rs, client-core/src/wallet/default_wallet_client.rs, client-rpc/src/rpc/wallet_rpc.rs
=> Problem:(CRO-536) backwards-incompatible hd-wallet derivation

.travis.yml, integration-tests/client-rpc/package.json, integration-tests/client-rpc/test/network-ops.test.ts, integration-tests/client-rpc/test/wallet-auto-sync.test.ts, integration-tests/client-rpc/test/wallet-transaction.test.ts
Solution: Disable caching in nightly and increase test allowed timeout
=> Problem: (CRO-538) Caching is too huge and timeout exceeded in Travis

.drone.yml
Solution: updated the signature
=> Problem: new drone pipeline not authorized

client-cli/src/command/transaction_command.rs, client-cli/src/main.rs
Solution: call unjail in cli
increase coverage
fix sync
fix save public, private key
=> Problem: (CRO-494) not possible to create unjail transaction in client-cli

client-core/src/signer/dummy_signer.rs, client-core/src/transaction_builder/default_transaction_builder.rs, client-network/Cargo.toml, client-network/src/network_ops/default_network_ops_client.rs
solution: Mock a signature to calculate fee.
=> Problem(CRO-549) client withdraw all doesn't use dummy values in fee estimation

chain-core/src/common/merkle_tree.rs
I've refactored the ``Path`` representation with ``Vec``, which makes it both more correct and more compact serialization (Old representation allows some illegal path state).
With the current implementation, the gain of further optimizing the serialization with ``BitVec`` is small, I guess it doesn't worth the trouble anymore.
=> Problem: Inefficient binary encoding of Merkle tree path (CRO-149)

.travis.yml, ci-scripts/install_kcov.sh, client-network/src/network_ops/default_network_ops_client.rs
Solution: Change cache location such that installation can be detected on restore
=> Problem: (CRO-599) kcov installation is not detected in properly in TravisCI

chain-abci/src/app/app_init.rs, chain-abci/src/app/jail_account.rs, chain-abci/src/app/mod.rs, chain-abci/src/app/slash_accounts.rs, chain-abci/src/liveness.rs, chain-abci/src/slashing.rs, chain-abci/src/storage/account/mod.rs, chain-abci/src/storage/tx.rs, chain-abci/tests/abci_app.rs, chain-core/src/init/config.rs, chain-core/src/state/account.rs, client-cli/src/command.rs, client-network/src/network_ops/default_network_ops_client.rs
Solution: Added punishment information in staked state
=> Problem: (CRO-527) Punishment information is not reflected in staked state

chain-tx-enclave/tx-validation/make.sh, integration-tests/env.sh, integration-tests/prepare.sh
Solution: add fixes for linux
fix env error
add sudo
=> Problem:(CRO-574)  integration test cannot run on linux

client-core/src/wallet/default_wallet_client.rs, integration-tests/client-rpc/test/hdrestore-auto-sync.test.ts, integration-tests/client-rpc/test/hdwallet-auto-sync.test.ts
Solution: add private, public keys to storage
=> Problem:(CRO-540) syncing does not work in HD wallet

Cargo.lock, client-common/src/storage.rs, client-core/src/service/hd_key_service.rs, client-core/src/wallet/default_wallet_client.rs
Solution: Added wallet name as associated data in client storage encryption/decryption
=> Problem: (CRO-576) Missing integrity check in client-storage

integration-tests/client-rpc/test/hdrestore-transaction.test.ts, integration-tests/client-rpc/test/hdwallet-management.test.ts, integration-tests/client-rpc/test/hdwallet-transaction.test.ts
Solution: add hdwallet integration test
=> Problem:(CRO-542) no integration test for hd-wallet

client-rpc/src/rpc/staking_rpc.rs
=> Problem:(CRO-545) not possible to unjailTx in client-rpc for test automation

client-common/src/multi_sig_address.rs
Solution: Add test attribute to run those tests
=> Problem: (CRO-582) Missing test attribute in a few MultiSigAddress tests

chain-core/src/init/network.rs, client-cli/src/command/wallet_command.rs, client-common/Cargo.toml, client-common/src/key/public_key.rs, client-core/src/hd_seed.rs, client-core/src/lib.rs, client-core/src/mnemonic.rs, client-core/src/service/hd_key_service.rs, client-core/src/service/root_hash_service.rs, client-core/src/wallet.rs, client-core/src/wallet/default_wallet_client.rs, client-rpc/src/rpc/wallet_rpc.rs
Solution: Extract `HdKey` into `HDSeed` and `Mnemonic`
=> Problem: (CRO-591) HD wallet module is not re-usable

chain-tx-enclave/tx-query/app/src/test/mod.rs
Solution: added logging of exact errors + more graceful process quitting (rather than panic)
=> Problem: tx-query test occassionally hangs for unknown reason on CI (CRO-598)

.drone.yml, ci-scripts/Dockerfile, ci-scripts/tx-query-hw-test.sh, ci-scripts/tx-validation-hw-test.sh
Solution: created a simple Docker image uploaded to the Docker hub and updated the drone pipelines to use it
=> Problem: drone pipelines not portable and reproducible (CRO-598)

.drone.yml
Solution: updated the pipeline signature
=> Problem: new drone CI server

.dockerignore, Cargo.lock, Cargo.toml, chain-abci/src/app/app_init.rs, chain-abci/src/app/mod.rs, chain-abci/src/main.rs, chain-abci/src/storage/account/mod.rs, chain-abci/src/storage/account/tree.rs, chain-abci/tests/abci_app.rs, chain-abci/tests/punishment.rs, chain-abci/tests/tx_validation.rs, chain-core/src/common/mod.rs, chain-tx-validation/src/lib.rs, client-cli/src/command.rs, client-common/Cargo.toml, client-common/src/tendermint/mock.rs, client-core/Cargo.toml, client-core/src/hd_seed.rs, client-core/src/service/hd_key_service.rs, client-core/src/synchronizer/manual_synchronizer.rs, client-core/src/synchronizer/polling_synchronizer.rs, client-mock/Cargo.toml, client-mock/src/lib.rs, client-rpc/src/rpc/sync_rpc.rs, client-rpc/src/rpc/wallet_rpc.rs, dev-utils/src/commands/genesis_command.rs, dev-utils/src/commands/genesis_dev_config.rs, dev-utils/src/commands/init_command.rs
Solution:
- A separate crate client-mock to generate legitimate tendermint data types, to test lite client verification.
- Other misc changes.
- Change DateTime to Time, Timespec from i64 to u64.
- Remove `Default` trait implementation of `HDSeed`.
- Some hash field on tendermint data type should be `Option`.
=> Problem (CRO-592) Problem: lite client code not tested.

Cargo.lock, chain-core/src/tx/data/address.rs, client-rpc/Cargo.toml, client-rpc/src/rpc/staking_rpc.rs
solution: Add a `staking_validatorNodeJoin` method in rpc.
=> Problem:(CRO-586) No way to add a node to validator set from client-rpc

chain-tx-enclave/tx-query/Makefile, chain-tx-enclave/tx-query/enclave/Cargo.toml, chain-tx-enclave/tx-query/enclave/src/lib.rs
Solution: added sgx-test feature which will disable timeouts on query connections
=> Problem: tx-query occasionally fails

Cargo.lock, chain-core/Cargo.toml, chain-tx-enclave/tx-validation/enclave/Cargo.toml, client-common/Cargo.toml
as https://github.com/crypto-com/chain/pull/629 is incomplete
=> Bump aead to 0.2 and aes-gcm-siv to 0.3

.drone.yml
Solution: marked docker containers with git sha and added a container stop teardown
=> Problem: no clean up for reproducible / portable pipelines

.drone.yml, ci-scripts/run-integration-tests.sh
Solution: removed rustup and environment dependant parts
=> Problem: Integration tests are not reproducible on Drone (CRO-610)

client-core/src/transaction_builder/raw_transfer_transaction_builder.rs
Solution: Remove unnecessary semicolon
=> Problem: (CRO-608) Unnecessary semicolon in RawTransferTransactionBuilder

.github/CODEOWNERS
Solution: added a code owners file
=> Problem: pull assigner doesn't assign PRs

.github/CODEOWNERS
Solution: syntax in CODEOWNERS file was wrong -> added the global prefix
=> Problem: PRs not auto-assigned

chain-abci/src/app/end_block.rs, chain-abci/src/app/rewards.rs, chain-abci/tests/abci_app.rs, chain-core/src/common/fixed.rs, chain-core/src/init/config.rs, chain-core/src/init/params.rs, chain-core/src/state/mod.rs, client-common/src/tendermint/mock.rs, dev-utils/example-dev-conf.json, dev-utils/src/commands/genesis_dev_config.rs, integration-tests/prepare.sh, test-common/src/chain_env.rs
Solution:
- Checked the arithemetic error, when happends print a warning
and don't mint new coins.
=> Problem: monetary expansion calculation could panic for misconfigration

dev-utils/example-dev-conf.json
Solution: Fixed error in `example-dev-conf.json`
=> Problem: (CRO-631) Panic while generating genesis.json from example-dev-conf.json

Cargo.lock, chain-core/src/init/address.rs, chain-core/src/tx/data/address.rs, client-common/Cargo.toml
Solution: Add network human readable prefix check
=> Problem: (CRO-634) from_cro in ExtendedAddress ignores network

architecture-docs/adr-001.md
Solution: wrote up a proposal in ADR
NOTE: it's marked as proposed, as it needs some discussion before it's accepted -- feel free to comment if anything is unclear or missing.
I don't expect this changes to be in 0.1, but more for later releases
=> Problem: non-consolidated storage architecture

client-common/src/tendermint/lite.rs, client-core/src/handler.rs, client-core/src/handler/default_block_handler.rs, client-core/src/handler/default_transaction_handler.rs, client-core/src/service.rs, client-core/src/service/global_state_service.rs, client-core/src/synchronizer/manual_synchronizer.rs
Solution:
- No need to encrypt global state
- Store `lite::TrustedState` in global state
- Cache global state in memory when syncing.
Make some less controversial changes first.
=> Problem (CRO-578 WIP): Wallet keep loading and decrypt global state

chain-tx-enclave/tx-query/enclave/src/lib.rs, client-core/src/cipher/default.rs
Solution: added more details to error messages to know where exactly it failed
+ explicit flushing after writing to streams
=> Problem: random broken pipe failures in sgx-cargo-1804-hw2

.drone.yml, integration-tests/jail/docker-compose.yml
Solution: made it to be executed only on bors commands
+ updated the sig
=> Problem: blocking drone exec pipeline

client-rpc/src/server.rs
Solution: Added retry logic in case of I/O failure
Sample log message:
```
[2019-12-12T09:00:20Z ERROR client_rpc::server] Initialization error: Unable to connect to websocket RPC at: ws://localhost:26657/websocket
=> WebSocketError: I/O failure
```
=> Problem: (CRO-643) client-rpc does not retry connections to tendermint

Cargo.lock, client-common/Cargo.toml, client-core/Cargo.toml, client-network/Cargo.toml, test-common/Cargo.toml
=> Problem:(CRO-641) signatory v0.17 fails to compile

integration-tests/README.md
Solution: add document
tidy up
=> Problem:(cro-623) no documentation for integration test

integration-tests/bot/chainbot.py
=> chainbot fails to run after recent dev-utils change

dev-utils/src/commands/init_command.rs
=> Problem:(cro-525) dev-utils init throws away error

Cargo.lock, chain-tx-enclave/tx-validation/app/Cargo.toml, client-common/Cargo.toml
Solution: updated to 0.30.1 which has a patch for not taking all CPU in idle time
=> Problem: old sled version

CHANGELOG.md, Cargo.lock, chain-abci/Cargo.toml, chain-core/Cargo.toml, chain-tx-enclave/tx-query/app/Cargo.toml, chain-tx-enclave/tx-query/enclave/Cargo.toml, chain-tx-enclave/tx-validation/app/Cargo.toml, chain-tx-enclave/tx-validation/enclave/Cargo.toml, chain-tx-filter/Cargo.toml, chain-tx-validation/Cargo.toml, client-cli/Cargo.toml, client-common/Cargo.toml, client-core/Cargo.toml, client-core/src/hd_seed.rs, client-core/src/service.rs, client-core/src/service/hd_key_service.rs, client-core/src/wallet/default_wallet_client.rs, client-network/Cargo.toml, client-rpc/Cargo.toml, client-rpc/src/rpc/wallet_rpc.rs, client-rpc/src/server.rs, dev-utils/Cargo.toml, enclave-protocol/Cargo.toml, test-common/Cargo.toml, test-common/src/block_generator.rs
Solution: use different account_index(2) for view key derivation.
=> Problem: transfer private key can be compromised by leaked private view key

chain-abci/src/app/rewards.rs
Solution:
- Fix the bug: `last_distribution_time` not updated after rewards distribution.
- Added unit testing to prevent this happen again.
=> Problem (CRO-668): app hash keep changing on every empty block

CHANGELOG.md
Solution: added an entry of main changes
=> Problem: changelog not updated for v0.2 release

Cargo.lock, client-common/Cargo.toml, client-common/src/error.rs, client-common/src/storage.rs
Solution: Started using `rust-argon2`
=> Problem: (CRO-577) Client uses weak hashing algorithm for passwords

chain-abci/src/storage/account/tree.rs
Solution: Change to use to_string
=> Problem: (CRO-679) cargo build failed on nightly of error description

.travis.yml, chain-abci/src/main.rs, chain-tx-enclave/tx-query/Dockerfile, chain-tx-enclave/tx-query/app/src/enclave_u/mod.rs, chain-tx-enclave/tx-query/entrypoint.sh, docker/Dockerfile, integration-tests/client-rpc/test/hdrestore-transaction.test.ts, integration-tests/client-rpc/test/hdwallet-transaction.test.ts, integration-tests/client-rpc/test/wallet-transaction.test.ts, integration-tests/const-env.sh, integration-tests/docker-compose.yml, integration-tests/env.sh, integration-tests/prepare.sh, integration-tests/wait-for-setup.sh
Solution: Run integration tests as mock on Travis CI
=> Problem: (CRO-629) Integration tests fails on Travis CI

Cargo.lock, chain-abci/Cargo.toml, dev-utils/Cargo.toml, test-common/Cargo.toml
Solution: Updated kvdb versions. Fixes https://github.com/crypto-com/chain/issues/799
=> Problem: Latest kvdb fails to compile

client-cli/src/command/wallet_command.rs, client-core/src/service/hd_key_service.rs, client-core/src/service/key_service.rs, client-core/src/service/root_hash_service.rs, client-core/src/service/sync_state_service.rs, client-core/src/service/wallet_service.rs, client-core/src/wallet.rs, client-core/src/wallet/default_wallet_client.rs, client-rpc/src/rpc/wallet_rpc.rs, integration-tests/bot/chainrpc.py, integration-tests/client-rpc/test/hdwallet-management.test.ts, integration-tests/client-rpc/test/wallet-management.test.ts
Solution:
- Add delete wallet api to both cli and rpc.
=> Problem(Fix #915): no delete wallet API

chain-core/src/state/account.rs, chain-tx-validation/src/lib.rs, client-cli/src/command.rs, client-cli/src/command/transaction_command.rs, client-common/src/transaction.rs, client-core/src/signer/dummy_signer.rs, client-core/src/wallet.rs, client-core/src/wallet/default_wallet_client.rs, client-network/src/network_ops.rs, client-network/src/network_ops/default_network_ops_client.rs, client-rpc/src/rpc/multisig_rpc.rs, client-rpc/src/rpc/staking_rpc.rs, client-rpc/src/rpc/wallet_rpc.rs, client-rpc/src/server.rs, integration-tests/bot/chainrpc.py, integration-tests/client-rpc/test/network-ops.test.ts
solution:
1. create a transfer tx to make a UTXO
2. broadcast the transfer tx and waiting util it confirmed
3. create deposit transaction using the transfer tx output
4. broadcast the deposit tx
=> Problem(fix #847): no high-level client deposit tx workflow

Cargo.toml, chain-core/cbindgen.toml, chain-core/src/init/network.rs, cro-clib/.gitignore, cro-clib/Cargo.toml, cro-clib/build.rs, cro-clib/cbindgen.toml, cro-clib/chain-core.h, cro-clib/chain.h, cro-clib/examples/Makefile, cro-clib/examples/test.c, cro-clib/src/lib.rs, cro-clib/src/types.rs, cro-clib/src/wallet.rs
Solution: add c-bindings
remove auto-generated files
working
tidy up
fix clippy issues
remove chain.h
=> Problem:(cro-819) no C bindings for client libraries

integration-tests/README.md
=> Problem (Fix #952): No manually setup docs for integration tests.

cro-clib/Cargo.toml, cro-clib/chain.h, cro-clib/examples/test.c, cro-clib/src/address.rs, cro-clib/src/basic_wallet.rs, cro-clib/src/lib.rs, cro-clib/src/wallet.rs
Solution: add c-binding for normal wallet
tidy up
=> Problem:(cro-945) no c-binding for normal wallet

client-cli/src/command/transaction_command.rs, client-core/src/types/transaction_change.rs, client-network/src/network_ops.rs, client-network/src/network_ops/default_network_ops_client.rs, client-rpc/src/rpc/staking_rpc.rs, integration-tests/bot/chainrpc.py, integration-tests/pytests/common.py, integration-tests/pytests/conftest.py, integration-tests/pytests/test_pending_tx.py, integration-tests/pytests/test_watch_only_wallet.py, integration-tests/run.sh
Solution:
- Handle `TransactionPending` for deposit transaction
- Add thorough integration tests for pending balance
=> Problem (Fix #929): total/available balance for ongoing deposit transaction is not correct

client-core/src/lib.rs, client-core/src/multi_sig.rs, client-core/src/multi_sig/builder.rs, client-core/src/multi_sig/session.rs, client-core/src/multi_sig/signer.rs, client-core/src/service/multi_sig_session_service.rs
Solution: Decouple MultiSig into separate module for re-use
=> Problem: (fix #967) MultiSig logic is coupled with MultiSig service

chain-abci/src/app/slash_accounts.rs
Solution:
- Change to the correct link.
=> Problem (Fix #1031): The doc link of proportional slashing is dead

integration-tests/bot/chainbot.py, integration-tests/multinode/common.py, integration-tests/multinode/jail_cluster.json, integration-tests/multinode/jail_test.py, integration-tests/multinode/join_cluster.json, integration-tests/multinode/join_test.py
Solution:
- integrate unbond test into join test.
- use tx_search to wait for transaction (Fix #948)
- change node stopping sequence, try to fix app_hash mismatch problem
=> Problem (Fix #851): no unbonding validator test

client-cli/src/command.rs, client-network/src/network_ops.rs, client-network/src/network_ops/default_network_ops_client.rs, client-rpc/src/rpc/staking_rpc.rs, integration-tests/bot/chainrpc.py, integration-tests/client-rpc/test/network-ops.test.ts, integration-tests/multinode/jail_test.py, integration-tests/multinode/join_test.py, integration-tests/pytests/test_pending_tx.py
Solution: Removed wallet details requirement. Fixes #974.
=> Problem: Public network state retrievals require wallet information.

client-core/src/transaction_builder.rs, client-core/src/transaction_builder/raw_transfer_transaction_builder.rs, cro-clib/Cargo.toml, cro-clib/chain.h, cro-clib/examples/Makefile, cro-clib/examples/test.c, cro-clib/examples/tx.c, cro-clib/src/fee.rs, cro-clib/src/lib.rs, cro-clib/src/transaction_build.rs, cro-clib/src/types.rs
Solution:add c-binding for tx
this pr is for tx building only
=> Problem:(cro-947) no C bindings for transaction building

CHANGELOG.md
Solution: updated main 0.3 changes
=> Problem: changelog is not up to date with most recent changes

chain-abci/src/enclave_bridge/mock.rs
Solution:
- Make it build again
=> Problem (Fix #1093): Mock mode in master branch not buildable

client-cli/src/command/transaction_command.rs
solution: confirm coin input in client-cli
=> Problem:(fix #1027) inputted coin value in client-cli is not confirmed

.gitignore, integration-tests/bot/chainrpc.py, integration-tests/multinode/common.py, integration-tests/multinode/proportional_cluster.json, integration-tests/multinode/proportional_test.py, integration-tests/run_multinode.sh
Env:
- Three node, node0 has more than 2/3 power
- Disable generation of empty blocks
- missed_block_threshold set to 5
- slash_wait_period set to 5 seconds
Procedure:
- Query and save staking address of node1 and node2.
- Stop node1 and node2.
- Keep sending tx to generate new blocks, gen missed_block_threshold blocks.
- Check punishment of staking address of node1 and node2.
- Wait slash_wait_period
- Check slash_amount
Compute expected slash_amount:
```
>>> 1/6
0.16666666666666666
>>> import math
>>> math.sqrt(0.166)
0.4074309757492673
>>> (0.407 + 0.407) ** 2
0.662596
>>> 0.662 * 0.1
0.0662
>>> 0.066 * 100000000000000000
6600000000000000
```
=> Problem (Fix #1061): no integration test for proportional slashing

Cargo.lock, client-common/Cargo.toml, client-core/Cargo.toml, client-network/Cargo.toml, test-common/Cargo.toml
solution:
* update signatory to v0.18 in tendermint
* update signatory to v0.18 in chain
=> Problem:(fix #927) failed to update signatory to 0.18

.drone.yml, ci-scripts/Dockerfile.fuzzer, ci-scripts/fuzzit.sh
Solution: added a script + drone pipeline that will build fuzzer on master
and create a job on fuzzit.dev
=> Problem: fuzzer not executed continously

cro-clib/Makefile, cro-clib/android.md, cro-clib/android_compile.sh, cro-clib/android_install.sh, cro-clib/examples/Makefile
Solution:  add android support
add lib for example
=> Problem:(cro-1140) no android support for c-bindings

client-core/src/transaction_builder/raw_transfer_transaction_builder.rs, client-network/src/network_ops/default_network_ops_client.rs
solution: 
* Add fee check for transfer tx on client-side
* check the staking address is jailed or not for the `deposit_bonded_stake` tx
=> Problem:(fix #1004) client doesn't validate transactions it generates

Cargo.lock, client-cli/Cargo.toml, client-cli/build.rs, client-cli/src/command.rs, client-cli/src/logo.rs, client-cli/src/main.rs
Solution:
* add a  blockchain cat logo designed by Carson
* play logo and jok when run `client-cli --version` and `client-rpc` starts up and chain-abci succefully start up.
* extend `client-cli --version`'s result, add compile-time and git commit version like "2020-02-25:4c86fbc"
=> Problem:(fix #815)technical user may experience boredom when running CLI

chain-abci/fuzz/fuzz_targets/abci_cycle.rs
Solution: checking that chain-id ends with two hex digits and using that,
otherwise using the default one
=> Problem: fuzzer may generate invalid chain-ids (fixes #1180)

chain-abci/fuzz/fuzz_targets/abci_cycle.rs
Solution: initialize mock bridge witch fuzzed network id if it's valid
=> Problem: mock validation in fuzzer may be initialised with wrong network id (fixes #1186)

client-cli/src/command.rs, client-core/src/synchronizer.rs, client-core/src/wallet/syncer.rs, client-rpc/src/rpc/sync_rpc.rs
Solution:
- Add progress_callback
- Remove progress_reporter
=> Problem (Fix #1188): WalletSyncer doesn't support callback to report progress

architecture-docs/README.md, architecture-docs/adr-002.md
Solution: drafted a proposal to switch to EDP
=> Problem: code sharing of client-side TLS between SGX and non-SGX is complex

chain-abci/tests/abci_app.rs
Solution:
- Add one in the `all_valid_tx_types_should_commit`.
=> Problem (Fix #1225): No unit test case for deposit into non exist(new) staking address

chain-abci/src/app/query.rs, chain-core/src/init/address.rs, client-common/src/seckey.rs, client-common/src/tendermint/lite.rs, client-common/src/tendermint/mock.rs, client-common/src/tendermint/types/block_results.rs, client-common/src/tendermint/websocket_rpc_client.rs, client-core/src/cipher/cert.rs, client-core/src/cipher/sgx.rs, test-common/src/block_generator.rs
Solution: removed the import statements
=> Problem: redudand import statements (found by clippy 1.42)

cro-clib/Makefile, cro-clib/download_ios.sh, cro-clib/examples/Makefile, cro-clib/examples/rpc.c
Solution: add ios example for wallet restoration, sync
=> Problem:(cro-1160) no ios example for c-binding#1160

chain-abci/src/app/mod.rs, chain-abci/src/app/slash_accounts.rs
Solution: Fix typo and broken link
=> Problem: (Fix #1243) ChainABCI comment has typo and broken link

Cargo.lock, Cargo.toml, chain-abci/src/app/query.rs, chain-tx-enclave/tx-query-next/README.md, chain-tx-enclave/tx-query-next/app-runner/Cargo.toml, chain-tx-enclave/tx-query-next/app-runner/src/main.rs, chain-tx-enclave/tx-query-next/enclave-app/Cargo.toml, chain-tx-enclave/tx-query-next/enclave-app/src/main.rs
Solution:
- added a bare minimum skeleton for runner that bridges zMQ connection
using userextension
(with documentation of current limitations)
=> Problem: no enclave runner which bridges zMQ (fixes #1229)

integration-tests/client-rpc/package-lock.json, integration-tests/client-rpc/package.json
Solution: Update mocha to latest version
=> Problem: (Fix #1263) mocha is out-of-dated

Cargo.lock, chain-abci/Cargo.toml, chain-abci/fuzz/Cargo.toml, chain-storage/Cargo.toml, dev-utils/Cargo.toml, test-common/Cargo.toml
Solution: bumped all related crate versions at once
=> Problem: latest kvdb fails to compile (fixes #1255)

client-rpc/src/rpc/wallet_rpc.rs
=> Problem (Fix #1299): typo in rpc endpoint name of wallet import

chain-abci/src/enclave_bridge/real/server.rs, chain-abci/src/enclave_bridge/real/test/seal.rs, chain-abci/tests/abci_app.rs, chain-abci/tests/tx_validation.rs, chain-tx-enclave/tx-query/enclave/src/lib.rs, chain-tx-validation/src/lib.rs, client-core/src/signer/dummy_signer.rs, client-core/src/transaction_builder/default_wallet_transaction_builder.rs, client-core/src/transaction_builder/raw_transfer_transaction_builder.rs, client-network/src/network_ops/default_network_ops_client.rs, cro-clib/src/transaction_build.rs, cro-clib/src/transaction_deposit.rs, enclave-protocol/src/lib.rs
Solution: deposit, transfer, withdraw enforce min fee;
(unbond tx already only had min fee)
adjusted tests
=> Problem: revised fees not implemented (fixes #1302)

client-core/src/transaction_builder/default_wallet_transaction_builder.rs
=> Problem: incorrect formatting in latest fmt

client-core/src/wallet/syncer.rs, integration-tests/bot/chainbot.py
Solution:
- Solved the bug in the wallet synconizer, incorrect fast forward logic.
=> Problem (Fix #1316): mutitx integration test fail occasionally

Cargo.lock, Cargo.toml, chain-tx-enclave/enclave-ra/ra-client/Cargo.toml, chain-tx-enclave/enclave-ra/ra-client/src/config.rs, chain-tx-enclave/enclave-ra/ra-client/src/lib.rs, chain-tx-enclave/enclave-ra/ra-client/src/verifier.rs, chain-tx-enclave/enclave-ra/ra-common/src/lib.rs, chain-tx-enclave/enclave-ra/ra-common/src/report.rs, chain-tx-enclave/enclave-ra/ra-common/src/sp/protocol.rs, chain-tx-enclave/enclave-ra/ra-enclave/.cargo/config, chain-tx-enclave/enclave-ra/ra-enclave/Cargo.toml, chain-tx-enclave/enclave-ra/ra-enclave/src/certificate.rs, chain-tx-enclave/enclave-ra/ra-enclave/src/cmac.rs, chain-tx-enclave/enclave-ra/ra-enclave/src/config.rs, chain-tx-enclave/enclave-ra/ra-enclave/src/context.rs, chain-tx-enclave/enclave-ra/ra-enclave/src/lib.rs, chain-tx-enclave/enclave-ra/ra-sp-client/src/client.rs, chain-tx-enclave/enclave-ra/ra-sp-server/Cargo.toml, chain-tx-enclave/enclave-ra/ra-sp-server/src/context.rs, chain-tx-enclave/enclave-ra/ra-sp-server/src/server.rs
Solution: Added `ra-enclave` (crate for creating attested TLS server) and `ra-client` (create for creating attestation checking TLS client). Fixes #860 #1228.
=> Problem: No attested TLS server + attestation checking TLS client

cro-clib/Cargo.toml, cro-clib/android.md, cro-clib/android_mac.md
=> Problem: (cro-1335) no guide for cbindings android compile on mac #1335

architecture-docs/adr-003.md
Solution:
- Write an adr for migrate to jellyfish-merle-tree
=> Problem: non-stable merkle trie library #802

architecture-docs/README.md, architecture-docs/adr-003.md
Solution: refined ADR-003 doc + updated the decision
=> Problem: no decision on the merkle trie storage (#802)

chain-abci/src/staking/table.rs, chain-abci/tests/abci_app.rs, chain-core/src/init/config.rs, chain-core/src/init/params.rs, chain-core/src/state/account.rs, chain-core/tests/verify_config.rs, client-common/src/tendermint/mock.rs, dev-utils/example-dev-conf.json, dev-utils/src/commands/genesis_dev_config.rs, docker/config/devnet/dev-conf.json, docker/config/devnet/tendermint/genesis.json, docker/config/testnet/tendermint/genesis.json, integration-tests/bot/chainbot.py, test-common/src/block_generator.rs, test-common/src/chain_env.rs
Solution: removed the no longer existant parameters as per the revised staking:
https://github.com/crypto-com/chain-docs/blob/master/docs/modules/punishment.md
https://github.com/crypto-com/chain-docs/blob/master/docs/getting-started/reward-and-punishments.md#punishments-network-parameters-for-slashing
=> Problem: unnecessary items in chain-core (fixes #1367)

client-network/src/network_ops/default_network_ops_client.rs
Solution:
- Fetch genesis_time in this case
=> Problem (Fix #1400) `get_last_block_time` returns zero before first block is generated

CHANGELOG.md
=> Problem: Missing changelog for punishment and staking transition changes

chain-abci/fuzz/fuzz_targets/abci_cycle.rs
Solution: updated the fuzzer target to the latest (post ADR-003) storage API
=> Problem: fuzzer code fails to compile (fixes #1438)

client-cli/src/command/transaction_command.rs, client-core/src/wallet.rs, client-core/src/wallet/default_wallet_client.rs, client-rpc/src/rpc/staking_rpc.rs, client-rpc/src/rpc/transaction_rpc.rs, client-rpc/src/rpc/wallet_rpc.rs, cro-clib/src/transaction.rs
solution: use BTreeSet instread of Vector
=> Problem: (fix #1242)client-rpc may include duplicate view keys

Makefile, docker/config/devnet/tendermint/genesis.json
Solution: Update Tendermint to 0.33 and update genesis.json
---
Fix #1461
=> Problem: (Fix #1461) Tendermint in Makefile is outdated

Cargo.lock, chain-abci/src/enclave_bridge/mock.rs, chain-tx-enclave/mock-utils/Cargo.toml, chain-tx-enclave/mock-utils/src/lib.rs, client-core/src/cipher/mock.rs
Solution:
- Change unwrap to Result
=> Problem (Fix #1479): mock-utils crash when provided with invalid tx payload

chain-abci/src/app/query.rs, chain-abci/tests/abci_app.rs, chain-storage/src/jellyfish.rs, integration-tests/bot/chaincodec.py, integration-tests/bot/chainrpc.py, integration-tests/bot/setup.py, integration-tests/bot/type_registry.json, integration-tests/multinode/reward_cluster.json, integration-tests/multinode/reward_test.py, integration-tests/run_multinode.sh
Solution:
- Add a dedicated reward integration test
Check:
- monetary expansion formula, tau decaying
- no reward for jailed node
- slashing is added to reward pool
Based on https://github.com/crypto-com/chain/pull/1466, rebase after that is merged.
=> Problem (Fix #1040): No reward distribution integration tests

CHANGELOG.md, Cargo.lock, client-common/Cargo.toml, client-core/Cargo.toml, client-network/Cargo.toml, integration-tests/multinode/byzantine_test.py, test-common/Cargo.toml
Solution:
- fix the evidence encoding in tendermint-rs
=> Problem (Fix #1506): block fetch failed when there is evidence in it

client-cli/src/command.rs, client-common/src/tendermint/client.rs, client-common/src/tendermint/rpc_client/sync_rpc_client.rs, client-common/src/tendermint/unauthorized_client.rs, client-core/src/cipher/default.rs, client-core/src/cipher/mock.rs, client-core/src/wallet/default_wallet_client.rs, client-core/src/wallet/syncer.rs, client-network/src/network_ops/default_network_ops_client.rs, client-rpc/src/rpc/multisig_rpc.rs, client-rpc/src/rpc/wallet_rpc.rs, cro-clib/src/transaction.rs, test-common/src/block_generator.rs
Solution:
- Add the parameters, and do the nessesary changes.
=> Problem (Fix #1499): query api in tendermint client trait don't support height and prove

chain-tx-enclave/mock-utils/src/lib.rs
Solution:
- Change the return value of unpad_payload to Result
=> Problem (Fix #1485): mock-utils may crash when the payload is less than 16 bytes

chain-abci/src/app/mod.rs
Solution:
- Set version in info handler regardless of state
=> Problem (Fix #1527): app version not set on the first startup

Cargo.lock, client-rpc/Cargo.toml, client-rpc/src/rpc/multisig_rpc.rs, client-rpc/src/rpc/staking_rpc.rs, client-rpc/src/rpc/sync_rpc.rs, client-rpc/src/rpc/transaction_rpc.rs, client-rpc/src/rpc/wallet_rpc.rs
Solution:
- Remove the unused dependencies
Related: #1483
=> Problem (#1483): jsonrpc-client dependency is unused

Cargo.lock, client-cli/Cargo.toml, client-cli/src/logo.rs
solution: remove `console` crate in client-cli.
=> Problem: (fix #1490) unnecessary dependency in client-cli

chain-abci/src/app/app_init.rs, chain-abci/src/app/mod.rs, chain-abci/src/enclave_bridge/real/server.rs, chain-abci/src/enclave_bridge/real/test/seal.rs, chain-abci/src/staking/mod.rs, chain-abci/src/staking/tx.rs, chain-abci/src/storage/mod.rs, chain-abci/tests/abci_app.rs, chain-abci/tests/punishment.rs, chain-abci/tests/tx_validation.rs, chain-core/src/lib.rs, test-common/src/block_generator.rs, test-common/src/chain_env.rs
Solution:
- Fetch max evidence age from consensus parameter and store in chain
state
- Filter evidences against it
=> Problem (Fix #987): byzantine punishment doesn’t take evidence age in to account

dev-utils/example-dev-conf.json, dev-utils/src/commands/genesis_command.rs, dev-utils/src/main.rs
solution:
* fix example-dev-conf.json
* add unit test
* print out the source error
=> Problem: (fix #1434) outdated dev-utils example

chain-abci/fuzz/fuzz_targets/abci_cycle.rs
Solution: updated the fuzz target to include evidence age in initchain request
=> Problem: fuzzer crashes with invalid evidence age (fixes #1536)

CHANGELOG.md, chain-abci/src/app/app_init.rs, chain-abci/src/app/mod.rs, chain-abci/src/enclave_bridge/real/server.rs, chain-abci/src/enclave_bridge/real/test/seal.rs, chain-abci/src/staking/mod.rs, chain-abci/src/staking/table.rs, chain-abci/src/storage/mod.rs, chain-abci/tests/abci_app.rs, chain-abci/tests/tx_validation.rs, chain-abci/tests/validator_changes.rs, chain-core/src/init/params.rs, chain-core/src/lib.rs, chain-core/src/tx/fee/mod.rs, chain-core/tests/verify_config.rs, client-core/src/wallet/syncer.rs, dev-utils/src/commands/genesis_command.rs, dev-utils/src/commands/genesis_dev_config.rs, docker/config/devnet/tendermint/genesis.json, integration-tests/bot/chainbot.py, test-common/src/block_generator.rs, test-common/src/chain_env.rs
Solution:
- Remove unbonding_period parameter, use max_evidence_age of consensus
parameter instead.
=> Problem (Fix #1016): jail period/unbonding time is not verified against maximum evidence age

Cargo.lock, dev-utils/Cargo.toml, dev-utils/src/commands.rs, dev-utils/src/commands/test_vector_command.rs, dev-utils/src/dev_utils.rs
the result is:
```
{
"withdraw_unbounded_vector": {
"transfer_address": "cro1duepg06jrlgpdphxlnfrt3lxu95mdpl5g03vxn89yzhvdl74p6ms4ursr6",
"staking_address": "cro13xh025aqd2cvx9e7080pecjp48knhxfv40entz",
"witness": "000149553434c87cdb2fa8fbfb251d83143401077f3d09b9ed770f43493ce35abf7920332c095b599235b5088e8188de3f45b296c30f55405c0ddff6d71bf3d28ce1",
"payload": "00000000000000000000000000000000000000003d040d0f0f0f0f0f0f0f0f1f0f603d1b305d10df1989e9f3dd3ac8e9ee66b988fb4cedcc43ea2fa1c9f0da01b80feefa0a0f0f0f0f0e0f0f0f0f0f0f0f0f0f603d1b305d10df1989e9f3dd3ac8e9ee66b988fb4cedcc43ea2fa1c9f0da01b80fcde4040f0f0f0f0e0f0f0f0f0f0f0f0f0f603d1b305d10df1989e9f3dd3ac8e9ee66b988fb4cedcc43ea2fa1c9f0da01b80feefa0a0f0f0f0f0e0f0f0f0f0f0f0f0f0f603d1b305d10df1989e9f3dd3ac8e9ee66b988fb4cedcc43ea2fa1c9f0da01b87d751f7d …
```
=> Problem: (fix #1493) no way to generate test vectors in dev-utils

NOTICE, chain-abci/src/app/rewards.rs, chain-core/Cargo.toml, chain-core/src/common/mod.rs, chain-core/src/fixed/continued_fraction.rs, chain-core/src/fixed/display.rs, chain-core/src/fixed/div.rs, chain-core/src/fixed/mod.rs, chain-core/src/fixed/mul.rs, chain-core/src/lib.rs
Solution:
- Review and vendor-in related code into chain-core and document them.
=> Problem (Fix #805): fixed package is not reviewed

Cargo.lock, dev-utils/Cargo.toml, dev-utils/src/commands/test_vector_command.rs
Solution:
added details needed in the basic write up: https://github.com/crypto-com/chain-docs/pull/137
- keypair and address details
- network id based on doc conventions
- more realistic council node info
- deposit stake transaction id
=> Problem: test-vector command misses a few details (fixes #1597)

client-cli/src/command/multisig_command.rs
=> Problem: Typo in client-cli multisig operation

Cargo.lock, Makefile, client-cli/src/command.rs, client-core/Cargo.toml, client-core/src/wallet/syncer.rs, client-rpc/server/src/program.rs, dev-utils/src/commands/genesis_command.rs, integration-tests/bot/chainbot.py
check the genesis app hash from tendermint with the trusted one when `get_genesis_sync_state`
=> Problem: (fix #1545)light client doesn't verify genesis hash

.travis.yml, Cargo.lock, Cargo.toml, chain-tx-enclave/enclave-ra/ra-sp-server/src/context.rs, docker/build.sh
Solution:
- fix the compile error
=> Problem (Fix #1648): build ra-sp-server failed

client-core/src/service/wallet_service.rs
Solution:
- Update the error message.
=> Problem: (Fix#1533) Error messages is ambiguous for node-join/unbond Txs 

Makefile, integration-tests/bot/chainbot.py, integration-tests/bot/client_cli.py, integration-tests/pytests/test_client_cli.py, integration-tests/run.sh, integration-tests/zero_fee_cluster.json
Solution:
* create a python lib for client-cli
* add integration test for client-cli
* transfer transaction failed in client-cli, currently only test withdraw transaction
=> Problem: (fix #1555) add integration tests for client-cli

Cargo.lock, chain-tx-enclave-next/mls/Cargo.toml, chain-tx-enclave-next/mls/src/group.rs, chain-tx-enclave-next/mls/src/key.rs, chain-tx-enclave-next/mls/src/message.rs, chain-tx-enclave-next/mls/src/tree.rs
Solution:
- added MLSPlainTest message signing + verification
- encoding/decoding code for related data types
- a small test to check signing-verify works
NOTE/WIP follow-up to https://github.com/crypto-com/chain/pull/1659
still missing secret derivations, message processing etc.
=> Problem: no MLS group creation procedure (WIP #1617)

chain-abci/src/staking/tx.rs, client-rpc/src/rpc/staking_rpc.rs, test-common/src/block_generator.rs
Solution:
- Fix reference time in block generator
=> Problem (Fix #1676): mock keypackages failing unit tests

client-cli/src/command/wallet_command.rs, client-core/src/service/root_hash_service.rs, client-core/src/service/wallet_service.rs, client-core/src/wallet/default_wallet_client.rs, integration-tests/pytests/test_client_cli.py
solution:
* fix encode/decode method for Wallet
* add key pairs and multisig addresses in WalletInfo
* restore key pair, private keys, multisig addresses and root hash when import wallet
=> problem: (fix #1610) can not find wallet name in wallet list after import success from a file

chain-abci/src/staking/tx.rs, chain-core/src/init/config.rs, chain-tx-enclave-next/mls/src/group.rs, chain-tx-enclave-next/mls/src/keypackage.rs, chain-tx-enclave-next/mls/src/tree.rs, chain-tx-enclave-next/mls/tests/verify_test_vectors.rs, client-common/src/keypackage.rs
Solution:
- pass them by reference
=> Problem: no need to clone attestation certificate verifier

chain-tx-enclave-next/mls/src/group.rs, chain-tx-enclave-next/mls/src/keypackage.rs, chain-tx-enclave-next/mls/src/message.rs, chain-tx-enclave-next/mls/src/tree.rs
Solution:
- basic processing (missing the parts that were not implemented yet elsewhere)
- extended the unit test to check the resulting context from processing Welcome and Commit
=> Problem: mls commit message not processed (fixes #1706)

chain-tx-enclave-next/mls/src/group.rs, chain-tx-enclave-next/mls/src/lib.rs, chain-tx-enclave-next/mls/src/tree.rs, chain-tx-enclave-next/mls/src/tree_math.rs
Solution:
- included proposed fixes (5ee9f5d) to the tree math draft
- explicit types for node and leaf indices
=> Problem (WIP #1703): incorrect tree hashing in mls modules

chain-tx-enclave-next/mls/src/astree.rs, chain-tx-enclave-next/mls/src/ciphersuite.rs, chain-tx-enclave-next/mls/src/group.rs, chain-tx-enclave-next/mls/src/lib.rs, chain-tx-enclave-next/mls/src/secrets.rs, chain-tx-enclave-next/mls/src/tree.rs
Solution:
- added basic application secrets tree + derivation code
- updated group secrets to initialize application secrets
=> Problem: no application secrets in mls (fixes #1737)

client-cli/src/command/wallet_command.rs, client-core/src/hd_seed.rs, client-core/src/mnemonic.rs, client-core/src/service/mock_hw_key_service.rs, client-core/src/signer/wallet_signer.rs, client-core/src/transaction_builder/default_wallet_transaction_builder.rs, client-core/src/wallet.rs, client-core/src/wallet/default_wallet_client.rs, client-core/src/wallet/syncer.rs, client-core/src/wallet/syncer_logic.rs, client-network/src/network_ops/default_network_ops_client.rs, client-rpc/src/rpc/multisig_rpc.rs, client-rpc/src/rpc/wallet_rpc.rs, cro-clib/src/wallet.rs, dev-utils/src/commands/init_command.rs
Solution: add mnemonics word count in wallet creation
for example)
word count ==12, 12 mnemonics
word count ==24, 24 mnemonics
=> Problem: no 12 words mnemonics option for HDWallet (fix #1694)

client-core/src/wallet/syncer_logic.rs, integration-tests/bot/client_cli.py, integration-tests/pytests/test_client_cli.py
solution:
* when the transaction type is `Deposit` and the inputs belong to self-wallet,  make the tx history as `Input` and the amount is `sum(input)` 
* add some integration tests.
=> Problem: (fix #1614) outgoing wallet deposit amount is not displayed

ROADMAP.md
Solution: updated the "ROADMAP" document
with several areas that would be worth exploring
in the long-term future post-mainnet development.
=> Problem: no long-term roadmap documented

client-cli/src/command/transaction_command.rs
Solution: 
Change it to _"Import a transaction from the given plain transaction data"_.
=> Problem: Incorrect client-cli help information for Tx importing

chain-tx-enclave-next/mls/src/ciphersuite.rs, chain-tx-enclave-next/mls/src/group.rs, chain-tx-enclave-next/mls/src/key.rs, chain-tx-enclave-next/mls/src/keypackage.rs, chain-tx-enclave-next/mls/src/secrets.rs, chain-tx-enclave-next/mls/src/tree.rs, chain-tx-enclave-next/mls/src/tree_math.rs
Solution:
- Implement ratchet tree evolution
- Populate DirectPath for init_commit
- support apply the path secrets when apply commit message
=> Problem (Fix #1703): incorrect tree hashing in mls modules

chain-core/BUILD-WASM.md
=> Problem: no instructions for compiling chain-core to WASM#1690

chain-tx-enclave-next/mls/src/ciphersuite.rs, chain-tx-enclave-next/mls/src/group.rs, chain-tx-enclave-next/mls/src/keypackage.rs, chain-tx-enclave-next/mls/src/lib.rs, chain-tx-enclave-next/mls/src/main.rs, chain-tx-enclave-next/mls/src/message.rs, chain-tx-enclave-next/mls/src/tree.rs
Solution:
- process update/remove proposal and add unit test
=> Problem (Fix #1787 #1788): no update/remove proposal processing in mls module

client-core/src/wallet/syncer_logic.rs, cro-clib/chain.h, cro-clib/examples/Makefile, cro-clib/src/jsonrpc.rs, cro-clib/src/transaction_build.rs
Solution: fix ffi issue and change progress_callback for example c-code, also fix clippy issue
=> Problem: broken nightly compilation due to FFI pass-by-value array in cro-clib (fix #1826)

chain-tx-enclave-next/mls/src/astree.rs, chain-tx-enclave-next/mls/src/group.rs, chain-tx-enclave-next/mls/src/message.rs, chain-tx-enclave-next/mls/src/tree.rs, chain-tx-enclave-next/mls/src/tree_math.rs
Solution:
- refactor tree math api,
- also change to use u32 since messages in mls use u32 to encode the node index.
=> Problem (Fix #1833): mls tree math api don't separate leaf and parent in type

chain-storage/Cargo.toml, chain-storage/src/lib.rs, client-core/Cargo.toml, client-network/Cargo.toml
Solution:
- make kvdb-rocksdb dependency in chain-storage optional
=> Problem (Fix #1832): unnecessary rocksdb dependency in clients

Makefile, ci-scripts/run_chain_abci.sh, docker/Dockerfile
Solution: Provide an option to customize the hostname
-----
Fix #1849
=> Problem: (Fix #1849) Makefile run chain-abci with tx_query set to docker hostname

client-core/src/hd_seed.rs, client-core/src/hd_wallet/key_chain/chain_path.rs, client-core/src/service/hd_key_service.rs, client-core/src/service/hw_key_service.rs, client-core/src/service/mock_hw_key_service.rs, client-core/src/service/wallet_service.rs, client-core/src/signer/wallet_signer.rs, client-core/src/wallet/default_wallet_client.rs, docker/build.sh, integration-tests/bot/chainbot.py, integration-tests/bot/client_cli.py, integration-tests/pytests/test_client_cli.py
solution:
* add hd_path in client-* side
* modify mock_hardware_wallet
* add mock hardware wallet in integration test
* add hd_path and hdkey information when export and import wallet
=> Problem: (fix #1790) client-* cannot obtain HD path for HW wallet operations

Cargo.lock, Cargo.toml
Solution: Upgraded ring to latest version
=> Problem: ring is not updated to latest version

architecture-docs/adr-002.md
Solution: documented additional consequences
uncovered during development
=> Problem: incomplete consequences in ADR-002

client-common/src/tendermint/types/block_results.rs, client-core/src/wallet/syncer.rs, client-core/src/wallet/syncer_logic.rs, integration-tests/cleanup.sh
solution: handle the block if transactions in the block is/are the self outgoing staking transaction(s)
=> Problem: (fix #1978) Outgoing deposit history is not displayed

Makefile, client-cli/src/command.rs, client-rpc/server/src/program.rs, client-rpc/server/src/server.rs, integration-tests/bot/chainbot.py, integration-tests/bot/client_cli.py, integration-tests/pytests/test_client_cli.py
disabled fast forward is the default option
--enable-fast-forward to activate `fast forward`
=> Problem: unsafe default option for client-* (fix #1869)

cro-clib/chain.h, cro-clib/src/jsonrpc.rs, integration-tests/bot/chainbinding.py
=> Problem: unnecessary `mock` function argument in cro-clib (fix #1792)

integration-tests/run.sh, integration-tests/run_multinode.sh
Solution:
- fix the virtual env directory.
=> Problem (Fix #1942): running integration-tests/run.sh manually failed

.travis.yml
Solution: added NETWORK_ID environment variable to travis ci
=> Problem: kcov fails on nightly (fixes #1946)

docker/config/devnet/tendermint/genesis.json, integration-tests/bot/chainbot.py, integration-tests/bot/client_cli.py, integration-tests/pytests/test_client_cli.py
solution: add integration test of deposit/withdraw/transfer between two wallets
=> Problem: (fix #1868) no integration tests for cross-wallet operations

chain-abci/src/app/mod.rs, chain-abci/tests/abci_app.rs, integration-tests/run.sh
solution: get info from storage.
=> Problem: (fix #1828)abci info endpoint returns uncommitted state

client-core/src/wallet/syncer.rs
Solution:
- disable it, use status api directly
=> Problem: light client verification is not disabled when fast forward enabled

Cargo.lock, Cargo.toml, chain-util/Cargo.toml, chain-util/src/lib.rs, chain-util/src/non_empty.rs, client-core/Cargo.toml, client-core/src/wallet/syncer.rs, client-core/src/wallet/syncer_logic.rs, docker/unittest.sh
Solution:
- put it into chain-util crate.
=> Problem: non-empty-vec don't have security scrutiny

Cargo.lock, chain-tx-enclave-next/mls/Cargo.toml, chain-tx-enclave-next/mls/src/group.rs, chain-tx-enclave-next/mls/src/tree.rs
Solution:
- separated `TreeSecret`
=> Problem (Fix #1979): ratchet tree mixed public and private informations

Cargo.lock, chain-tx-enclave-next/mls/Cargo.toml, chain-tx-enclave-next/mls/src/ciphersuite.rs, chain-tx-enclave-next/mls/src/group.rs, chain-tx-enclave-next/mls/src/key.rs, chain-tx-enclave-next/mls/src/keypackage.rs, chain-tx-enclave-next/mls/src/secrets.rs, chain-tx-enclave-next/mls/src/tree.rs
Solution:
- better error hierarchy
- convert panic operation to error propogation
- better comment on internal invariants panic
> `astree.rs` is not touched in this pr.
=> Problem (Fix #1784): possible panic of operations in mls modules

.github/workflows/audit.yml, .github/workflows/rust.yml, bors.toml
Solution: switch to github actions
=> Problem: Travis CI doesn't report back on push event status (fixes #2060)

.github/actions-rs/grcov.yml, .github/workflows/rust.yml, codecov.yml
Solution: a few fixes to the workflow
=> Problem: github actions fail

Makefile
Solution: 
1. Generate key on the fly in makefile for both tx-query-next and tx-validation-next.
2. Combine tx-query-next and tx-validation-next in one container to built to shorten build time.
=> Problem: (fix #2064)devnet missing private key for sgxs-sign

chain-tx-enclave-next/mls/src/ciphersuite.rs, chain-tx-enclave-next/mls/src/group.rs, chain-tx-enclave-next/mls/src/lib.rs, chain-tx-enclave-next/mls/src/secrets.rs, chain-tx-enclave-next/mls/src/tree.rs
https://github.com/mlswg/mls-protocol/compare/c3db39266505e9d202158d642d65918d35870e77...d1d5f56a5d83781042d19c830497ab5aa104907f
Solution:
- don't special case the first commit to populate path secrets
- commit secret should be zeroes when not populate path secrets (https://github.com/mlswg/mls-protocol/pull/385)
- fix path_secret in welcome message
- fix a vec indexing panic
=> Problem: mls protocol not up-to-date

client-common/src/storage.rs, client-common/src/storage/memory_storage.rs, client-common/src/storage/sled_storage.rs, client-common/src/storage/unauthorized_storage.rs, client-core/src/wallet.rs, client-core/src/wallet/default_wallet_client.rs, client-core/src/wallet/syncer.rs, client-rpc/src/handler.rs, client-rpc/src/rpc/sync_rpc.rs, client-rpc/src/rpc/wallet_rpc.rs
Solution: add flushing
in recent sled, flushing is not working as previous version.
flushes on drop only.
so added manual flushing to `db writing` functions
(sled Config.flush_every_ms didn't work)
=> Problem: client-rpc doen't flush sled database, possibly causes lost data (fix #2100)

client-cli/src/command.rs, client-rpc/src/handler.rs
Solution: change default trusting period to max_evidence_age/2
=> Problem: unsafe default setting of the trusting period  (fix #2117) 

chain-abci/fuzz/fuzz_targets/abci_cycle.rs
Solution: adapted the fuzzer target to the latest chain-abci change
=> Problem: fuzzer fails to compile

client-cli/src/command.rs
=> Problem: client-cli sync produces panic after sync #2138

chain-tx-enclave-next/mls/src/group.rs
Solution:
- update implementation according to spec
=> Problem (Fix #2145): incorrect confirmed_transcript_hash calculation in mls

Makefile, ci-scripts/Dockerfile
Solution: update Makefile and ci-scripts/Dockerfile
=> Problem: (fix #2162)devnet cannot build after #2140

chain-abci/fuzz/fuzz_targets/abci_cycle.rs, chain-abci/src/app/app_init.rs, chain-abci/src/app/query.rs, chain-abci/src/main.rs, chain-abci/tests/abci_app.rs, test-common/src/chain_env.rs
Solution: Add ABCI `query` to fetch TDBE connection details
=> Problem: TDBE connection details are not exposed in tendermint RPC

chain-core/src/init/address.rs, cro-clib/src/jsonrpc.rs
Solution: remove un-necessary unit test
=> Problem: legacy redeem address textual conversion code (fix #2150)

client-cli/src/command.rs, client-cli/src/command/address_command.rs, client-cli/src/command/transaction_command.rs, client-cli/src/command/wallet_command.rs, client-core/src/hd_wallet/wallet_kind.rs, client-core/src/service/wallet_service.rs, client-core/src/signer/wallet_signer.rs, client-core/src/transaction_builder/default_wallet_transaction_builder.rs, client-core/src/wallet.rs, client-core/src/wallet/default_wallet_client.rs, client-core/src/wallet/syncer.rs, client-core/src/wallet/syncer_logic.rs, client-network/src/network_ops/default_network_ops_client.rs, client-rpc/src/rpc/multisig_rpc.rs, client-rpc/src/rpc/wallet_rpc.rs, dev-utils/src/commands/init_command.rs, integration-tests/bot/client_cli.py, integration-tests/pytests/test_client_cli.py
solution:
* add harware wallet type in the storage when create a new wallet
* remove --hardware in client-cli transaction
=> Problem: (issue-2135) client-* doesn't know the wallet type from storage

chain-tx-enclave-next/enclave-ra/ra-sp-server/src/context.rs
Solution: Added 6 retries for `AesmClient` at an interval of 2 secs each. Fixes #2175.
=> Problem: ra-sp-server crashes sometimes

Cargo.lock, chain-core/src/init/config.rs, chain-tx-enclave-next/tdbe/enclave-app/Cargo.toml, chain-tx-enclave-next/tdbe/enclave-app/src/sgx_module.rs, chain-tx-enclave-next/tx-validation-next/src/sgx_module.rs, chain-tx-enclave/enclave-macro/src/lib.rs, dev-utils/src/commands/genesis_command.rs, dev-utils/src/commands/genesis_dev_config.rs, docker/build.sh
Solution:
- preliminary try implemented in build.sh
=> Problem (WIP #1996): no support for genesis build procedure involving TDBE

client-cli/src/command.rs, client-core/src/wallet/syncer.rs, client-core/src/wallet/syncer_logic.rs
Solution: display progress only in validation
=>  Problem: Ambiguous "synchronization complete" message (fix #2168)

client-core/src/wallet/syncer.rs
=> Problem: client-cli wallet sync in integration test fail occasionally (fix #2093)

.dockerignore, Makefile, docker/Dockerfile
=> Problem: (fix #2196)Cannot compile tx-validation-next in devnet

.travis.yml, ci-scripts/install_protoc.sh
Solution:
- added a step install a newer protoc
=> Problem: Travis CI building fails (fixes #2226)

client-common/src/cipher/mock.rs, cro-clib/chain-core.h, cro-clib/chain.h
Solution: small style fix + c binding regen
=> Problem: clippy in 1.47 fails

chain-abci/Cargo.toml, client-common/Cargo.toml, client-core/Cargo.toml, client-core/src/wallet/default_wallet_client.rs, integration-tests/pytests/test_wallet_offline.py
Solution: fixed tokio version to 0.2.22
+ small unit test fix
=> Problem: Dependabot can't resolve Rust dependency files (fixes #2308)

README.md, architecture-docs/adr-001.md, architecture-docs/adr-002.md, chain-core/src/mls/mod.rs, chain-tx-enclave-next/enclave-ra/ra-client/src/verifier.rs, chain-tx-enclave-next/mls/src/extras/mod.rs, chain-tx-enclave-next/mls/src/extras/validation.rs, chain-tx-enclave-next/mls/src/lib.rs, chain-tx-enclave-next/tdbe/enclave-app/src/sgx_module.rs
Some quick thaler-docs redirections.
=> Thaler docs redirection

.github/workflows/rust.yml, chain-core/src/state/account/op/data/deposit.rs, chain-core/src/tx/data/mod.rs, chain-core/src/tx/mod.rs, chain-core/src/tx/witness/mod.rs, chain-tx-enclave-next/enclave-ra/ra-client/src/verifier.rs, chain-tx-enclave-next/enclave-ra/ra-common/src/report.rs, chain-tx-enclave-next/enclave-ra/ra-enclave/src/context.rs, chain-tx-enclave-next/enclave-ra/ra-sp-client/src/client.rs, chain-tx-enclave-next/enclave-ra/ra-sp-server/src/ias_client.rs, enclave-protocol/src/lib.rs
Solution:
- fixed clippy issues for new rust tooling
- added apt-get update to GH CI actions
=> Problem: package installation fails on GH CI (fixes #2344)

Cargo.lock, Cargo.toml
=> Bumped ring patch to latest sgx-env (rebased with 0.16.19)
