- CONTRIBUTING.md
Solution: created a new repo and fixed the link in CONTRIBUTING.md
> Problem: broken documentation link

- Cargo.lock
- client-common/Cargo.toml
- client-common/src/balance/balance_change.rs
- client-common/src/balance/transaction_change.rs
- client-common/src/error.rs
- client-common/src/storage.rs
- client-common/src/storage/memory_storage.rs
- client-core/src/service/key_service.rs
- client-core/src/service/wallet_service.rs
- client-core/src/test.rs
- client-index/Cargo.toml
- client-index/src/index.rs
- client-index/src/index/rpc_sled_index.rs
- client-index/src/lib.rs
- client-index/src/service.rs
- client-index/src/service/address_service.rs
- client-index/src/service/balance_service.rs
- client-index/src/service/global_state_service.rs
- client-index/src/service/transaction_outputs_service.rs
- client-index/src/service/transaction_service.rs
- client-index/src/tendermint.rs
- client-index/src/tendermint/rpc_client.rs
- client-index/src/tendermint/types/block.rs
- client-index/src/tendermint/types/block_results.rs
- client-index/src/tendermint/types/genesis.rs
- client-index/src/tendermint/types/status.rs
- client-index/src/test.rs
- client-index/src/test/mock_client.rs
Solution: Created transaction index
Details:
- `Index` is the main trait which has functions to get balance, transaction history, etc.
- A default implementation of `Index` trait is provided by `RpcSledIndex` which uses `jsonrpc` for making rpc calls to tendermint and `sled` for storage
- There are other services which is used for synchronising current state of `Index` with Crypto.com Chain
> Problem: (CRO-53) No easy way to query transaction data from Chain

- README.md
Solution: Updated README to include `rustflags` configurations and update the documentation to include the latest deployment steps.
> Problem: (CRO-90) cargo build fails if README instructions are followed

- client-common/src/tendermint/rpc_client.rs
On testing the Tendermint RPC client it shows unstable request from time to time. The problem is that the `jsonrpc` crate use Hyper as the underlying HTTP client, but the crate does not handle connection reset correctly, hence causing unstable request. The issue is filed below
https://github.com/apoelstra/rust-jsonrpc/issues/26
Create a new client on every JSON-RPC call as a workaround
The current solution is a workaround and is inefficient. In the future we should keep track of the `jsonrpc` issue and take appropriate response.
> Problem: (CRO-99) jsonrpc client does not handle underlying connection reset properly

- Cargo.lock
- client-common/Cargo.toml
- client-common/src/storage.rs
- client-core/Cargo.toml
- client-core/src/service/key_service.rs
- client-core/src/service/wallet_service.rs
- client-core/src/wallet.rs
- client-core/src/wallet/default_wallet_client.rs
- client-rpc/Cargo.toml
- client-rpc/src/wallet_rpc.rs
**Solution**: Started using secstr which provides secure strings.
**Note on security**: Current implementation uses deserialization feature provided by `secstr` crate which uses `serde`. To obtain a `SecStr` object from `&str`, they copy all the bytes from `&str` provided by serde. Its not possible to zeroize `&str` provided by serde because we never get a mutable reference from serde. [here](https://github.com/myfreeweb/secstr/blob/master/src/lib.rs#L220) is the line where they make a copy of `&str`.
> Problem: (CRO-104) Plain insecure strings for passphrases

- Cargo.lock
- chain-abci/benches/hashes.rs
- chain-abci/src/app/app_init.rs
- chain-abci/src/app/commit.rs
- chain-abci/src/app/mod.rs
- chain-abci/src/app/query.rs
- chain-abci/src/storage/mod.rs
- chain-abci/src/storage/tx.rs
- chain-core/src/common/merkle.rs
- chain-core/src/init/coin.rs
- chain-core/src/init/config.rs
- chain-core/src/lib.rs
- chain-core/src/state/mod.rs
- chain-core/src/tx/fee/mod.rs
- chain-core/src/tx/mod.rs
- client-common/src/tendermint/types/genesis.rs
- client-index/src/index/default_index.rs
- dev-utils/Cargo.toml
- dev-utils/src/commands/genesis_command.rs
This a work-in-progress PR that will lead to a simple transaction fee system, sketched out in the specs: https://github.com/crypto-com/chain-docs/blob/master/docs/staking.md#transaction-fee
I guess I'll split it into two PRs -- this one will just add a InitChain initialisation of the rewards pool; the other PR will then extend TX, add fee-related network parameters and TX fee validation logic.
(reward distribution will be then another PR some time in the future)
added @CeruleanAtMonaco  as a reviewer to double check the initialisation assumption, as she authored the ERC20 contract. The assumption is that the rewards pool will be initialised from:
1. long term incentive address
2. secondary distribution and launch incentive address -- this one is actually two addresses, as the contract …
> Problem: nowhere to pay fees to (CRO-94)

- Cargo.lock
- client-cli/Cargo.toml
- client-cli/src/main.rs
- client-common/Cargo.toml
- client-common/src/storage.rs
- client-core/Cargo.toml
- client-core/src/service/key_service.rs
- client-core/src/service/wallet_service.rs
- client-core/src/transaction_builder.rs
- client-core/src/transaction_builder/default_transaction_builder.rs
- client-core/src/transaction_builder/unauthorized_transaction_builder.rs
- client-core/src/wallet.rs
- client-core/src/wallet/default_wallet_client.rs
- client-rpc/Cargo.toml
- client-rpc/src/wallet_rpc.rs
Solution: Use `SecUtf8` instead of `SecStr` which supports deserialization from String to secure string
> Problem: Client RPC requires passphrase to be a byte array

- Cargo.lock
- chain-abci/Cargo.toml
- chain-abci/src/app/app_init.rs
- chain-abci/src/app/commit.rs
- chain-abci/src/app/mod.rs
- chain-abci/src/app/validate_tx.rs
- chain-abci/src/main.rs
- chain-abci/src/storage/account/tree.rs
- chain-abci/src/storage/mod.rs
- chain-abci/src/storage/tx.rs
- chain-core/src/state/account.rs
- chain-core/src/state/mod.rs
- chain-core/src/tx/mod.rs
- client-core/src/transaction_builder/default_transaction_builder.rs
- client-index/src/index/default_index.rs
Solution: extended TX types, added TODO stubs in pattern matches; extended storage to choose between main and account-related storage; moved to use a nightly merkle_bit crate (as the old struct wasn't Sync+Send)
--
this is more of WIP PR to add core data types before breaking changes due to InitConfig, InitChain processing, TX validation etc. come in.
> Problem: missing types and integration for account/staking-related functionality (CRO-96 / CRO-97)

- Cargo.lock
- client-cli/Cargo.toml
- client-common/Cargo.toml
- client-core/Cargo.toml
- client-rpc/Cargo.toml
Solution: Changed from pointing to GitHub repository `v0.3.2` tag to crates.io
> Problem: (CRO-120) SecStr bumped version to 0.3.2 on crates.io but we are still pointing to GitHub repository

- Cargo.lock
- chain-abci/Cargo.toml
chain-abci has Builder::init error and cannot be started
```
thread 'main' panicked at 'Builder::init should not be called after logger initialized: SetLoggerError(())', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
`rust-abci` recently upgraded to [0.5.1](https://github.com/crypto-com/chain/commit/d1941f434684be1d083973a8297face33741a656) in which it added `evn_logger` initialization. Since env_logger only allows one initialization, chain-abci panic.
Revert "Bump abci from 0.5.0 to 0.5.1 (#97)"
This reverts commit d1941f434684be1d083973a8297face33741a656.
> Problem: (CRO-122) chain-abci has Builder::init error and cannot be started

- Cargo.lock
- chain-core/src/common/merkle_tree.rs
- chain-core/src/tx/witness/tree.rs
- client-cli/src/command/wallet_command.rs
- client-common/src/error.rs
- client-core/Cargo.toml
- client-core/src/key/public_key.rs
- client-core/src/lib.rs
- client-core/src/service.rs
- client-core/src/service/key_service.rs
- client-core/src/service/multi_sig_service.rs
- client-core/src/service/wallet_service.rs
- client-core/src/transaction_builder/default_transaction_builder.rs
- client-core/src/wallet.rs
- client-core/src/wallet/default_wallet_client.rs
Solution: Added a basic support for creating m-of-n tree addresses in client
- This PR only has support for creating addresses is and not signing multi-sig transactions.
- Signing will be a part of different PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crypto-com/chain/108)
> Problem: (CRO-123) No support for creating tree multi-sig addresses in client

- Cargo.lock
- chain-abci/Cargo.toml
- chain-core/Cargo.toml
- client-core/Cargo.toml
Solution: the original dependency's branch was force-pushed rebased and the current HEAD fails to compile schnorr.
this uses a custom fork with a fix
> Problem: build fails checking out secp256k1-zkp submodule -- should fix #111

- client-core/src/key/private_key.rs
- client-core/src/key/public_key.rs
- client-core/src/service/multi_sig_address_service.rs
- client-core/src/service/multi_sig_session_service.rs
- client-core/src/service/wallet_service.rs
- client-core/src/wallet.rs
- client-core/src/wallet/default_wallet_client.rs
Solution: Added support for simple schnorr signatures for 1-of-n transactions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crypto-com/chain/117)
> Problem: (CRO-127) No support for simple schnorr signatures for 1-of-n transactions

- integration-tests/client-rpc/package.json
- integration-tests/client-rpc/yarn.lock
Solution: Upgraded Axios to v0.19.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crypto-com/chain/123)
> Problem: (CRO-216) Axios v0.18.0 has vulnerability CVE-2019-10742

- chain-core/src/tx/data/address.rs
- client-core/src/transaction_builder/default_transaction_builder.rs
- client-core/src/unspent_transactions.rs
**Solution**: 
Added a concept of operations that can be applied to unspent transactions:
- There are three type of operations:
- Filter
- Sort
- GroupBy
- Filter and Sort are self explanatory
- GroupBy will divide unspent transactions in two groups and will apply subsequent operations
to each group separately.
- This can be used to achieve a usecase where we want all the unspent transaction separated
in two groups of redeem address and tree address respectively and both groups should
individually be sorted by descending order of their value.
**Usage**:
```
// Retrieve a list of unspent transactions from an external source (e.g. WalletClient)
let mut unspent_transactions = UnspentTransactions::default();
// A list of operations to apply: only transactions with redeem addresses and in
// …
```
> Problem: (CRO-128) Using decorators for unspent transaction configuration is unintuitive

- client-cli/src/command.rs
- client-cli/src/command/transaction_command.rs
- client-core/src/input_selection.rs
- client-core/src/lib.rs
- client-core/src/service/root_hash_service.rs
- client-core/src/service/wallet_service.rs
- client-core/src/signer.rs
- client-core/src/signer/default_signer.rs
- client-core/src/signer/unauthorized_signer.rs
- client-core/src/transaction_builder.rs
- client-core/src/transaction_builder/default_transaction_builder.rs
- client-core/src/transaction_builder/unauthorized_transaction_builder.rs
- client-core/src/unspent_transactions.rs
- client-core/src/wallet.rs
- client-core/src/wallet/default_wallet_client.rs
- client-rpc/src/server.rs
- client-rpc/src/wallet_rpc.rs
**Solution**: 
- Added support for 1-of-n schnorr signatures in transaction builder.
- Divided transaction builder into three components:
- `Signer`: For transaction signing
- `UnspentTransactions`: For UTXO selection
- `TransactionBuilder`: For building transaction
- There is also a slight change in algorithm used for creating transactions:
- We now no longer have a `DummySigner` which signs a transaction with dummy values for calculating fees. (I'll have to give more thought on implementing a `DummySigner` because 1-of-n signatures consist of a schnorr signature and a merkle proof which can be of variable size. So, we cannot deterministically estimate the size and structure of a 1-of-n signature)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Problem: (CRO-128) 1-of-n schnorr signatures are not supported by transaction builder

- chain-core/src/init/config.rs
- chain-core/src/state/mod.rs
Solution:
* removed secp256k1 (as it's currently unsupported https://tendermint.com/docs/spec/abci/apps.html#validator-updates )
* changed string type to "ed25519"
> Problem: wrong key type in validator update (CRO-171)

- chain-abci/src/app/query.rs
- chain-abci/tests/abci_app.rs
Solution: added a new path in the query handler + not failing peer whitelist querying
@devashishdxt this should help with the client -- I haven't tested it yet; I'll do it now and write a small unit test as well
> Problem: no way to query account state (CRO-173)

- Cargo.lock
- Cargo.toml
- client-core/src/key/private_key.rs
- client-core/src/service/wallet_service.rs
- client-core/src/signer/default_signer.rs
- client-core/src/wallet.rs
- client-core/src/wallet/default_wallet_client.rs
- client-network/Cargo.toml
- client-network/src/lib.rs
- client-network/src/network_ops.rs
- client-network/src/network_ops/default_network_ops_client.rs
**Solution**: 
- Created `NetworkOpsClient` with a default implementation to create and sign transaction to withdraw unbonded amount.
- In future, all the functions related to network operations on Chain will be added to `NetworkOpsClient`.
NOTE: Currently, I've hard-coded value of nonce to be zero. This will change in future once we have a way to query nonce value from Chain.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crypto-com/chain/142)
> Problem: (CRO-132) No way to create transactions to withdraw unbonded amount from account

- Cargo.lock
- chain-abci/Cargo.toml
- chain-core/Cargo.toml
- chain-core/src/state/account.rs
- chain-core/src/tx/witness/mod.rs
- client-core/Cargo.toml
- client-core/src/key/private_key.rs
- client-core/src/key/public_key.rs
Solution: upgraded secp256k1 fork
-- it merged changes from upstream rust-secp256k1: recovery module is now feature guarded
we may consider removing it and switching to plain ecdsa
> Problem: latest zeroize crate compilation fails (#127)

- chain-abci/src/app/commit.rs
- chain-abci/src/app/validate_tx.rs
- chain-abci/src/storage/tx.rs
- chain-abci/tests/abci_app.rs
- chain-tx-validation/Cargo.toml
- chain-tx-validation/src/lib.rs
Solution: moved the remaining tx validation code from chain-abci to the dedicated crate and fixed tests.
note that the dedicated crate tries to be as self-contained as possible, so it doesn't do I/O and all inputs are explicitly provided to it -- for account/stakedstate-based operations, it assumes witness / signature was checked during the account lookup; for utxo-based operations, it assumes inputs were checked not to be spent in abci app
> Problem: non-consolidated transaction validation code (CRO-175)

- Cargo.lock
- chain-abci/Cargo.toml
- chain-core/Cargo.toml
- chain-core/src/common/merkle_tree.rs
- chain-core/src/init/address.rs
- chain-core/src/init/coin.rs
- chain-core/src/init/config.rs
- chain-core/src/lib.rs
- chain-core/src/state/account.rs
- chain-core/src/state/mod.rs
- chain-core/src/state/tendermint.rs
- chain-core/src/tx/data/access.rs
- chain-core/src/tx/data/address.rs
- chain-core/src/tx/data/attribute.rs
- chain-core/src/tx/data/input.rs
- chain-core/src/tx/data/mod.rs
- chain-core/src/tx/data/output.rs
- chain-core/src/tx/fee/mod.rs
- chain-core/src/tx/witness/mod.rs
- chain-core/src/tx/witness/tree.rs
- chain-tx-validation/Cargo.toml
- client-core/Cargo.toml
- client-index/Cargo.toml
Solution: upgraded secp256k1 fork + feature-guarded a lot of it
NOTE: proper sgx-friendly version would also require a few changes in chain-core's Cargo.toml + would only work on nightly OR would need Xargo;
for that reason it's not done here -- the TX enclave repo will have a subtree of chain's repository with the SGX breaking changes
> Problem: chain-core is not sgx-friendly (CRO-188 / CRO-182)

- Cargo.lock
- chain-abci/Cargo.toml
- chain-core/Cargo.toml
- chain-tx-validation/Cargo.toml
- client-common/Cargo.toml
- client-common/src/storage.rs
- client-core/Cargo.toml
- client-core/src/key/private_key.rs
- client-core/src/service/multi_sig_session_service.rs
- client-index/Cargo.toml
Solution: There are two parts to the solution
- Update `rand` in `secp` crate (already done in https://github.com/crypto-com/rust-secp256k1-zkp/pull/5)
- Update `rand` in `chain` crate
This pull request is for the second part of the solution.
> Problem: (CRO-196) Latest rand doesn't compile with client

- Cargo.lock
- chain-core/Cargo.toml
- chain-core/src/init/address.rs
- chain-tx-validation/src/lib.rs
Solution: extra attribute configs + converted the address in chain core to use tiny-keccak rather than sha3 crate (as the former compiles out-of-the-box in sgx env)
> Problem: tx-validation doesn't compile in enclaves (CRO-189 / CRO-182)

- Cargo.lock
- chain-abci/Cargo.toml
- chain-abci/src/app/mod.rs
- chain-abci/tests/abci_app.rs
- chain-core/src/common/mod.rs
Solution: Changed abci version to 0.6 and made all necessary changes.
- tendermint 0.32 also involves changes in the response structure of `/block_results` RPC call which will be fixed as a part of separate PR.
> Problem: (CRO-197) Latest ABCI (for tendermint 0.32) doesn't compile

- Cargo.lock
- chain-abci/Cargo.toml
- chain-abci/tests/abci_app.rs
Solution: updated abci app test to use a fixed sized array that works with the new ethbloom API
> Problem: latest ethbloom doesn't compile (CRO-191)

- README.md
Solution: Updated README to first install zmq and pkg-config
> Problem: (CRO-209) README build instructions fail with libzmq

- client-common/src/tendermint/types/block_results.rs
- client-index/src/index/default_index.rs
Solution: Changed block_results RPC call to match new structure in Tendermint 0.32
> Problem: (CRO-199) BlockResults RPC call in client is not compatible with Tendermint 0.32

- chain-abci/src/app/commit.rs
- chain-abci/src/app/mod.rs
- chain-abci/src/app/query.rs
- chain-abci/src/enclave_bridge/mock.rs
- chain-abci/src/storage/tx.rs
- chain-abci/tests/abci_app.rs
- chain-core/src/tx/data/input.rs
- chain-core/src/tx/fee/mod.rs
- chain-core/src/tx/mod.rs
- client-common/src/tendermint/types/block.rs
- client-core/src/transaction_builder/default_transaction_builder.rs
- client-index/src/index/default_index.rs
- enclave-protocol/Cargo.toml
- enclave-protocol/src/lib.rs
Solution: added "plain" TX data type and moved transfer TX there
* changed downstream with stubs and temporary mocks
* added mock querying data types
--
some more context:
* this breaks the client functionality, as the client won't be able to decode Tx data straight out of Tendermint blocks (it's still possible to decode in the current implementation, as the txpayload isn't obfuscated, but soon-ish, it won't be) => I guess I'll tag master before merging this PR
* as the enclave part will require a lot of additional work to facilitate encrypting/decrypting, I've added temporary TM query paths that would help with developing the client workflow (client adds view keys in TX, syncs up block header filters, uses filters to collect TXIDs...) before it's usable
> Problem: no private TX support (CRO-181)

- chain-core/src/tx/mod.rs
Solution: added an explicit Vec import in tx module
> Problem: latest chain-core doesn't compile in tx-enclave

- chain-abci/src/app/commit.rs
- chain-abci/src/app/mod.rs
- chain-abci/src/app/query.rs
- chain-abci/src/enclave_bridge/mock.rs
- chain-abci/src/storage/tx.rs
- chain-abci/tests/abci_app.rs
- chain-core/src/lib.rs
- chain-core/src/tx/fee/mod.rs
- chain-core/src/tx/mod.rs
- chain-tx-validation/src/lib.rs
- client-common/src/tendermint/types/block.rs
- client-core/src/transaction_builder/default_transaction_builder.rs
- client-index/src/index/default_index.rs
- client-network/src/network_ops/default_network_ops_client.rs
- enclave-protocol/src/lib.rs
Solution: changed the chain-core data types to split the private and public parts; updated the enclave protocol
--
note -- this is WIP, will also need to update https://github.com/crypto-com/chain-tx-enclave to support this after this PR is merged
>  Problem: deposit bonded and withdraw unbounded aren't done in enclaves (CRO-208)

- Cargo.lock
- chain-core/Cargo.toml
- chain-core/src/init/address.rs
- chain-core/src/tx/data/address.rs
Solution: upgraded to the latest bech32, made bech32 dependency optional (textual repr. not needed in enclave tx validation), feature-guarded its usage
--
Note that it'd also be possible to fork bech32 crate to make it sgx-friendly (mainly a few std-related tweaks), but I guess that's more hassle
>  Problem: latest chain core doesn't compile on tx-enclave (CRO-230) (CRO-208)

- chain-tx-validation/src/lib.rs
Solution: split out the core validation functionality from the account update
-- 
Note: tx-validation / ABCI would require a lot more refactoring, so this is a small change for making a bit more usable
> Problem: validation of bonded deposits and unbonded withdrawals is cumbersome to call from within enclaves

- Cargo.lock
- client-cli/src/command.rs
- client-common/Cargo.toml
- client-common/src/balance/transaction_change.rs
- client-common/src/storage/sled_storage.rs
- client-common/src/tendermint/types/block_results.rs
- client-common/src/tendermint/types/query.rs
- client-core/src/wallet/default_wallet_client.rs
- client-index/src/index/default_index.rs
- client-rpc/src/client_rpc.rs
Solution: Changed block results RPC call to parse `end_block` section of response.
- Also includes a small change of wrapping `sled::Db` in `Arc` in `client_common::SledStorage`.
> Problem: (CRO-215) BlockResults RPC call does not parse block filter.

- client-common/src/block_header.rs
- client-common/src/lib.rs
- client-common/src/tendermint/client.rs
- client-common/src/tendermint/rpc_client.rs
- client-index/src/index/default_index.rs
- client-network/src/network_ops/default_network_ops_client.rs
- client-rpc/src/client_rpc.rs
Solution: Added `BlockHeader` data type in `client-common`
- Also, changed tendermint RPC query data from `&str` to `&[u8]`
> Problem: (CRO-215) No data structure to hold details of a block header

- Cargo.lock
- client-index/Cargo.toml
- client-index/src/cipher.rs
- client-index/src/cipher/abci_transaction_cipher.rs
- client-index/src/lib.rs
- client-rpc/src/client_rpc.rs
**Solution**: Implemented `TransactionCipher` which can be used to decrypt a set if transaction_ids using current mock implementation in `chain-abci`
**Note**: `encrypt()` will be implemented in future PRs.
> Problem: (CRO-215) No way to decrypt an encrypted transaction

- Cargo.lock
- client-cli/src/command.rs
- client-core/src/wallet.rs
- client-core/src/wallet/default_wallet_client.rs
- client-index/Cargo.toml
- client-index/src/handler.rs
- client-index/src/handler/default_block_handler.rs
- client-index/src/index.rs
- client-index/src/index/default_index.rs
- client-index/src/index/unauthorized_index.rs
- client-index/src/lib.rs
- client-index/src/service/global_state_service.rs
- client-rpc/src/client_rpc.rs
**Solution**: This is second of a series of PRs which will slowly extract out all the transaction synchronization code from transaction index.
**Note**: Current implementation of `BlockHandler` only handles transaction which are encrypted (`Transfer` and `Withdraw`). Implementation for `DepositStake` transactions will be a part of future PRs.
> Problem: (CRO-215) Transaction synchronization code is tightly coupled with transaction index

- client-common/src/lib.rs
- client-common/src/transaction.rs
- client-index/src/cipher.rs
- client-index/src/cipher/abci_transaction_cipher.rs
- client-index/src/handler/default_block_handler.rs
Solution: Added `encrypt()` to interface and also a default implementation using mockencrypt in ABCI
> Problem: (CRO-215) TransactionCipher does not support transaction encryption

- client-rpc/src/client_rpc.rs
Solution:
- Modified `client-rpc` code to correctly create network transactions and broadcast them
- Also, modified transfer transaction to use user provided `view_keys`
> Problem: (CRO-260) Network operations in RPC does not broadcast to Chain

- chain-abci/src/app/app_init.rs
- chain-abci/src/app/validate_tx.rs
- chain-abci/src/enclave_bridge/mock.rs
- chain-abci/src/enclave_bridge/mod.rs
- chain-abci/src/storage/tx.rs
- chain-core/src/tx/mod.rs
- enclave-protocol/src/lib.rs
Solution: as the enclave seals and stores data locally, it just needs the tx pointers / txids which are included in the TxAux.
* changed the mock to store it locally in a hashmap
Note: enclave code doesn't do unsealing yet -- WIP
>  Problem: redundant sending of TX data to enclave (CRO-229)

- client-cli/src/command/address_command.rs
- client-cli/src/command/transaction_command.rs
- client-core/src/signer/default_signer.rs
- client-core/src/transaction_builder/default_transaction_builder.rs
- client-core/src/wallet.rs
- client-core/src/wallet/default_wallet_client.rs
- client-rpc/src/client_rpc.rs
Solution: Standardized RPC method name
- RPCs are catogerized into `sync_*`, `wallet_*`, `stagking_*` and `multiSig_*`
- use camelcase to name RPC calls
- Renamed create single transfer address to `new_transfer_address`, create multisig address to `new_multisig_transfer_address` because I think this is more mentally straightforward.
> Problem: ClientRPC method name are not standardized

- chain-core/src/lib.rs
- chain-core/src/state/account.rs
- chain-core/src/tx/data/access.rs
- chain-core/src/tx/data/attribute.rs
- chain-core/src/tx/fee/mod.rs
- chain-core/src/tx/witness/mod.rs
- chain-core/src/tx/witness/tree.rs
- enclave-protocol/src/lib.rs
Solution: Removed manual implementation and auto derived `Encode` and `Decode`
> Problem: (CRO-276) Unnecessary Encode and Decode impls of types supported by parity_scale_codec

- client-cli/src/main.rs
Solution: Added exit code 1 in error scenarios
> Problem: (CRO-256) Client CLI does not exit with code > 0 when error occurs

- enclave-protocol/src/lib.rs
Solution: Added maximum size of binary encoded data for an encryption request. Currently, the default value is 1 MB (same as tendermint's default for a transaction) which can be changed once we have a better understanding of different usecases we want to support and the size required for those.
> Problem: (CRO-247) Mock transaction encryption endpoint is vulnerable to DoS attack

- chain-core/src/tx/mod.rs
Solution: Added maximum size of binary encoded data for a transaction. Currently, the default value is 1 MB (same as tendermint's default for a transaction) which can be changed once we have a better understanding of different usecases we want to support and the size required for those.
**Note**: This change is temporary and should be reverted once tendermint officially starts supporting `max_tx_bytes` in `cargo.toml`.
> Problem: (CRO-247) Broadcast transaction endpoint is vulnerable to DoS attack

- chain-core/src/state/account.rs
- chain-core/src/tx/data/access.rs
- chain-core/src/tx/witness/mod.rs
- client-common/src/balance/transaction_change.rs
- client-common/src/key/private_key.rs
- client-common/src/key/public_key.rs
Solution: Added `size_hint` implementation in all manual implementations of `Encode`
> Problem: Encoded types not using size_hint

- Cargo.lock
- NOTICE
- chain-abci/Cargo.toml
- chain-abci/src/app/query.rs
- chain-core/Cargo.toml
- chain-tx-filter/Cargo.toml
- chain-tx-validation/Cargo.toml
- client-cli/src/command.rs
- client-common/Cargo.toml
- client-common/src/error.rs
- client-core/Cargo.toml
- client-core/src/transaction_builder/default_transaction_builder.rs
- client-core/src/wallet/default_wallet_client.rs
- client-index/Cargo.toml
- client-index/src/cipher.rs
- client-index/src/cipher/abci_transaction_cipher.rs
- client-index/src/cipher/cert.rs
- client-index/src/cipher/default.rs
- client-index/src/cipher/sgx.rs
- client-index/src/handler/default_block_handler.rs
- client-index/src/lib.rs
- client-network/Cargo.toml
- client-network/src/network_ops/default_network_ops_client.rs
- client-rpc/src/rpc/wallet_rpc.rs
- client-rpc/src/server.rs
- enclave-protocol/Cargo.toml
- enclave-protocol/src/lib.rs
Solution:
- extended the enclave protocol for direction communication
- refactored abci and client libs to make it explicit they've been using a mock (+ warning in abci)
- ported some of the MesaTEE client facility (using the failure crate instead of custom monadic macro)
- "switch" to the direct communication with TDQE (refusing abci queries etc.) is currently feature-guarded, as TDQE "server" is still WIP
> Problem: tx decryption done using a mock abci query (CRO-274)

- client-index/src/cipher.rs
- client-index/src/cipher/default.rs
Solution: re-exported the struct in the parent module
> Problem: TDQE client not exposed (CRO-274)

- integration-tests/client-rpc/test/wallet-transaction.test.ts
Solution: Updated test suite to adapt with new response
```javascript
1) Wallet transaction
can transfer funds between two wallets:
AssertionError: expected 'Outgoing' to equal 'outgoing'
+ expected - actual
-Outgoing
+outgoing
at expectTransactionShouldBe (test/wallet-transaction.test.ts:324:25)
at Context.it (test/wallet-transaction.test.ts:102:3)
at process._tickCallback (internal/process/next_tick.js:68:7)
2) Wallet transaction
can transfer funds between two wallets with fee included:
AssertionError: expected 'Outgoing' to equal 'outgoing'
+ expected - actual
-Outgoing
+outgoing
at expectTransactionShouldBe (test/wallet-transaction.test.ts:324:25)
at Context.<anonymous> (test/wallet-transaction.test.ts:223:3)
at process._tickCallback (internal/process/next_tick.js:68:7)
> Problem: Integration tests fails because of changes in RPC response

- chain-abci/src/enclave_bridge/mock.rs
- enclave-protocol/src/lib.rs
Solution: TVE handles storage access, TDQE communicates to it via zMQ (TODO) => extended the zMQ protocol to include TDQE-TVE requests-replies
> Problem: TDQE and TVE cannot simultaneously access enclave storage (CRO-337)

- Cargo.lock
- chain-abci/Cargo.toml
- chain-core/Cargo.toml
- chain-tx-filter/Cargo.toml
- chain-tx-validation/Cargo.toml
- client-common/Cargo.toml
- client-core/Cargo.toml
- client-index/Cargo.toml
- client-network/Cargo.toml
- enclave-protocol/Cargo.toml
Solution: Changed zeroize version to 0.10 and also updated secp256k1 dependency to latest
> Problem: (CRO-338) Zeroize 0.10 fails to compile

- client-common/src/tendermint/client.rs
- client-common/src/tendermint/rpc_client.rs
- client-index/src/cipher/abci_transaction_cipher.rs
- client-index/src/handler/default_transaction_handler.rs
- client-index/src/index/default_index.rs
- client-index/src/synchronizer.rs
- client-network/src/network_ops/default_network_ops_client.rs
- client-rpc/src/rpc/multisig_rpc.rs
- client-rpc/src/rpc/transaction_rpc.rs
- client-rpc/src/rpc/wallet_rpc.rs
**Solution**: Created batched RPC request functions for `block` and `block_results`. 
**Note**: Right now, we only need `block` and `block_results` RPC calls in batch mode. Other methods can be added later as needed.
> Problem: (CRO-252) Tendermint client does not support batched RPC requests

- client-common/src/tendermint/rpc_client.rs
Solution: Added a check before making tendermint RPC calls
> Problem: (CRO-252) Tendermint client can create empty batch requests

- client-common/src/tendermint/rpc_client.rs
Solution: Added a check to send non-batch request when `params.len() == 1`
Note: This change is necessary because Tendermint's batch RPC API returns an object instead of an array of objects when there is only one set of params in request which makes serde deserializer to fail because it expects an array in case of batch requests.
> Problem: (CRO-252) Client sends batch request for one parameter set

- client-core/src/service/multi_sig_session_service.rs
Solution: Fixed the same problem for nonce commitment and partial signatures also. Added unit test cases to check this.
> Problem: (CRO-351) MultiSigWallet fails to retrieve nonce value for a session more than once

- .travis.yml
- integration-tests/README.md
- integration-tests/client-rpc/package.json
- integration-tests/client-rpc/test/core/setup.ts
- integration-tests/client-rpc/test/wallet-management.test.ts
- integration-tests/client-rpc/test/wallet-transaction.test.ts
- integration-tests/client-rpc/tsconfig.json
- integration-tests/client-rpc/yarn.lock
- integration-tests/constant-env.sh
- integration-tests/prepare.sh
- integration-tests/start-local.sh
The integration tests use docker to build and run the test environment. When you are under active development, you have to rebuild from scratch again on every code changes because the docker always rebuild from scratch
Refactor integration tests to allow starting the test environment using local build (from `cargo build`)
```bash
$ ./integration-tests/prepare.sh
$ ./integration-tests/start-local.sh <chain-tx-enclave|chain-tx-enclave-zerofee>
$ ./integration-tests/start-local.sh <tendermint|tendermint-zerofee>
$ ./integration-tests/start-local.sh <chain-abci|chain-abci-zerofee>
$ ./integration-tests/start-local.sh <client-rpc|client-rpc-zerofee>
```
```bash
$ cd integration-tests/client-cli
$ TEST_ONY=<WITH_FEE|ZERO_FEE> yarn test
```
For details, please refer to README in integration …
> Problem: (CRO-344) Integration test is not friendly to development

- client-cli/src/command.rs
- client-index/src/synchronizer.rs
- client-rpc/src/rpc/sync_rpc.rs
Solution: Added a cli option to configure batch size. Default is 20.
> Problem: (CRO-359) Batch size for tendermint RPC calls is not configurable

- chain-tx-filter/src/lib.rs
- client-common/src/block_header.rs
- client-common/src/tendermint/types/block.rs
- client-common/src/tendermint/types/status.rs
- client-index/src/handler/default_block_handler.rs
- client-index/src/service/global_state_service.rs
- client-index/src/synchronizer.rs
- client-rpc/src/rpc/wallet_rpc.rs
**Solution**:
1. Client will now fast forward if current app hash matches last app hash stored in client.
2. Client will fast forward each batch of requests (default is 20) if the batch does not change app hash (it will still make `block` RPC call).
**Note**: Because this PR changes internal storage structure of `last_block_height` and `last_app_hash`, every client will have to do a `sync --force`.
> Problem: (CRO-359) Client does not fast forward when app hash is same

- .travis.yml
Solution: audit didn't have a version arg/command (for testing the executable presence) => switched to the help arg/command
> Problem: failing CI on stable (on audit command)

- client-common/src/error.rs
- client-index/src/handler/default_transaction_handler.rs
- client-index/src/index/default_index.rs
- client-index/src/service/transaction_service.rs
Solution: Ignore a transaction input when its details are not available (this means that current wallet's view key was not present in that transaction).
> Problem: Client synchronization fails when storage does not contain input transaction details

- Cargo.lock
- chain-abci/src/enclave_bridge/mock.rs
- chain-abci/src/storage/tx.rs
- chain-tx-validation/Cargo.toml
- chain-tx-validation/src/lib.rs
- enclave-protocol/src/lib.rs
Solution:
(WIP -- tx validation enclave needs patching)
- tx validation error cannot be easily passed as C FFI error code => temporarily removed the nested variants
- tx validation error not returned by the enclave protocol => added encode-decode derivation to the tx validation error data type
and extended the enclave protocol
> Problem: no error code returned from tx validation enclave (CRO-373)

- client-index/src/synchronizer.rs
Solution: Changed client code to only fetch block header of last block to check if the batch can be fast-forwarded. This will make fast forwarding much faster.
> Problem: (CRO-387) Client fetches block headers for whole batch before fast forwarding

- Cargo.lock
- chain-abci/Cargo.toml
Solution: investigated the crates that bring duplicate dependencies -- most of them would require more complex changes / rewriting in the code or fixing external code -- I opened separate issues for them.
One quick fix here was to comment out the microbenchmark dependency (as that's not being tested/maintained at the moment), because that brought the old version of rayon and transitive dependencies
> Problem: duplicate/similar crate dependencies (CRO-270)

- Cargo.lock
- chain-abci/src/app/mod.rs
- chain-abci/tests/abci_app.rs
- client-common/src/tendermint/types/block_results.rs
- client-index/Cargo.toml
- client-index/src/synchronizer.rs
Solution: Store transaction id as UTF-8 string in `txid` attribute
Remarks:
to search for a particular tx id, use
```bash
curl -X GET \
'http://localhost:16657/tx_search?query=%22valid_txs.txid=%270766d4e1c09124af9aeb4a7ed99d81654a84473f133948cea050daa17ff0e7ff%27%22&prove=true' \
-H 'Content-Type: application/json' \
-H 'Host: localhost:26657'
```
> Problem: (CRO-341) No way to search for transaction id

- chain-core/Cargo.toml
- chain-core/src/init/address.rs
- chain-core/src/init/mod.rs
- chain-core/src/state/account.rs
- chain-core/src/state/mod.rs
- chain-core/src/tx/data/address.rs
- chain-core/src/tx/data/attribute.rs
- chain-core/src/tx/data/input.rs
- chain-core/src/tx/data/mod.rs
- chain-core/src/tx/data/output.rs
- chain-core/src/tx/mod.rs
Solution: WIP as hex + base64 weren't upgraded yet; they are not actually used in the enclave code => their usage was feature guarded, so they could be removed in the enclave code
> Problem: tx-enclaves fail to compile in v1.0.9 sgx sdk

- CHANGELOG.md
- Cargo.lock
- chain-abci/Cargo.toml
- chain-core/Cargo.toml
- chain-tx-filter/Cargo.toml
- chain-tx-validation/Cargo.toml
- client-cli/Cargo.toml
- client-common/Cargo.toml
- client-core/Cargo.toml
- client-index/Cargo.toml
- client-network/Cargo.toml
- client-rpc/Cargo.toml
- dev-utils/Cargo.toml
- enclave-protocol/Cargo.toml
Solution: created a compatible release with minor improvements
--
Note that commits will be cherry-picked on the release/v0.0 branch and then 0.0.2 will be tagged
> Problem: outdated dependecies in the first release

- client-index/src/auto_synchronizer.rs
Solution:
in process_text of auto_synchronizer,
it should return Ok, Err instead of directly close_connection.
because close_connection is called in caller "process_text".
> Problem:(CRO-424) Auto-sync doesn't work correctly after adding wallet

- CHANGELOG.md
- Cargo.lock
- chain-abci/Cargo.toml
- chain-core/Cargo.toml
- chain-tx-filter/Cargo.toml
- chain-tx-validation/Cargo.toml
- client-cli/Cargo.toml
- client-common/Cargo.toml
- client-core/Cargo.toml
- client-index/Cargo.toml
- client-network/Cargo.toml
- client-rpc/Cargo.toml
- dev-utils/Cargo.toml
- enclave-protocol/Cargo.toml
Solution: a hotfix in 0.0.3
--
Note that commits will be cherry-picked on the release/v0.0 branch and then 0.0.3 will be tagged
> Problem: auto-sync broken in 0.0.2

- integration-tests/start-local.sh
Solution: Added WS URL option to `start-local.sh`
> Problem: (CRO-431) Missing WebSocket URL in Integration Tests local mode

- chain-abci/src/enclave_bridge/mock.rs
- chain-abci/src/storage/tx.rs
- enclave-protocol/src/lib.rs
Solution: refined datatypes in enclave protocol, so that
they could be one entry point and one output point (either via two
memory buffers or a single ipc socket)
--
Note: WIP tx-validation enclave needs to be patched / this will break current enclave protocol integration
> Problem: complex transaction validation EDL (CRO-386)

- client-common/Cargo.toml
- client-core/Cargo.toml
- client-network/Cargo.toml
Solution: added the required dependency feature
similar problem to #390 -- discovered with tx-query test, as it imports client-core (previously client-index) and client-common as libraries
> Problem: client libraries cannot be compiled on their own

- Cargo.lock
- chain-core/Cargo.toml
- chain-tx-validation/Cargo.toml
- enclave-protocol/Cargo.toml
Solution: tweaked Cargo.toml's feature set up, such that the exact same code (including Cargo.toml) can be compiled both in the enclave and in the normal environment. (hopefully we can get rid of the subtree after this)
> Problem: chain-tx-enclave repo needs a subtree for small modification of cargo manifests

- client-core/src/synchronizer/auto_sync.rs
- client-core/src/synchronizer/auto_sync_data.rs
- client-core/src/synchronizer/auto_synchronizer.rs
Solutoin:
update send queue after closing the session, which is the channel between core and network.
this is Arc::Mutex related bug, because it's shallow cloning,
we need to use &mut to change it
without that, mutex value is Option, it is just replaced on the stack
and destroyed after it's out of scope.
> Problem: (CRO-444) auto sync doesn't work correctly after receceiving incorrect messages

- chain-tx-filter/src/filter.rs
- chain-tx-filter/src/lib.rs
- enclave-protocol/src/lib.rs
Solution: (WIP) enhanced the enclave protocol to exchanges of tx filters + small changes in the tx filter
NOTE: the logic is not yet implemented in ABCI:
it'll first be implemented in the tx validation enclave and then abci
> Problem: tx-filter not computed in the tx validation enclave (CRO-364)

- chain-tx-filter/src/filter.rs
- chain-tx-filter/src/lib.rs
- enclave-protocol/src/lib.rs
Solution: added explicit Vec imports + extended the intra-request reply to accommodate for endblock handling
> Problem: tx-filter cannot be compiled for the enclave (CRO-364)

- Cargo.lock
- client-cli/src/command.rs
- client-cli/src/main.rs
- client-common/Cargo.toml
- client-common/src/tendermint.rs
- client-common/src/tendermint/http_rpc_client.rs
- client-common/src/tendermint/websocket_rpc_client.rs
- client-common/src/tendermint/websocket_rpc_client/types.rs
- client-common/src/tendermint/websocket_rpc_client/websocket_rpc_loop.rs
- client-core/Cargo.toml
- client-rpc/src/program.rs
- client-rpc/src/server.rs
- integration-tests/docker-compose.yml
- integration-tests/start-local.sh
Solution: Use websocket for JSON-RPC everywhere
Note: Currently, `AutoSynchronizer` creates its own websocket connection with tendermint. So, there'll be two separate websocket connections with tendermint.
> Problem: (CRO-391) Two transport layers for tendermint JSON-RPC client

- .travis.yml
- integration-tests/client-rpc/test/network-ops.test.ts
- integration-tests/client-rpc/test/wallet-transaction.test.ts
- integration-tests/constant-env.sh
- integration-tests/docker/chain/Dockerfile
- integration-tests/prepare.sh
- integration-tests/start-local.sh
Solution:
- Lengthened the setup time for docker
- Allow more time for transaction to broadcast and be included in a block
- Use debug build to speed up build process
- Integration tests local mode - Build chain-tx-enclave at prepare phase, instead of start-up phase
- Added ClientCLI in integration tests local mode
> Problem: (CRO-448) Integration tests suite in CI is unstable

- .travis.yml
Solution: ignore docker compose log's return code
> Problem: integration test CI fails with "logs"

- chain-abci/src/storage/account/mod.rs
Solution: added a basic quickcheck property to check trie root after insertions in different order
> Problem: no test of prefix merkle trie determinism

- chain-abci/src/app/app_init.rs
- chain-abci/tests/abci_app.rs
- chain-core/src/init/config.rs
Solution: Added `jailing_config` in `ChainNodeState`
> Problem: (CRO-461) ABCI app does not store jailing configuration

- client-rpc/src/rpc/staking_rpc.rs
- integration-tests/client-rpc/test/core/rpc.ts
- integration-tests/client-rpc/test/core/setup.ts
- integration-tests/client-rpc/test/core/tendermint-client.ts
- integration-tests/client-rpc/test/core/transaction-utils.ts
- integration-tests/client-rpc/test/core/utils.ts
- integration-tests/client-rpc/test/network-ops.test.ts
- integration-tests/client-rpc/test/wallet-auto-sync.test.ts
- integration-tests/client-rpc/test/wallet-management.test.ts
- integration-tests/client-rpc/test/wallet-transaction.test.ts
- integration-tests/prepare.sh
Solution: Used more reliable mechanism to check for state changes and improved error message
- Transaction: Pull Tendermint for the new transaction
- Changed staking RPCs to return txid
- Staking state: Pull staking state until expected result
- Added contextual error message to all RPC calls by introducing `asyncMiddleman()`
- Refactored Staking test cases and added unbond txid duplication check
> Problem: (CRO-463) Integration tests relies on unreliable timeout for state changes

- chain-core/src/tx/mod.rs
- chain-tx-enclave/enclave-macro/Cargo.toml
- chain-tx-enclave/enclave-macro/src/lib.rs
- chain-tx-enclave/tx-validation/enclave/Cargo.toml
- chain-tx-enclave/tx-validation/enclave/src/lib.rs
- chain-tx-enclave/tx-validation/enclave/src/obfuscate.rs
- chain-tx-enclave/tx-validation/enclave/src/validate.rs
- client-common/src/tendermint/types/block.rs
- enclave-protocol/src/lib.rs
Solution: (WIP) added a mock compile-time key generation + encryption/decryption using AES-GCM-SIV crate (should be fast + safe for multiple encryptors with random nonce generation which is our case)
- added a new request type in protocol (will be generated / passed from tx-query -- TODO)
- split tx-validation enclave's functionality into modules
TODO: extend tx-validation enclave tests
> Problem: no in-enclave decryption/encryption functionality (CRO-451)

- chain-abci/src/app/commit.rs
- chain-abci/src/app/mod.rs
- chain-abci/src/storage/tx.rs
- chain-core/src/state/account.rs
- chain-core/src/tx/mod.rs
- chain-tx-validation/src/lib.rs
Solution: Created an `UnjailTx` which unjails a jailed account
Note: Currently, there is no logic to add unjailed accounts back to validator set. That'll be a part of future PRs.
> Problem: (CRO-454) Cannot unjail a jailed account

- Cargo.lock
- chain-core/Cargo.toml
- chain-core/src/tx/mod.rs
- chain-tx-enclave/tx-validation/Makefile
- chain-tx-enclave/tx-validation/app/src/test/mod.rs
- chain-tx-enclave/tx-validation/enclave/Cargo.toml
- chain-tx-enclave/tx-validation/enclave/Enclave.edl
- chain-tx-enclave/tx-validation/enclave/src/obfuscate.rs
- chain-tx-enclave/tx-validation/enclave/src/validate.rs
- chain-tx-filter/src/lib.rs
- enclave-protocol/src/lib.rs
- integration-tests/docker/chain/Dockerfile
Solution:
- renamed the overshadowing tx
- extended the tx-validation test: enclave code has now sgx-test feature flag
which compiles extra ecall for simple (unchecked) encrypting with a mock key
(`make` with `SGX_TEST=1`)
> Problem: incorrect tx payload for in-enclave encryption (CRO-451)

- chain-tx-enclave/tx-query/app/src/test/mod.rs
- chain-tx-enclave/tx-validation/app/src/enclave_u/mod.rs
- chain-tx-enclave/tx-validation/app/src/server/mod.rs
- chain-tx-enclave/tx-validation/enclave/src/obfuscate.rs
- enclave-protocol/src/lib.rs
Solution: extended the enclave protocol by one more variant + handling (chain info is stored locally from the validated transactions)
TODO: changes to tx-query
> Problem: no way to send encryption request from tx-query enclave (CRO-478)

- chain-abci/src/app/mod.rs
- chain-abci/src/liveness.rs
Solution: Added a `warn!` statement if validator is not present in liveness tracker
Note: This PR is mostly addressing the review comments on earlier PR.
> Problem: (CRO-469) Updating validator liveness may panic if validator is not present in tracker

- chain-abci/src/app/jail_account.rs
- chain-abci/src/app/mod.rs
- chain-abci/src/liveness.rs
- chain-abci/tests/abci_app.rs
Solution: After updating liveness of a validator based on `last_commit_info`. Jail if validator is not live.
> Problem: (CRO-453) Non-live validators are not jailed

- Cargo.lock
- chain-abci/Cargo.toml
- chain-core/Cargo.toml
- chain-tx-enclave/enclave-t-common/Cargo.toml
- chain-tx-enclave/tx-query/app/Cargo.toml
- chain-tx-enclave/tx-query/enclave/Cargo.toml
- chain-tx-enclave/tx-validation/app/Cargo.toml
- chain-tx-enclave/tx-validation/enclave/Cargo.toml
- chain-tx-filter/Cargo.toml
- chain-tx-validation/Cargo.toml
- client-common/Cargo.toml
- client-core/Cargo.toml
- client-network/Cargo.toml
- enclave-protocol/Cargo.toml
Solution: Updated `zeroize` and `secp256k1` crate versions after updating `secp256k1` crate
> Problem: (CRO-489) client-common fails to compile with zeroize 1.0

- NOTICE
- client-core/Cargo.toml
- client-core/src/hdwallet/error.rs
- client-core/src/hdwallet/extended_key.rs
- client-core/src/hdwallet/extended_key/key_index.rs
- client-core/src/hdwallet/key_chain.rs
- client-core/src/hdwallet/key_chain/chain_path.rs
- client-core/src/hdwallet/mod.rs
- client-core/src/hdwallet/traits.rs
- client-core/src/lib.rs
- client-core/src/service/key_service.rs
Solution: remove dependency of tiny_hderive, replace with secp256k1 directly, which is already being used in core
add module
compile ok
hdwallet working
fix hdwallet
display info
tidy up
add zeroize
> Problem:(CRO-490) tiny_hderive uses the same secp256k1 library and it's outdated

- chain-abci/src/app/app_init.rs
Solution:
1. encode the raw hash data into string 
2. if the raw hash is None, use "None"
3. make the log into a single line
4. use "{}" instead of "{:?}" in string format
> Problem: (CRO-280) chain-abci init panics with raw genesis hash rather than hex-encoded

- chain-tx-enclave/enclave-u-common/src/enclave_u/mod.rs
- chain-tx-enclave/tx-query/app/src/main.rs
- chain-tx-enclave/tx-query/app/src/test/mod.rs
- chain-tx-enclave/tx-validation/app/src/enclave_u/mod.rs
- chain-tx-enclave/tx-validation/app/src/main.rs
- chain-tx-enclave/tx-validation/app/src/server/mod.rs
- chain-tx-enclave/tx-validation/app/src/test/mod.rs
- enclave-protocol/src/lib.rs
Solution: removed the enclave protocol parts related to them;
updated the enclave launcher to use dummy values in the meantime
--
NOTE: Rust SDK isn't updated yet, hence the need of dummy values for the moment
(launch_token and launch_token_updated are now deprecated according to https://download.01.org/intel-sgx/linux-2.6/docs/Intel_SGX_Developer_Reference_Linux_2.6_Open_Source.pdf. They are fully ignored by psw/sgx_urts.)
> Problem: deprecated enclave launch token functionality (CRO-499)

- chain-abci/src/app/app_init.rs
- chain-abci/src/app/mod.rs
- chain-abci/src/app/slash_accounts.rs
- chain-abci/src/lib.rs
- chain-abci/src/main.rs
- chain-abci/src/punishment.rs
- chain-abci/src/slashing.rs
- chain-abci/tests/abci_app.rs
- chain-core/src/init/coin.rs
- chain-core/src/init/config.rs
- chain-core/src/state/account.rs
Solution: Add byzantine validators to slashing queue and slash them when wait time passes
> Problem: (CRO-455) Byzantine validators are not slashed

- client-core/src/types/wallet_kind.rs
- client-rpc/src/rpc/wallet_rpc.rs
- integration-tests/client-rpc/test/network-ops.test.ts
- integration-tests/client-rpc/test/wallet-auto-sync.test.ts
- integration-tests/client-rpc/test/wallet-management.test.ts
- integration-tests/client-rpc/test/wallet-transaction.test.ts
Solution: add hdwallet api to client-rpc
> Problem:(CRO-479) no HD wallet support in client-rpc

- .drone.yml
Solution: added trigger conditions, such that
"exec" pipelines are only executed after bors actions
> Problem: unrestricted drone exec pipeline

- chain-core/Cargo.toml
Solution: added the `std` feature for secp256k1 default compilation
> Problem: chain-core cannot be compiled on its own

- chain-abci/src/app/mod.rs
- chain-abci/src/app/slash_accounts.rs
- chain-core/src/common/mod.rs
Solution: Create tendermint events for punishments
> Problem: (CRO-498) No events for punishments (jailing/slashing)

- client-common/src/transaction.rs
- client-core/src/cipher/default.rs
- client-core/src/cipher/mock_abci_transaction_obfuscation.rs
- client-network/src/network_ops.rs
- client-network/src/network_ops/default_network_ops_client.rs
- client-rpc/src/rpc/wallet_rpc.rs
add unjail-tx to default network client
fix un-covered match
fix un-covered match in wallet-rpc
fix argument
add unit test
rename
> Problem: (CRO-495) no way for client to unjail account

- Cargo.lock
- chain-abci/Cargo.toml
- chain-core/Cargo.toml
- chain-tx-enclave/enclave-t-common/Cargo.toml
- chain-tx-enclave/tx-query/app/Cargo.toml
- chain-tx-enclave/tx-query/enclave/Cargo.toml
- chain-tx-enclave/tx-validation/app/Cargo.toml
- chain-tx-enclave/tx-validation/enclave/Cargo.toml
- chain-tx-filter/Cargo.toml
- chain-tx-validation/Cargo.toml
- client-common/Cargo.toml
- client-core/Cargo.toml
- client-network/Cargo.toml
- enclave-protocol/Cargo.toml
Solution: migrated to the last ported version + re-generated Cargo.lock
> Problem: outdated secp256k1 fork dependency

- chain-abci/src/app/app_init.rs
- chain-abci/src/app/commit.rs
- chain-abci/src/app/mod.rs
- chain-abci/src/app/slash_accounts.rs
Solution: added a flag to chainabci node to signal whether rewards pool was updated
in that block (either by slashing events or transaction fees -- in the future reward distribution),
so that its "last_block_height" (which denotes when it was updated last time)
is only updated when the amount changed.
TODO: perhaps move the rewards pool update logic to rewards pool code (rather than in abci)?
> Problem: app hash changes even if app state didn't change (CRO-526)

- client-cli/src/command.rs
Solution: Added `Jailed Until` in cli display table of `staked-state`
> Problem: (CRO-530) Staked State does not show jailing information in client-cli

- .travis.yml
- install_kcov.sh
Solution: Add more aggressive caching of re-usable resources
---
Remarks:
- With more aggressive caching task time has reduced ~10mins, with the tradeoff of a much bigger cache size
- Hence a cron job is need to run on master maybe every week to keep the master branch cache to be slim
> Problem: (CRO-512) Cargo tools and build intermediates are not cached in Travis

- client-core/src/signer.rs
- client-core/src/signer/default_signer.rs
- client-core/src/signer/dummy_signer.rs
- client-core/src/signer/unauthorized_signer.rs
- client-core/src/transaction_builder/default_transaction_builder.rs
- client-network/src/network_ops/default_network_ops_client.rs
solution:
- create a Merkle tree (length is 2) for each selected unpent transactions to get the Merkle tree `Path`
- use Vec<u8> allocated with the same number of bytes as the `signature`
- use the above `Merkle tree path` + `signature` as the witness
- pad the payload to the multiples of 128 bits used in the  mock`TxEnclaveAux::TransferTx`
> Problem:(CRO 266) Not using dummy values for fee calculation

- chain-abci/src/app/app_init.rs
- chain-abci/src/app/jail_account.rs
- chain-abci/tests/abci_app.rs
- chain-core/src/init/config.rs
- chain-core/src/init/params.rs
- chain-core/src/state/account.rs
- chain-core/tests/verify_config.rs
- chain-tx-enclave/tx-query/app/src/test/mod.rs
- chain-tx-enclave/tx-validation/app/src/enclave_u/mod.rs
- chain-tx-enclave/tx-validation/app/src/test/mod.rs
- chain-tx-validation/src/lib.rs
- dev-utils/src/commands/genesis_command.rs
Solution: 
change the parameters of `new_init`: change `genesis_time` from `Timespec` into `Option<Timespec>`, remove the `bool` type parameter `bonded`, add a `&StakedStateDestination` type parameter.
> Problem:(CRO-521) unbonded from custom time is ignored in genesis initconfig

- .gitignore
> Problem: developers may accidentally commit ssh keys

- Cargo.lock
- chain-core/Cargo.toml
- chain-core/src/init/address.rs
Solution: Made necessary changes for `tiny-keccak = 2.0`
> Problem: (CRO-562) tiny-keccak 2.0 fails to compile

- Cargo.lock
- chain-abci/tests/abci_app.rs
- client-core/Cargo.toml
Solution: Removed default features and added features that are used in `client-core`
Note: This does not change `Cargo.lock` because other dependencies of `client-core` still depends on features that are removed in this PR.
> Problem: (CRO-568) client-core depends on unused tokio dependencies

- chain-abci/src/app/app_init.rs
Solution:
Skip serialization of invalid json field.
> Problem: chain-abci panic due to failed serialization (CRO-575)

- chain-tx-validation/src/lib.rs
- client-common/src/error.rs
- client-core/Cargo.toml
- client-core/src/transaction_builder/default_transaction_builder.rs
- client-network/src/network_ops/default_network_ops_client.rs
Solution: Added basic checks from `chain-tx-validation` in `client-core`
> Problem: (CRO-531) Client can generate invalid transactions

- .drone.yml
- .travis.yml
- Cargo.lock
- README.md
- ci-scripts/drone.nix
- client-common/Cargo.toml
- client-common/src/error.rs
- client-common/src/storage.rs
- client-core/src/service/hd_key_service.rs
- docker/Dockerfile
Solution: Use `aes-gcm-siv` for encryption/decryption
Note: Turns out that the root cause of timeouts was password hashing using `rust-argon2` which, as far as I know, is only useful when we want to store passwords in a database. Adding cache for wallet details is still a good idea and can be done in a different task.
> Problem: (CRO-392) Outdated dependencies in client's storage encryption

- chain-abci/src/app/app_init.rs
- chain-abci/src/app/mod.rs
- chain-abci/src/app/slash_accounts.rs
- chain-abci/src/app/validate_tx.rs
- chain-abci/src/enclave_bridge/mock.rs
- chain-core/src/common/mod.rs
- chain-tx-enclave/tx-validation/app/src/enclave_u/mod.rs
- chain-tx-enclave/tx-validation/app/src/test/mod.rs
- chain-tx-enclave/tx-validation/enclave/src/validate.rs
- chain-tx-filter/src/lib.rs
- client-common/src/tendermint/types/block_results.rs
- client-core/src/synchronizer/auto_sync_core.rs
- client-core/src/synchronizer/manual_synchronizer.rs
- enclave-protocol/src/lib.rs
Solution: Query informatin using event in deliver_tx
--- 
Before this PR staking account is put into bloom filter in `end_block` event. The syncrhonizer will use the filter to probablistically check if there is staking related transactions inside.
But actually the staking account info. is public and stored inside the `deliver_tx` events.
So there is not need to add the staking address to bloom filter anymore; And should use the `deliver_tx` event instead
> Problem: (CRO-405) Querying public information by probablistic filter

- Cargo.lock
- client-common/Cargo.toml
- client-common/src/key/public_key.rs
- client-common/src/lib.rs
- client-common/src/multi_sig_address.rs
- client-core/src/service/root_hash_service.rs
- client-core/src/signer/default_signer.rs
- client-core/src/transaction_builder/default_transaction_builder.rs
- client-core/src/wallet.rs
- client-core/src/wallet/default_wallet_client.rs
- client-rpc/src/rpc/multisig_rpc.rs
Solution: Extracted MultiSigAddress from root_hash service to serve single responsibility
---
Remarks:
- This PR is a pre-requisite of the JS library by making components re-usable by JS
- Removed n(total_signers) field because it is implied from len of public keys
> Problem: (CRO-582) Create transfer address is not re-usable

- Cargo.lock
- client-cli/Cargo.toml
- client-cli/src/command/transaction_command.rs
- client-network/src/network_ops.rs
- client-network/src/network_ops/default_network_ops_client.rs
Solution: Added support for creating new `node-join` transaction in `client-cli`
Note: I've also performed a basic manual test to check the node addition flow. It works!
> Problem: (CRO-585) No client support for new validator node joining

- chain-tx-enclave/tx-query/enclave/src/lib.rs
- client-core/src/cipher/default.rs
- client-core/src/signer/dummy_signer.rs
Solution:
- still WIP -- didn't turn it on yet, as it'll require modifications in integration test deployments etc.
- there were small problems discovered in full flow testing that should be fixed in this PR:
1) dummy signer didn't follow the cryptographic padding convention, so the estimate fee would sometimes be wrong
2) client couldn't connect to IP addresses, as they are not valid hostnames (hostname required by the TLS library)
3) tx-query randomly failed some requests (witness on CI as well) -- probably due to trying to parse the whole allocated buffer (rather than just the actual request length slice)
> Problem: full client flow not tested with "better" mock encryption+tx-query (CRO-510)

- Cargo.lock
- client-core/Cargo.toml
Solution:
futures related code in client already removed by previous commits,
so simply remove the dependency.
> Problem (CRO-558): client code doesn't compile with futures 0.3

- chain-core/src/init/address.rs
- chain-core/src/init/network.rs
- chain-core/src/tx/data/address.rs
- client-rpc/src/rpc/transaction_rpc.rs
- client-rpc/src/rpc/wallet_rpc.rs
Solution: Add network argument to to_cro()
---
`to_cro()` always encoded with the initialized network, making it mpossible to encode to arbitrary network
> Problem: (CRO-603) Bech32 address always encoded with initialized network

- client-core/src/mnemonic.rs
Solution:
- Ignore the `new-without-default` one.
- Fix the unneeded collect call.
> Problem (CRO-614): clippy error of mnemonic.rs

- before_push.sh
Solution: Add script to do final checkings including build, test, clippy and audit
---
- By default, it runs at quiet mode with a minimum logs output.
- Toggle verbose mode by `./before_push.sh --verbose`
> Problem: (CRO-619) Missing script to do final checkings before push

- chain-tx-validation/src/witness.rs
- client-cli/src/command.rs
- client-common/src/error.rs
- client-core/src/lib.rs
- client-core/src/signer.rs
- client-core/src/signer/dummy_signer.rs
- client-core/src/signer/key_pair_signer.rs
- client-core/src/signer/unauthorized_signer.rs
- client-core/src/signer/wallet_signer.rs
- client-core/src/transaction_builder.rs
- client-core/src/transaction_builder/default_wallet_transaction_builder.rs
- client-core/src/transaction_builder/raw_transfer_transaction_builder.rs
- client-core/src/transaction_builder/unauthorized_wallet_transaction_builder.rs
- client-core/src/unspent_transactions.rs
- client-core/src/wallet/default_wallet_client.rs
- client-network/src/network_ops/default_network_ops_client.rs
- client-rpc/src/rpc/multisig_rpc.rs
- client-rpc/src/rpc/wallet_rpc.rs
- client-rpc/src/server.rs
Solution: Refactor transaction builder and signer to be generic
---
- Keep transaction builder and signer; But rename with wallet prefix
- Extract transaction building logic into `RawTransferTransactionBuilder`
- Refactor `Signer` trait to be generic
> Problem: (CRO-608) Transaction builder and signer are coupled with wallet

- Cargo.lock
- chain-abci/Cargo.toml
- chain-tx-enclave/tx-validation/Dockerfile
- ci-scripts/Dockerfile
- docker/Dockerfile
Solution: updated the CI docker image to have clang installed
> Problem: kvdb-rocksdb 0.2 fails to compile in the container (CRO-620)

- Cargo.lock
- client-common/Cargo.toml
- client-core/Cargo.toml
- client-core/src/transaction_builder/raw_transfer_transaction_builder.rs
- client-mock/Cargo.toml
- client-mock/src/lib.rs
solution:
- update signature to 1.0.0-pre.1
- update signatory to v0.16 in tendermint
> Problem:(CRO-613)client-mock with signatory 0.16 + signature 0.3 fails to compile

- architecture-docs/README.md
- architecture-docs/adr-template.md
Solution: added Architectural Decision Record template + readme
> Problem: no place to record and discuss high level architectural decisions

- client-common/src/tendermint/websocket_rpc_client.rs
Solution: Made `call` and `call_batch` functions `pub`
> Problem: (CRO-622) Raw call function of WebsocketRpcClient cannot be accessed from other crates

- .drone.yml
- Cargo.lock
- chain-abci/Cargo.toml
- chain-abci/src/enclave_bridge/mock.rs
- chain-tx-enclave/tx-query/Dockerfile
- chain-tx-enclave/tx-query/app/src/enclave_u/mod.rs
- chain-tx-enclave/tx-query/app/src/main.rs
- chain-tx-enclave/tx-query/app/src/test/mod.rs
- chain-tx-enclave/tx-query/enclave/Enclave.edl
- chain-tx-enclave/tx-query/enclave/src/attest.rs
- chain-tx-enclave/tx-query/enclave/src/lib.rs
- chain-tx-enclave/tx-query/entrypoint.sh
- chain-tx-enclave/tx-query/make.sh
- chain-tx-enclave/tx-validation/enclave/src/validate.rs
- client-cli/Cargo.toml
- client-cli/src/command.rs
- client-common/src/block_header.rs
- client-common/src/tendermint/types.rs
- client-core/src/cipher/default.rs
- client-core/src/handler/default_block_handler.rs
- client-core/src/synchronizer/manual_synchronizer.rs
- client-network/Cargo.toml
- client-network/src/network_ops/default_network_ops_client.rs
- client-rpc/Cargo.toml
- client-rpc/src/server.rs
- integration-tests/client-rpc/test/network-ops.test.ts
- integration-tests/const-env.sh
- integration-tests/docker-compose.yml
- integration-tests/prepare.sh
Solution:
- changed chain-abci, client-cli and client-rpc default compilation not to use the complete mock
- added decryption in tx-validation by default
- extended client-rpc with mock feature for transaction obfuscation
- added dockerfile etc. for tx-query
- extended integration test setup + drone pipeline
NOTE: transaction confidentiality is still WIP -- currently data is sealed with a static key known at compile time
(rather than some enclave-only random secret that's periodically re-generated by validators' bootstrapping enclaves),
so it's still a "mock", but better in the sense that client workflows are more realistic / closer to the complete implementation
(decryption queries are over attested TLS to the tx-query enclave rather than plain abci query)
> Problem: integration test doesn't use tx-query (CRO-618)

- .travis.yml
- chain-tx-enclave/tx-query/app/src/test/mod.rs
Solution: disable it for the moment (the full integration test is execution
on drone CI), as it'd require more changes in its execution
(recompilation with mock flags etc.)
> Problem: travis CI integration test pipeline is broken

- Cargo.lock
- chain-abci/tests/abci_app.rs
- chain-core/Cargo.toml
- chain-core/src/init/config.rs
- chain-core/src/init/params.rs
- chain-core/src/state/tendermint.rs
- chain-core/tests/verify_config.rs
- client-common/src/tendermint/mock.rs
- dev-utils/example-dev-conf.json
- dev-utils/src/commands/genesis_dev_config.rs
- dev-utils/src/commands/init_command.rs
- integration-tests/fix_genesis.py
- integration-tests/prepare.sh
- test-common/src/block_generator.rs
- test-common/src/chain_env.rs
Solution:
- serialize TendermintValidatorPubKey the same as tendermint.
- Remove ValidatorPubkey in favor of TendermintValidatorPubKey.
> Problem (CRO-627) council node pubkey format different from tendermint

- chain-abci/src/app/query.rs
- chain-core/src/state/account.rs
Solution: Created an `abci_query` endpoint to return list of validators
> Problem: (CRO-527) Missing validator information in block explorer

- chain-abci/src/enclave_bridge/mock.rs
- chain-tx-enclave/tx-query/enclave/src/lib.rs
- client-core/src/cipher/default.rs
- client-core/src/cipher/mock_abci_transaction_obfuscation.rs
- enclave-protocol/src/lib.rs
Solution: changed the enclave protocol response to return result and the tx-query implementation
to return that instead of closing the connection in that case
> Problem: tx-query doesn't return cause for invalid transactions (CRO-638 / CRO-336)

- client-rpc/src/rpc/wallet_rpc.rs
Solution: Exposed `wallet_newPublicKey` method in `client-rpc`
> Problem: (CRO-599) No way to get public key for creating new MultiSig address

- chain-core/src/init/address.rs
- chain-core/src/init/coin.rs
- chain-core/src/init/config.rs
- chain-core/src/init/mod.rs
- chain-core/src/init/params.rs
- chain-core/src/state/account.rs
- chain-core/src/state/mod.rs
- chain-core/src/state/tendermint.rs
- chain-core/src/state/validator.rs
- chain-core/src/tx/data/access.rs
- chain-core/src/tx/data/address.rs
- chain-core/src/tx/data/attribute.rs
- chain-core/src/tx/data/input.rs
- chain-core/src/tx/data/mod.rs
- chain-core/src/tx/data/output.rs
- chain-core/src/tx/fee/mod.rs
- chain-core/src/tx/mod.rs
- chain-core/src/tx/witness/tree.rs
Solution: simplified feature guards to be just a switch on "mesalock_sgx"
instead of various combinations of required crates, as the feature guarding
is only needed for reduced dependencies in the enclave compilation
> Problem: complex feature-guarding of chain-core (CRO-628)

- chain-tx-enclave/tx-query/app/src/test/mod.rs
- integration-tests/docker-compose.yml
Solution: changed wait-for-it in docker compose to tx-query, as that may take the longest time to start up
> Problem: integration tests occasionally fail due to tx-query not started

- chain-tx-enclave/tx-query/enclave/src/attest.rs
Solution: not sure of the cause -- it may be the random generation may fail and needs to be retried... but it could be something else -- added extra loggging for errors from IAS
> Problem: ra cert generation occasionally fails on CI

- client-core/src/cipher/default.rs
- client-core/src/transaction_builder/default_wallet_transaction_builder.rs
- client-core/src/transaction_builder/raw_transfer_transaction_builder.rs
- client-rpc/src/server.rs
Solution: Refactor RawTransferTransactionBuilder and related functions
---
- Rename existing `fee` method to `required_fee`; `fee` method now calculates difference between inputs and outputs
- Extract `get_tx_query` method into DefaultTransactionObfuscation
- Extract transaction obfuscation to until needed
- Creating incomplete transaction now does not require `TxObfuscation` and can be done offline
> Problem: (CRO-635) Transaction builder is not Node.js lib friendly

- CHANGELOG.md
Solution: tried to summarize changes that happened since 0.0.3
--
Let me know if something important is omitted in changelog.
I'll wait for #677 and #669 to get merged before creating binaries.
> Problem: changelog not updated for 0.1 release

- .drone.yml
- .travis.yml
- Cargo.lock
- before_push.sh
- chain-abci/Cargo.toml
- chain-core/Cargo.toml
- chain-core/src/state/tendermint.rs
- chain-tx-enclave/enclave-macro/Cargo.toml
- chain-tx-enclave/enclave-t-common/Cargo.toml
- chain-tx-enclave/enclave-u-common/Cargo.toml
- chain-tx-enclave/tx-query/app/Cargo.toml
- chain-tx-enclave/tx-query/enclave/Cargo.toml
- chain-tx-enclave/tx-validation/app/Cargo.toml
- chain-tx-enclave/tx-validation/enclave/Cargo.toml
- chain-tx-filter/Cargo.toml
- chain-tx-validation/Cargo.toml
- client-cli/Cargo.toml
- client-common/Cargo.toml
- client-core/Cargo.toml
- client-core/src/transaction_builder/raw_transfer_transaction_builder.rs
- client-network/Cargo.toml
- client-rpc/Cargo.toml
- client-rpc/src/server.rs
- dev-utils/Cargo.toml
- dev-utils/src/commands/genesis_command.rs
- enclave-protocol/Cargo.toml
- test-common/Cargo.toml
Solution: Add checking to CI pipeline and fix existing warnings
> Problem: (CRO-654) Fix unnoticed warnings

- Cargo.lock
- client-common/Cargo.toml
- client-common/src/tendermint/lite.rs
- client-core/Cargo.toml
- client-core/src/service/sync_state_service.rs
- client-network/Cargo.toml
- test-common/Cargo.toml
Solution:
- Fixed deserailzation code in tendermint-rs.
- Added unit test to verify.
> Problem: trusted_state serialization/deserailzation not symmetric

- client-cli/src/command.rs
Solution: Added documentation for all environment variables in help command
New help message:
```
client-cli 0.1.1
Basic CLI tool for interacting with Crypto.com Chain
ENVIRONMENT VARIABLES:
CRYPTO_CLIENT_DEBUG             Set to `true` for detailed error messages (Default: `false`)
CRYPTO_CHAIN_ID                 Chain ID of Crypto.com Chain
CRYPTO_CLIENT_STORAGE           Storage directory (Default: `.storage`)
CRYPTO_CLIENT_TENDERMINT        Websocket endpoint for tendermint (Default: `ws://localhost:26657/websocket`)
USAGE:
client-cli <SUBCOMMAND>
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
SUBCOMMANDS:
address        Address operations
balance        Get balance of a wallet
help           Prints this message or the help of the given …
```
> Problem: (CRO-300) No easy way to find client's environment variables

- dev-utils/example-dev-conf.json
- dev-utils/src/commands/genesis_command.rs
- dev-utils/src/commands/genesis_dev_config.rs
- dev-utils/src/commands/init_command.rs
Solution:
- dev-utils use `genesis_time` from `genesis.json`, rather than `dev-utils.json`
- Remove `genesis_time` field from `dev-utils.json`
> Problem: dev-utils generates incorrect app hash

- .gitignore
- ci-scripts/run-integration-tests.sh
- client-cli/src/command.rs
- client-cli/src/command/address_command.rs
- client-core/src/service/wallet_service.rs
- client-core/src/service/wallet_state_service.rs
- client-core/src/unspent_transactions.rs
- client-core/src/wallet.rs
- client-core/src/wallet/default_wallet_client.rs
- client-rpc/src/rpc/multisig_rpc.rs
- client-rpc/src/rpc/wallet_rpc.rs
- client-rpc/src/server.rs
- integration-tests/.gitignore
- integration-tests/bot/chainrpc.py
- integration-tests/bot/tests/conftest.py
- integration-tests/bot/tests/test_watch_only_wallet.py
- integration-tests/client-rpc/test/core/utils.ts
- integration-tests/client-rpc/test/hdrestore-auto-sync.test.ts
- integration-tests/client-rpc/test/hdrestore-transaction.test.ts
- integration-tests/client-rpc/test/hdwallet-auto-sync.test.ts
- integration-tests/client-rpc/test/hdwallet-management.test.ts
- integration-tests/client-rpc/test/hdwallet-transaction.test.ts
- integration-tests/client-rpc/test/network-ops.test.ts
- integration-tests/client-rpc/test/wallet-auto-sync.test.ts
- integration-tests/client-rpc/test/wallet-management.test.ts
- integration-tests/client-rpc/test/wallet-transaction.test.ts
Solution:
- Add these apis to client-rpc:
- restoreBasic(WalletRequest, String[hex encoded private view key])
- createStakingWatchAddress(WalletRequest, PublicKey)
- createTransferWatchAddress(WalletRequest, PublicKey)
- listUTxO(WalletRequest)
- Add several paramters to transactions api:
- transactions(WalletRequest, offset: usize, limit: usize, reversed: bool)
- Makes several api changes for testing convinience:
- Add private option to `view_key` to get private view key.
- Add `list_pub_key` command to client-cli to list public keys of
transfer addresses.
- Also record the public key in wallet when creating transfer address.
Implemented integration tests in python.
> Problem (CRO-642): no "watch-only" wallet mode in client

- Cargo.lock
- chain-abci/Cargo.toml
- chain-abci/src/app/query.rs
- chain-abci/src/storage/account/mod.rs
- chain-abci/src/storage/mod.rs
- chain-abci/tests/abci_app.rs
- chain-abci/tests/tx_validation.rs
- chain-core/src/init/address.rs
- chain-core/src/state/tendermint.rs
- chain-core/src/tx/data/address.rs
- client-common/src/tendermint/websocket_rpc_client/websocket_rpc_loop.rs
- client-core/src/transaction_builder/default_wallet_transaction_builder.rs
- client-rpc/src/server.rs
- dev-utils/Cargo.toml
- dev-utils/src/commands/init_command.rs
- test-common/Cargo.toml
- test-common/src/block_generator.rs
- test-common/src/chain_env.rs
Solution: updated chain-abci etc. (the main change in APIs was
not allowing empty columns and using u32 instead of Option<u32>)
> Problem: latest kvdb crates don't compile (CRO-674)

- Cargo.lock
- client-common/src/error.rs
- client-core/Cargo.toml
- client-core/src/wallet/default_wallet_client.rs
Solution: Estimate password strength using `zxcvbn` crate. Return `Error` when password score is less than 3.
> Problem: (CRO-577) Client allows weak passphrases

- client-cli/src/command.rs
Solution: Drop syncer before join progress reporting thread.
> Problem: client-cli sync hangs after sync complete

- client-common/src/tendermint/websocket_rpc_client.rs
Solution: Use sequencial atomic variable to generate unique method ids.
> Problem: websocket rpc method id may overlap

- client-common/src/tendermint/websocket_rpc_client.rs
Solution:
- Include the error message returned by chain-abci.
The error message is: `Invalid input: abci query fail: 1, tx query address not set`
> Problem: unclear client error message when tx-query not set

- Cargo.lock
- client-common/Cargo.toml
- client-core/Cargo.toml
- client-network/Cargo.toml
- test-common/Cargo.toml
- test-common/src/block_generator.rs
Solution:
- Fix the problem in tendermint-rs
- Upgrade dependency
tendermint-rs PR for this: https://github.com/interchainio/tendermint-rs/pull/103
> Problem: block id field in vote could be empty

- CHANGELOG.md
- chain-core/src/tx/data/input.rs
- client-cli/src/command/transaction_command.rs
- client-common/src/lib.rs
- client-common/src/transaction.rs
- client-core/src/service/wallet_service.rs
- client-core/src/transaction_builder.rs
- client-core/src/transaction_builder/default_wallet_transaction_builder.rs
- client-core/src/transaction_builder/unauthorized_wallet_transaction_builder.rs
- client-core/src/wallet.rs
- client-core/src/wallet/default_wallet_client.rs
- client-core/src/wallet/syncer.rs
- client-core/src/wallet/syncer_logic.rs
- client-rpc/src/rpc/wallet_rpc.rs
solution:
- add a interface `export_tx` for sender to get the plain transaction
- add a interface `import_tx` for receiver to import the plain transaction and get the output UTXO
> Problem:(CRO-557) no way to import transactions (without a view key)

- Cargo.lock
- chain-tx-enclave/tx-validation/app/Cargo.toml
- chain-tx-enclave/tx-validation/app/src/main.rs
- chain-tx-enclave/tx-validation/app/src/test/mod.rs
- client-common/Cargo.toml
- client-common/src/storage/sled_storage.rs
Solution: Changed `Db::open` to `sled::open`. `Db::open` is now deprecated.
> Problem: (CRO-680) Latest sled fails to compile

- .travis.yml
- before_push.sh
- client-common/src/tendermint/http_rpc_client.rs
Solution: Fix compilation error
---
- Add `cargo build` test in TravisCI
- Port changes from `WebSocketRpcClient` to `HttpRpcClient` to fix compilation error
> Problem: (CRO-678) Tendermint HttpRpcClient compilation error

- CHANGELOG.md
- Cargo.lock
- chain-abci/Cargo.toml
- chain-core/Cargo.toml
- chain-tx-enclave/tx-query/app/Cargo.toml
- chain-tx-enclave/tx-query/enclave/Cargo.toml
- chain-tx-enclave/tx-validation/app/Cargo.toml
- chain-tx-enclave/tx-validation/enclave/Cargo.toml
- chain-tx-filter/Cargo.toml
- chain-tx-validation/Cargo.toml
- client-cli/Cargo.toml
- client-common/Cargo.toml
- client-core/Cargo.toml
- client-network/Cargo.toml
- client-rpc/Cargo.toml
- dev-utils/Cargo.toml
- enclave-protocol/Cargo.toml
- test-common/Cargo.toml
Solution: updated changelog, bumped version numbers to 0.3.0
note -- 0.2.1 has changes cherry-picked from master onto release/v0.2 branches: https://github.com/crypto-com/chain/commit/ae5666204187e1223cb9b1ab5c659111d9beba94
> Problem: client breaking changes not recorded

- chain-tx-enclave/tx-query/enclave/src/attest.rs
- chain-tx-enclave/tx-validation/app/src/enclave_u/mod.rs
- chain-tx-enclave/tx-validation/app/src/server/mod.rs
- chain-tx-enclave/tx-validation/enclave/Cargo.toml
- chain-tx-enclave/tx-validation/enclave/src/lib.rs
- chain-tx-enclave/tx-validation/enclave/src/obfuscate.rs
- chain-tx-enclave/tx-validation/enclave/src/validate.rs
- enclave-protocol/src/error.rs
- enclave-protocol/src/lib.rs
> Problem:(CRO-661) not enough logging in debug enclave execution

- architecture-docs/adr-001.md
Solution: refined the ADR-001 based on the early experiments and
discussions where embedding tx-validation wrapper
app into chain-abci was preferred
> Problem: no clear decision on ADR-001

- client-core/src/wallet/syncer.rs
Solution:
- refuse to sync when tendermint catching up.
- retry several times for temparary catching up status.
> Problem #831: client sync fails if TM is catching up with the network

- chain-core/src/tx/data/access.rs
- client-cli/src/command/transaction_command.rs
Solution: Used `BTreeSet` instead of `Vec`. Fixes https://github.com/crypto-com/chain/issues/840
> Problem: User may enter same view key multiple times in client-cli

- chain-abci/src/app/app_init.rs
issue: #832 
solution: each time when chain-abci start, check the last app states stored in `COL_APP_STATES` to force to store historical state data or not.
> Problem:(Fix #832) random client failing if node didn't store historical state data

- chain-tx-validation/src/lib.rs
Solution: Added a more detailed error message. Fixes https://github.com/crypto-com/chain/issues/838
> Problem: Ambiguous error message for empty staking address

- client-cli/src/command.rs
- client-core/src/types/transaction_change.rs
- client-rpc/src/program.rs
Solution: Show transaction type in history. This addresses a part of https://github.com/crypto-com/chain/issues/846
Sample output after this change:
```
+------------------------------------------------------------------+--------+----------------------+-----+------------------+--------------+--------------------------------+
| Transaction ID                                                   | In/Out | Amount               | Fee | Transaction Type | Block Height | Block Time                     |
+------------------------------------------------------------------+--------+----------------------+-----+------------------+--------------+--------------------------------+
| cc88d0ca2cbcd6ce167a6db426f40c3da034deb5b4e4f09e5ec01f39af80c0ea | IN     | 24999999999.99999703 |   - | Withdraw …
```
> Problem: Client CLI does not show transaction type in history

- chain-tx-enclave/tx-query/enclave/Cargo.toml
- chain-tx-enclave/tx-query/enclave/Enclave.edl
- chain-tx-enclave/tx-query/enclave/src/attest.rs
reason: tx-query fails and crash if the network connection to intel failed, this happens when generating a certification while the first request coming. So when the tx-query starts, using `wait-for-it.sh` to check will pass, but when the first request coming and if the network connection to intel error, tx-query will crash.
solution:  retry 3 times when `SGX_ERROR_BUSY` error happens.
> Problem:(CRO-647)integration test occasionally fails due to tx-query not started up

- chain-tx-enclave/enclave-t-common/src/lib.rs
- chain-tx-enclave/tx-query/app/src/enclave_u/mod.rs
- chain-tx-enclave/tx-query/enclave/src/attest.rs
- chain-tx-enclave/tx-query/enclave/src/cert.rs
- chain-tx-enclave/tx-query/enclave/src/lib.rs
- chain-tx-enclave/tx-validation/app/src/server/mod.rs
- chain-tx-enclave/tx-validation/enclave/src/lib.rs
- chain-tx-enclave/tx-validation/enclave/src/obfuscate.rs
- chain-tx-enclave/tx-validation/enclave/src/validate.rs
Solution:
- Fix existing clippy suggestions.
- Can't add clippy on enclave into travis ci script yet due to lack of sgx sdk
The `cast_ptr_alignment` warning looks suspicious, the correctness dependents on the alignment of `Vec<u8>` pointer, I think normal allocator will produce aligned pointer, so it should be fine normally.
Run on linux:
```
$ cargo clippy -p tx-validation-app -p tx-query-app
$ cargo clippy -p tx-validation-enclave -p tx-query-enclave
```
> Problem (#870): There are unfixed clippy suggestions on enclave code

- .drone.yml
- chain-tx-enclave/tx-query/app/src/main.rs
- chain-tx-enclave/tx-validation/app/src/main.rs
- ci-scripts/tx-query-hw-test.sh
- ci-scripts/tx-validation-hw-test.sh
Solution:
- exiting enclave wrapper apps with status code on error
- fixed CI scripts to build wrapper apps with sgx-test feature (not possible in the workspace :( )
- signed the pipeline + added ttl
> Problem: sgx-cargo-1804-* tests failures not reflected in CI (fix #904)

- dev-utils/src/commands/genesis_command.rs
- integration-tests/bot/chainbot.py
Solution:
- Add `--no_backup` option to `dev-utils`, and chainbot use it.
> Problem(Fix #908): chainbot sometimes fail because tendermint config backup file conflict

- .travis.yml
Solution: not run it with --all?
> Problem: cargo kcov stopped working after the workspace build changes (fix #918)

- integration-tests/cleanup.sh
- integration-tests/deps.sh
- integration-tests/pytests/conftest.py
- integration-tests/pytests/test_watch_only_wallet.py
- integration-tests/run.sh
Solution:
- Add python integration tests to the `run` script
- moved the python tests directory to `integration-tests/pytests`
- fix the python test
This one is based on https://github.com/crypto-com/chain/pull/916, after that one is merged, rebase this one.
> Problem (Fix: #912): python integration tests not executed in CI

- chain-tx-enclave/tx-query/app/src/main.rs
- ci-scripts/run_tx_query.sh
Solution:  add environment check when the tx-query app starts, remove the environment check in the docker run script.
> Problem(fix #882):required tx-query environment vaiables are unchecked

- chain-abci/src/app/mod.rs
- chain-abci/tests/punishment.rs
- chain-abci/tests/validator_changes.rs
- test-common/src/chain_env.rs
Solution: Changed new voting power assignment logic. Fixes https://github.com/crypto-com/chain/issues/910
Note: 
- Logic is slightly different than the one in issue description.
- This PR only includes basic test scenarios and does not cover all the possible cases.
> Problem: Unbonding any amount removes a validator

- .drone.yml
Solution: disabled "ttl" -- will need to do custom cleanups on Drone CI server
> Problem: venv may be corrupted after Drone cache cleanups

- .gitignore
- client-cli/src/command.rs
- client-cli/src/command/address_command.rs
- client-cli/src/command/transaction_command.rs
- client-cli/src/command/wallet_command.rs
Solution: Fixed all the issues described in https://github.com/crypto-com/chain/issues/951. Fixes #951
> Problem: Ambiguous outputs from client-cli

- Cargo.lock
Solution: it seems it was force-pushed;
updated Cargo.lock with the correct commit ref
> Problem: chrono-sgx dependency commit ref doesn't exist (fix #965)

- CHANGELOG.md
- chain-core/src/tx/fee/mod.rs
- client-cli/src/command.rs
- client-common/src/tendermint/types/block_results.rs
- client-core/src/service/wallet_state_service.rs
- client-core/src/types/transaction_change.rs
- client-core/src/wallet/default_wallet_client.rs
- client-core/src/wallet/syncer.rs
- client-core/src/wallet/syncer_logic.rs
Solution:
- removed the "balance change" output custom fee calculation / deduction
- added paid fee to the balance change that's directly taken from events / attributes
Note: transaction details was moved to a separate issue: https://github.com/crypto-com/chain/issues/968
> Problem: incorrect fee display in history (#846)

- chain-core/src/init/network.rs
Solution: converted tabs to spaces
> Problem: clippy 1.41 warns about inconsistent spacing in comments

- chain-abci/src/enclave_bridge/mock.rs
- chain-storage/src/tx.rs
- integration-tests/bot/chainbot.py
- integration-tests/deps.sh
Solution:
- make mock mode build again.
- add a chainbot option to support mock mode.
The integration tests run successfully locally with the mock mode.
```
$ docker/build.sh mock
$ cd integration-tests
$ chainbot.py prepare zero_fee_cluster.json --mock-mode
$ ...
```
> Problem(Fix #991): mock mode doesn't build

- .gitignore
- CHANGELOG.md
- client-cli/src/command.rs
- client-cli/src/command/multisig_command.rs
- client-rpc/src/rpc/multisig_rpc.rs
- client-rpc/src/rpc/wallet_rpc.rs
Solution: Add new and list methods to ClientRPC and ClientCLI
> Problem: (Fix #972) Missing MultiSig pubkey methods in ClientRPC and ClientCLI

- Cargo.lock
Solution: updated Cargo.lock, as the fork of webpki seems to have been force-pushed
> Problem: enclave code cannot be built due to webpki (fix #1030)

- chain-abci/src/app/app_init.rs
- chain-abci/src/app/app_init/validator_state.rs
- chain-abci/src/app/app_init/validator_state_update.rs
- chain-abci/src/app/end_block.rs
- chain-abci/src/app/mod.rs
- chain-abci/src/app/rewards.rs
- chain-abci/tests/abci_app.rs
- chain-abci/tests/punishment.rs
- chain-abci/tests/tx_validation.rs
- chain-abci/tests/validator_changes.rs
- chain-core/src/init/config.rs
- chain-core/src/state/tendermint.rs
- chain-tx-validation/src/lib.rs
- client-common/src/tendermint/mock.rs
- dev-utils/example-dev-conf.json
- dev-utils/src/commands/genesis_dev_config.rs
- integration-tests/bot/chainbot.py
- integration-tests/multinode/jail_test.py
- integration-tests/with_fee_cluster.json
- integration-tests/zero_fee_cluster.json
- test-common/src/block_generator.rs
- test-common/src/chain_env.rs
Solution:
based on https://github.com/crypto-com/chain-docs/pull/66/files
- tx validation of node join takes into account minimum effective stake
- added unbonding period check against jail
- validator data is cleaned after end block update generation + for data that can't be deleted yet (e.g. for later byzantine validator lookups), it's scheduled to be deleted after unbonding period
- if (non-jailed) validator re-joins with the same key, the deletion schedule is cancelled
- updated the test configs
NOTE: genesis files in docker/config/* may need updating
> Problem: unbonded or unjailed validator cannot rejoin the validator set (fix #930)

- chain-abci/src/app/app_init/validator_state.rs
Solution:
- Don't reward jailed account
> Problem (Fix #1034): node with a jailed staked state remains/returns as an active validator

- integration-tests/multinode/byzantine_cluster.json
- integration-tests/multinode/byzantine_test.py
- integration-tests/run_multinode.sh
Solution:
- test procedure:
- 3 nodes
- node2 has more than 2/3 voting powers
- node0 and node1 have same validator seed, both have 0 bonded coins initially, only unbonded coins.
- start the nodes, and stop node1 immediately.
- withdraw, deposit and join node0.
- start node1, check node0 punished with byzantine fault.
> Problem (Fix #850): no automated test for jailing using byzantine faults

- client-cli/src/command.rs
Solution: Added a warning mentioning that the information may be outdated. One possible improvement is that we can record the time of last synced block and display that in the warning. Fixes #980.
> Problem: client-cli history/balance may display outdated information

- .drone.yml
- bors.toml
Solution: renamed the custom drone to "drone-hw" + updated the pipeline sig after restart
> Problem: drone check status name collides with the cloud version

- chain-abci/src/app/app_init/validator_state.rs
Solution:
- Check `tendermint_validator_addresses` when `liveness_tracker` not found, if cleaned up, log error otherwise log info.
> Problem (Fix #1007): liveness tracker doesn't contain information about some nodes in multi-node integration test

- client-cli/src/command/transaction_command.rs
- client-core/src/service/wallet_state_service.rs
- client-core/src/wallet.rs
- client-core/src/wallet/default_wallet_client.rs
Solution: Added `transaction show` command to display all the transaction information. Fixes #968.
> Problem: No way to display transaction details in client-cli

- .drone.mock.yml
- .gitignore
- dev-utils/Cargo.toml
- docker/Dockerfile.new
- docker/build.sh
- docker/unittest.sh
- integration-tests/run.sh
- integration-tests/run_multinode.sh
Solution:
- Add mock drone to run integration-tests on cloud.drone.io
- Use cargo-make to do coverage
- Prebuilt kcov in chain-test image
- Change 127.0.0.1 -> localhost for executing test on cloud.drone.io
Needs to update image `cryptocom/chain-test:latest` first:
```
$ docker build -f docker/Dockerfile.new --target TEST -t cryptocom/chain-test:latest .
$ docker push cryptocom/chain-test:latest
```
Add `CODECOV_TOKEN` into drone secret for upload coverage report to codecov.io
> Problem (Fix #1050): No integration-tests CI running in the cloud automatically

- integration-tests/bot/chainbot.py
- integration-tests/pytests/test_watch_only_wallet.py
Solution:
- Merge two times of wallet restore into one.
> There is also a change to make `test_watch_only_wallet` more stable.
> Problem (Fix #1067): chainbot.py prepare runs slow

- client-cli/src/command/address_command.rs
- client-cli/src/command/wallet_command.rs
solution: add `restore basic wallet ` and `create watch address` in client-cli
> Problem(fix #1043) watch-only mode cannot be used in client-cli

- integration-tests/multinode/byzantine_test.py
Solution:
- Workaround the issue by adding 5 seconds sleep.
> Problem (Fix #1097): byzantine integration-tests fail occasionally

- chain-abci/src/app/app_init/validator_state.rs
Solution:
- Check validator not active when record reward stats
> Problem (Fix #1091): Inactivated validator can still appear in block proposer

- chain-abci/tests/validator_changes.rs
- chain-core/src/common/fixed.rs
- chain-core/src/init/params.rs
Solution:
- Add more reasoning into the range of parameters.
The reasoning behind the choice:
https://github.com/crypto-com/chain/issues/1089#issuecomment-587327223
> Problem (Fix #1089): the upper bound of reward parameters are too restrictive

- chain-abci/src/app/rewards.rs
- chain-abci/tests/validator_changes.rs
- chain-core/src/state/account.rs
Solution:
- Increase nonce by one when add reward.
> Problem (Fix #1095): Reward distribution don't increase staking account's nonce

- client-cli/src/command/transaction_command.rs
- client-core/Cargo.toml
- client-core/src/transaction_builder.rs
- client-core/src/transaction_builder/raw_transfer_transaction_builder.rs
- client-core/src/unspent_transactions.rs
- client-core/src/wallet.rs
- client-core/src/wallet/default_wallet_client.rs
- client-rpc/Cargo.toml
- client-rpc/src/rpc/wallet_rpc.rs
- integration-tests/bot/chainrpc.py
- integration-tests/cleanup.sh
- integration-tests/deps.sh
- integration-tests/pytests/test_wallet_offline.py
solution:
* on online wallet, create a watch-only wallet, dump the inputs and other needed info as base64 string
* on offline wallet,  create a signed transaction using the dumped info
* send the signed transaction on the online wallet, wallet state be will updated on watch-only wallet
> Problem(fix #865)  no way to run client in air-gapped settings

- Cargo.lock
- chain-abci/Cargo.toml
- chain-storage/Cargo.toml
- dev-utils/Cargo.toml
- test-common/Cargo.toml
Solution: bumped versions of all three related crates
> Problem: kvdb 0.4 fails to compile (fixes #1015)

- cro-clib/Cargo.toml
- cro-clib/Makefile
Solution: add ios compile script
this builds ios cro-clib on mac
1. install xcode
2. run `make ios` in cro-clib folder
> Problem:(cro-1046)no c-api bindings for ios

- chain-abci/src/enclave_bridge/mock.rs
- client-core/src/signer/dummy_signer.rs
- integration-tests/multinode/join_cluster.json
- integration-tests/multinode/join_test.py
- integration-tests/pytests/test_small.py
- integration-tests/zero_fee_cluster.json
Solution:
- Fix DummySigner for deposit transaction
- Fix mock_enc_dec payload padding
- Test withdraw with viewkeys in the multinode join test (Fix #1101  )
> Problem (Fix #949): deposit amount fee calculation is not correct

- Cargo.lock
- chain-abci/src/app/mod.rs
- chain-abci/src/app/query.rs
- chain-abci/src/app/validate_tx.rs
- chain-abci/src/storage/mod.rs
- chain-abci/tests/abci_app.rs
- chain-storage/src/account/mod.rs
- chain-storage/src/lib.rs
- chain-storage/src/tx.rs
Solution: for the TX-related ops, added a temporary map in storage:
- insertions during delivertx will update the temporary map + insert entry into the current db tx
- at commit, the db tx is written and flushed
- lookup extended to indicate whether the caller wants to read the uncommitted change (as in delivertx
-- e.g. if two transactions in the same block want to spend the same utxo,
only the first one is valid, so processing needs to read the uncommitted change from the first one before processing the second one)
or committed change (e.g. in queries)
added two quick unit tests (the first one used to fail with "buffered_write" -- "buffered_write" was removed, as inserts are kind of buffered writes)
> Problem: uncommitted chain-abci storage changes may persisted (fixes #885)

- CHANGELOG.md
- Cargo.lock
- chain-abci/Cargo.toml
- chain-core/Cargo.toml
- chain-storage/Cargo.toml
- chain-tx-enclave/tx-query/app/Cargo.toml
- chain-tx-enclave/tx-query/enclave/Cargo.toml
- chain-tx-enclave/tx-validation/enclave/Cargo.toml
- chain-tx-filter/Cargo.toml
- chain-tx-validation/Cargo.toml
- client-cli/Cargo.toml
- client-common/Cargo.toml
- client-core/Cargo.toml
- client-network/Cargo.toml
- client-rpc/Cargo.toml
- dev-utils/Cargo.toml
- enclave-protocol/Cargo.toml
- test-common/Cargo.toml
Solution: updated changelog + bumped version numbers
--
Note this PR contains 2 commits, as the one with 0.3.1 will be cherry-picked onto release/v0.3 with the aforementioned fixes
> Problem: 0.3.1 not reflected in changelog

- Cargo.lock
- chain-tx-validation/src/lib.rs
- client-cli/Cargo.toml
- client-cli/src/command/wallet_command.rs
- client-core/src/service.rs
- client-core/src/service/wallet_service.rs
- client-core/src/wallet.rs
- client-core/src/wallet/default_wallet_client.rs
- client-rpc/src/rpc/multisig_rpc.rs
- client-rpc/src/rpc/staking_rpc.rs
- client-rpc/src/rpc/sync_rpc.rs
- client-rpc/src/rpc/wallet_rpc.rs
- client-rpc/src/server.rs
Solution: 
* add `export` method to backup a wallet, and `import` method to store the wallet again, both in client-rpc and client-cli
* add unit test
> Problem:(fix #827)no import/export for non-HD keys

- Cargo.lock
- Cargo.toml
- client-core/src/synchronizer.rs
- client-core/src/transaction_builder/default_wallet_transaction_builder.rs
- client-rpc/src/lib.rs
- client-rpc/src/rpc/sync_rpc.rs
- cro-clib/Cargo.toml
- cro-clib/chain.h
- cro-clib/src/jsonrpc.rs
- cro-clib/src/lib.rs
- cro-clib/src/transaction_staking.rs
- docker/build.sh
Solution:
- create `jsonrpc_call` api to encapulate all commands of `client-rpc`.
> Problem (Fix #1121): Too tedious to create separated c apis for all client features

- Makefile
- ci-scripts/run_chain_abci.sh
- ci-scripts/run_tx_query.sh
- docker/Dockerfile
Solution: remove tx-validation-app component from makefile and dockerfile
fix  enclave.socket issue for run-abci and run-sgx-query to share same unix domain socket
replace run_tx_validation.sh with ci-scripts/run_chain_abci.sh to make sure abci can replace the deprecated tx-validation-app 
fix other minor issue like setting $PID in shell script
> Problem: Makefile is trying to compile tx-validation-ap #1128

- client-cli/src/command/transaction_command.rs
solution:
* remove `deposit-amount` command 
* use deposit amount as default
* deposit `inputs` to a staking address in `--advanced` mode
> Problem:(fix #1148) default deposit client-cli flow is complex

- chain-storage/src/lib.rs
Solution: added explicit cleanups after successful (not failing) test execution
> Problem: Persistence unit tests cannot run twice successfully (fixes #1169)

- chain-abci/fuzz/fuzz_targets/abci_cycle.rs
- chain-abci/src/app/app_init.rs
- chain-abci/src/app/mod.rs
Solution: refactored validators<->council nodes check
and added that as an extra filter to the fuzzer
Note: we'll see how it goes with this raw byte stream fuzzing;
we may possibly restrict it with:
https://rust-fuzz.github.io/book/cargo-fuzz/structure-aware-fuzzing.html
> Problem: fuzzer crashes with invalid initchain (fixes #1178)

- CHANGELOG.md
- client-core/src/service/key_service.rs
- client-core/src/service/root_hash_service.rs
- client-core/src/service/wallet_service.rs
- client-core/src/signer/wallet_signer.rs
- client-core/src/wallet.rs
- client-core/src/wallet/default_wallet_client.rs
- client-core/src/wallet/syncer.rs
- client-network/src/network_ops/default_network_ops_client.rs
- client-rpc/src/rpc/multisig_rpc.rs
solution:
* store the (wallet_name, wallet's private_key) in `KeySerivce`
* move the (public_key, private_key) pair (used for transfer add and staking address) in `Wallet`
* extend the `root_hash` with the `wallet_name` as  storage_key to store the `multi_sig_address`
* add unit test
> Problem(fix #914) Unable to restore wallet with the same mnemonic words

- chain-abci/src/app/mod.rs
- chain-abci/src/app/validate_tx.rs
- chain-abci/src/storage/mod.rs
- chain-core/src/state/account.rs
- chain-storage/src/account/mod.rs
Solution:
- Use `TxEnclaveAction` to seperate enclave tx validation and execution.
This is a refactoring prepared for the latter revised staking implementation.
> Problem (Fix #1214): Tx validation mutate StakedState directly

- cro-clib/chain.h
- cro-clib/examples/Makefile
- cro-clib/examples/rpc.c
- cro-clib/src/jsonrpc.rs
- cro-clib/src/types.rs
1.  add context
2. for different request, you can give different user_data as void*
```
actual code is  called in-directly via `handle_request_sync`, so, callback is stored at trait,
and called afterwards
this is for simplicity of reusing rpc-server.
also json run code is all synchronous.
```
rpc call1 end
rpc call2 end
for autosync, call is sync,
but actual syncing is endless. 
so, other thread checking via polling  
it's will be added soon.
> Problem:(cro-1132) repeated db open/close and thread spawning `jsonrpc_call` C binding#1132

- Cargo.lock
- Cargo.toml
- chain-tx-enclave/enclave-utils/Cargo.toml
- chain-tx-enclave/enclave-utils/src/lib.rs
Solution: added an enclave-utils crate that contains a parsed for Intel SDK sealed payloads
and unseals them using aes-gcm crate
> Problem: no way to unseal Intel SDK payloads directly in Rust (fixes #1227)

- chain-abci/src/app/app_init.rs
- chain-abci/src/app/end_block.rs
- chain-abci/src/app/mod.rs
- chain-abci/src/app/query.rs
- chain-abci/src/enclave_bridge/mock.rs
- chain-abci/src/liveness.rs
- chain-abci/tests/abci_app.rs
- chain-abci/tests/tx_validation.rs
- chain-core/src/state/mod.rs
- chain-core/src/state/tendermint.rs
- chain-storage/src/lib.rs
- chain-tx-enclave/tx-validation/enclave/src/obfuscate.rs
- client-core/src/cipher/mock_abci_transaction_obfuscation.rs
- client-core/src/signer/dummy_signer.rs
- client-core/src/transaction_builder/default_wallet_transaction_builder.rs
- client-core/src/transaction_builder/raw_transfer_transaction_builder.rs
- client-network/src/network_ops/default_network_ops_client.rs
- client-rpc/src/rpc/wallet_rpc.rs
Solution:
- Change `BlockHeight` to a newtype over u64
- Only support safe operations like `checked_sub/add`, `saturating_sub/add`.
> Problem: i64 doesn't represent the semantic of BlockHeight

- chain-abci/src/enclave_bridge/mock.rs
Solution:
- Check payload transaction type in mock enclave.
> Problem (Fix #1248): crash with withdraw transaction

- CHANGELOG.md
- chain-abci/src/app/commit.rs
- chain-abci/src/app/mod.rs
- chain-abci/src/app/validate_tx.rs
- chain-abci/src/storage/mod.rs
- chain-abci/tests/abci_app.rs
- chain-abci/tests/tx_validation.rs
- chain-core/src/tx/mod.rs
- client-common/src/tendermint/types.rs
- client-network/src/network_ops/default_network_ops_client.rs
- cro-clib/chain-core.h
- cro-clib/src/transaction.rs
- cro-clib/src/transaction_staking.rs
- cro-clib/src/types.rs
- test-common/src/chain_env.rs
Solution:
- Change the structure of TxAux
> Problem (Fix #1222): non-enclave / public transactions don't have a common outer type

- chain-storage/src/buffer.rs
- chain-storage/src/lib.rs
Solution:
- Implement a buffered storage abstraction for future revised staking implementation.
> This is separated from and will be used by the following PR.
> Problem: No storage abstraction to implement check_tx/deliver_tx/commit logic

- Cargo.lock
- chain-tx-enclave/enclave-utils/Cargo.toml
- chain-tx-enclave/enclave-utils/src/lib.rs
Solution: temporarily put attributes from tx validation + added temporary seal
when this WIP is finished, `cargo test --target x86_64-fortanix-unknown-sgx`
could perhaps but put into a CI pipeline
> Problem: EDP unseal doesn't work/compile (fixes #1274)

- chain-tx-enclave/enclave-utils/src/lib.rs
- cro-clib/chain-core.h
Solution: encrypting the actual data in place instead of a vector of 0s
(random change: with bindgen version change, constants got comments now)
> Problem: seal in enclave-utils doesn't work

- chain-abci/src/app/app_init.rs
Solution:
- Initialize mempool_state in init chain event.
> Problem (Fix #1282): chain-abci may crash with unititialized mempool storage

- chain-abci/src/app/commit.rs
- chain-abci/src/enclave_bridge/mock.rs
- chain-abci/src/enclave_bridge/real/test/seal.rs
- chain-abci/src/storage/mod.rs
- chain-abci/tests/abci_app.rs
- chain-abci/tests/tx_validation.rs
- chain-core/src/tx/data/input.rs
- chain-core/src/tx/mod.rs
- chain-storage/src/api.rs
- chain-tx-enclave/tx-query/enclave/src/lib.rs
- chain-tx-enclave/tx-validation/enclave/src/validate.rs
- client-core/src/signer/dummy_signer.rs
- client-core/src/transaction_builder/default_wallet_transaction_builder.rs
- client-core/src/transaction_builder/raw_transfer_transaction_builder.rs
- client-core/src/wallet/syncer_logic.rs
- client-network/src/network_ops/default_network_ops_client.rs
- client-rpc/src/rpc/wallet_rpc.rs
Solution: rename TxoIndex to TxoSize
this is just renaming type "TxoIndex", that is u16
other code is the same.
> Problem:(cro-1223) TxoIndex is misused to refer to output size #1223

- client-rpc/src/rpc/staking_rpc.rs
Solution:
- make deposit amount return the tx id of the last transaction,
rather than the first one.
> Problem (Fix #1273): "deposit_amount" test failed occationally

- Cargo.lock
Solution: `cargo update -p bumpalo`
it seems this was just a compile-time dependency of some wasm-related tools
> Problem: security flaw in external dependency (RUSTSEC-2020-0006)

- .drone.yml
Solution:
- Move it into default pipeline
```
drone exec --trusted --include sgx-test
```
> Problem (Fix #1296): sgx-cargo-1804-hw1 is not easy to run locally

- chain-abci/src/app/query.rs
- chain-core/src/common/merkle_tree.rs
Solution: Added a check to verify that `hash(leaf_value) == path.leaf_hash`. Fixes #1329
> Problem: inclusion proof does not verify that hash(leaf_value) == path.leaf_hash

- chain-abci/tests/abci_app.rs
- chain-abci/tests/tx_validation.rs
- chain-core/src/common/merkle_tree.rs
Solution: removed leaf_hash and using the computed value
+ updated the related internal API
- note this reduced the TX size, so fee in some tests also decreased that were updated
> Problem: redundant leaf_hash stored in merkle proof (fixes #1333)

- .travis.yml
- Cargo.lock
- client-common/Cargo.toml
- client-common/src/tendermint/lite.rs
- client-common/src/tendermint/mock.rs
- client-common/src/tendermint/types.rs
- client-common/src/tendermint/websocket_rpc_client.rs
- client-core/Cargo.toml
- client-core/src/cipher/mock_abci_transaction_obfuscation.rs
- client-core/src/service/sync_state_service.rs
- client-core/src/wallet/syncer.rs
- client-network/Cargo.toml
- client-network/src/network_ops/default_network_ops_client.rs
- client-rpc/src/rpc/wallet_rpc.rs
- integration-tests/multinode/byzantine_test.py
- integration-tests/multinode/multitx_test.py
- test-common/Cargo.toml
- test-common/src/block_generator.rs
Solution:
- Update custom fork to recent upstream master
- migrate to new lite client API and other changes
Several things postponed:
- several parameters in lite client verification hardcoded.
- the first block is not verified because of the limitation of the new API, issue is created in upstream.
> Problem (Fix #1342): Custom tendermint-rs fork lag behind upstream too much

- chain-abci/src/staking/mod.rs
- chain-abci/tests/abci_app.rs
- chain-abci/tests/tx_validation.rs
- chain-core/src/init/config.rs
- chain-core/src/state/account.rs
- chain-core/tests/verify_config.rs
- chain-storage/src/account/mod.rs
- client-cli/src/command/transaction_command.rs
- client-common/src/tendermint/mock.rs
- client-network/src/network_ops/default_network_ops_client.rs
- client-rpc/src/rpc/staking_rpc.rs
- cro-clib/src/transaction_staking.rs
- dev-utils/src/commands/genesis_command.rs
- dev-utils/src/commands/genesis_dev_config.rs
- dev-utils/src/commands/init_command.rs
- docker/config/devnet/dev-conf.json
- docker/config/devnet/tendermint/genesis.json
- integration-tests/bot/chainbot.py
- test-common/src/block_generator.rs
- test-common/src/chain_env.rs
Solution:
- added a struct that's meant to contain x509 cert to be used in joining MLS group
ref: https://github.com/crypto-com/chain-docs/blob/master/plan.md#key-generation-and-rotation
and architecture audit report
It's hard to tell whether this is enough information, but one will at least need to have:
- "userinitkey"
- crendetial + attestation payload
both of which can be contained within x509 cert -- attestation as that cert extension
as in TLS settings -- so it may make sense to reuse that for this TDBE MLS group joining/init
> Problem: tx and staking state not accounting for TDBE (fixes #1303)

- Dockerfile
- Makefile
- ci-scripts/Dockerfile
- ci-scripts/run_chain_abci.sh
- ci-scripts/run_tx_query.sh
- docker/Dockerfile
Solution:
- update ci-scripts/Dockerfile for build issue
- update docker/Dockerfile, ci-scripts/run_tx_query.sh and ci-scripts/run_chain_abci.sh for PSW 2.9
- add `--disable-fast-forward` in makefile to avoid sync issue in #1398
> Problem: tx-query-app cannot be built and aesm not running in PSW 2.9 (fix #1392)

- chain-abci/src/staking/mod.rs
- chain-abci/src/staking/table.rs
- docker/build.sh
- integration-tests/multinode/common.py
Solution:
- Add test for nonce logic
- Test max(10) used_validator_keys
- Add more byzantine evidence detection test
- Test liveness tracking not interupt by temporary inactiveness.
- Remove rustup default in build.sh
> Problem (Fix #1297): Not all edge cases described in staking state spec is covered by tests

- Cargo.lock
Solution: regenerated Cargo.lock
(the forked "log-sgx" crate was force-pushed)
> Problem: codebase fails to compile on linux

- architecture-docs/adr-003.md
Solution:
- Change adr-003 to use dedicated version number rather than block height.
The reason for this is the library doesn't allow empty versions, but we have empty blocks, so we can't use block height as the version number.
So we need to use a dedicated version number, it's also the number of blocks which have at least a staking modifications.
> Problem: jellyfish merkle tree don't allow empty version

- CHANGELOG.md
- Cargo.lock
- chain-storage/Cargo.toml
- chain-storage/src/jellyfish.rs
- chain-storage/src/lib.rs
Solution:
- Cleanup jellyfish library
- Add the integration ground work for jellyfish, step1 of adr-003
> Problem (Fix #1307): many unused features and code in merkle trie code dependency

- chain-abci/src/app/mod.rs
- chain-abci/src/app/rewards.rs
- chain-abci/src/staking/table.rs
- chain-abci/tests/validator_changes.rs
- test-common/src/chain_env.rs
Currently, rewards are distributed based on the block proposer, which is unfair for other validators participating in voting process for that block. This PR changes rewards distribution based on the validators who signed the last block.
Fixes #1141.
>  Problem: Unfair rewards distribution

- CHANGELOG.md
- client-rpc/src/rpc.rs
- client-rpc/src/rpc/sync_rpc.rs
- client-rpc/src/rpc/sync_worker.rs
- cro-clib/src/jsonrpc.rs
- integration-tests/bot/chainrpc.py
- integration-tests/client-rpc/test/core/rpc.ts
- integration-tests/client-rpc/test/hdrestore-auto-sync.test.ts
- integration-tests/client-rpc/test/hdwallet-auto-sync.test.ts
- integration-tests/client-rpc/test/wallet-auto-sync.test.ts
- integration-tests/pytests/test_wallet_offline.py
Solution: add asynchronous SYNC and  get_progress api
currently, when we sync with testnet, it took a lot of time.
so "run_sync" is added, sync is now can be done in multi-threaded,
for each wallet, one thread can be activated.
by run_sync_progress, we can get current progress.
moved current sync code by using spawning thread,
to get information, i used Arc and Mutex
React, or Angular now can poll via "run_sync_progress", update UI
when it's done, can close the progress UI.
"sync" api will behave exactly the same as before.
> Problem: no progess api in sync rpc #1440

- CHANGELOG.md
- chain-abci/src/app/mod.rs
- chain-abci/src/app/staking_event.rs
- chain-abci/src/app/validate_tx.rs
- chain-abci/src/enclave_bridge/real/mod.rs
- chain-abci/src/staking/mod.rs
- chain-abci/src/staking/table.rs
- chain-abci/src/staking/tx.rs
- chain-abci/src/storage/mod.rs
- chain-abci/tests/abci_app.rs
- chain-abci/tests/tx_validation.rs
- chain-core/src/common/mod.rs
- chain-core/src/init/coin.rs
- chain-core/src/state/account.rs
- client-common/src/tendermint/types/block_results.rs
Solution: Refactor staking related events to standardized events
---
- Remove `RewardsDistribution` and `SlashValidators ` event
- Standardized all staking address related actions into `StakingChange` event
- Some sample event format (base64 encoded values are decoded)
```
{
type: 'StakingChange',
attributes: [
{
key: 'staking_address',
value: '0x2dfde2178daa679508828242119dcf2114038ea8',
},
{
key: 'staking_optype',
value: 'unbond',
},
{
key: 'staking_diff',
value: '[{key:'Bonded',value:"-1000"},{key:"Unbonded",value:"1000"}]'
}
]
}
```
```
{
"begin_block": {
"events": [
{
"type": "staking_change",
"attributes": [
{
"key": "staking_address",
"value": "MHgyZGZkZTIxNzhkYWE2Nzk1MDg4MjgyNDIxMTlkY2YyMTE0MDM4ZWE4"
},
{
"key": "staking_optype",
"value": "slash"
},
{
"key": "staking_diff", …
```
> Problem: (Fix #1435) No standardized staking event

- CHANGELOG.md
Solution: added an entry in the changelog
I've put tomorrow, as I guess it'll be good to have https://github.com/crypto-com/chain/pull/1449 merged first, so that it's included in the release
> Problem: next release not documented

- Cargo.lock
- chain-core/src/init/config.rs
- chain-storage/Cargo.toml
- chain-storage/benches/jellyfish.rs
- chain-storage/examples/bench_jellyfish_disk.rs
- chain-storage/examples/disk_storage.rs
- chain-storage/examples/jellyfish_nodes.rs
- chain-storage/src/buffer.rs
10000 stakings per version, commit 1000 versions in memory.
Internal node fill rate: 0.22 - 0.25, when the number of stakings is under 10M.
```
$ cargo run --example jellyfish_nodes -p chain-storage 1000 10000
...
internal/leaf: 65557 / 170000 = 0.3856294117647059
internal avg fill rate: 0.22457174672422472
...
internal/leaf: 807343 / 2060000 = 0.39191407766990294
internal avg fill rate: 0.22197365308177566
...
internal/leaf: 1090517 / 2840000 = 0.3839848591549296
internal avg fill rate: 0.2252667771341483
...
internal/leaf: 3333197 / 10000000 = 0.3333197
internal avg fill rate: 0.2500076503128978
```
```
$ cargo bench -p chain-storage
jellyfish, insert 256   time:   [4.6825 ms 4.6957 ms 4.7107 ms]
jellyfish, insert       time:   [30.993 us 31.144 us 31.313 us]
jellyfish, get_with_proof …
```
> Problem (Fix #1436): Performance of merkle library is not clear

- CHANGELOG.md
- chain-abci/src/app/app_init.rs
- chain-abci/src/app/query.rs
- chain-abci/tests/abci_app.rs
- chain-storage/src/api.rs
- chain-storage/src/lib.rs
- integration-tests/bot/chainrpc.py
Solution:
- Support query merkle inclusion proof
- Also support query historical staking state
- Query json encoded staking from abci_query directly #1464
This feature(query historical staked state) is also needed to make the reward integration tests more stable.
Added a new abci_query path "staking" which is like "account", but it returns JSON directly, also support the new features (historical query, proof), the next step will be update the "staking_state" API in client-rpc and client-cli to use the new one.
> Problem (WIP #1313): light client doesn't verify the fetched staking state

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- chain-abci/Cargo.toml
- chain-abci/fuzz/Cargo.toml
- chain-abci/src/app/app_init.rs
- chain-abci/src/app/query.rs
- chain-abci/src/enclave_bridge/mock.rs
- chain-abci/src/enclave_bridge/mod.rs
- chain-abci/src/main.rs
- chain-abci/src/staking/table.rs
- chain-abci/tests/abci_app.rs
- chain-abci/tests/tx_validation.rs
- chain-tx-enclave/mock-utils/Cargo.toml
- chain-tx-enclave/mock-utils/src/lib.rs
- chain-tx-enclave/tx-validation/enclave/src/obfuscate.rs
- client-cli/Cargo.toml
- client-cli/src/command.rs
- client-common/src/transaction.rs
- client-core/Cargo.toml
- client-core/src/cipher.rs
- client-core/src/cipher/mock.rs
- client-core/src/transaction_builder/default_wallet_transaction_builder.rs
- client-core/src/transaction_builder/raw_transfer_transaction_builder.rs
- client-rpc/Cargo.toml
- client-rpc/src/server.rs
- cro-clib/Cargo.toml
- dev-utils/Cargo.toml
- docker/build.sh
- docker/unittest.sh
Solution:
- Add mock mode
The basic idea is described in #1457.
> Problem (Fix #1457): No mock mode for developing on non-sgx platform

- Cargo.lock
- client-common/Cargo.toml
- client-core/Cargo.toml
- client-network/Cargo.toml
- test-common/Cargo.toml
Solution:
- Fix block_id of empty vote in tendermint-rs
> Problem (Fix #1475): lite client verifier crash fails occasionally in integration tests

- .travis.yml
Solution:
- "mock-validation" -> "mock-enclave"
> Problem (Fix #1478): cargo kcov doesn't run

- Cargo.lock
- chain-core/src/common/merkle_tree.rs
- client-common/Cargo.toml
- client-common/src/multi_sig_address.rs
solution:  give a tree heigh limit, and calculate the amount of n choose m , if the amount is  larger than the limit tree leaves number, return error.
> Problem: (fix #1112) Unbounded Tree Depth

- client-core/src/hd_seed.rs
Why?
there is no apis to make address from parent pubkey
to peek addresses, for non-hardened keys, it's possible from parent pubkey.
this feature is necessary for address recovery in sync (another PR)
What problem to solve?
previously, to get address of specific index, we have to derive private,publickeys, which is not necessary, especially for hardware wallet
Why i think this issue solved?
checked with unit-test
> Problem: no way to get pubkey from extended pubkey #1495

- chain-abci/benches/tx.rs
- chain-abci/tests/abci_app.rs
- chain-abci/tests/tx_validation.rs
- chain-abci/tests/validator_changes.rs
- chain-core/src/init/params.rs
- chain-core/src/tx/fee/mod.rs
- chain-core/tests/verify_config.rs
- client-core/src/transaction_builder/default_wallet_transaction_builder.rs
- client-core/src/transaction_builder/raw_transfer_transaction_builder.rs
- cro-clib/src/types.rs
- test-common/src/chain_env.rs
solution:
* add a `try_new` function, when overflow, return Error.
> Problem: (fix #1413) Milli::new and Milli:: integral may overflow

- chain-abci/tests/abci_app.rs
solution:
because the function `restore_from_storege` is private, I added a unit test to test the other function `new_with_storage` which can cover it.
> Problem: (fix #1217) chain-abci restore_from_storage not unit tested

- CHANGELOG.md
- chain-abci/src/app/mod.rs
- chain-abci/src/app/staking_event.rs
- chain-abci/src/staking/mod.rs
- chain-abci/src/staking/tx.rs
- chain-abci/src/storage/mod.rs
- chain-abci/tests/abci_app.rs
- client-network/src/network_ops/default_network_ops_client.rs
- integration-tests/bot/chainbot.py
- integration-tests/multinode/join_test.py
Solution:
- Fix the bug and add unit test
> Problem (Fix #1515): unbond tx don't subtract fee from bonded

- CHANGELOG.md
- chain-abci/tests/abci_app.rs
- chain-core/src/init/config.rs
> Problem (Fix #1520): `missed_block_threshold <= block_signing_window`not checked in init chain

- CHANGELOG.md
- Cargo.lock
- client-common/Cargo.toml
- client-core/Cargo.toml
- client-network/Cargo.toml
- integration-tests/multinode/join_test.py
- test-common/Cargo.toml
Solution:
- Make parse_non_empty_id parse null in tendermint-rs
Related upstream PR: https://github.com/informalsystems/tendermint-rs/pull/98
> Problem (Fix #1523): sync state deserialization fails when nil vote happens

- CHANGELOG.md
- chain-abci/Cargo.toml
Solution: updated chain-abci ver + changelog
--
hot fix needed as restarting nodes may fail as observed by @lezzokafka @allthatjazzleo
> Problem: hotfix (0.5.1) release not documented

- Cargo.lock
- chain-core/src/init/config.rs
- chain-core/src/state/account/address.rs
- client-cli/src/command.rs
- client-cli/src/command/transaction_command.rs
- client-core/Cargo.toml
- client-core/src/service/sync_state_service.rs
- client-core/src/wallet.rs
- client-core/src/wallet/default_wallet_client.rs
- client-core/src/wallet/syncer.rs
- client-core/src/wallet/syncer_logic.rs
- client-network/Cargo.toml
- client-network/src/network_ops.rs
- client-network/src/network_ops/default_network_ops_client.rs
- client-rpc/src/rpc/staking_rpc.rs
- cro-clib/src/transaction.rs
- integration-tests/bot/chainrpc.py
- integration-tests/client-rpc/test/network-ops.test.ts
- integration-tests/multinode/byzantine_test.py
- integration-tests/multinode/join_test.py
- integration-tests/multinode/reward_test.py
- integration-tests/pytests/test_pending_tx.py
Solution:
- Add staking_root in sync state
- Remove the "account" path in favor of the new "staking" path
- Client staking state command add wallet name parameter,
and verify staking state and proof against the trusted staking_root in sync state
- Need to sync wallet before fetching the new staking state now. (you can still get any staking state without verification by request abci_query API directly)
> Problem (Fix #1313): light client doesn't verify the fetched staking state

- .drone.yml
- chain-abci/fuzz/fuzz_targets/abci_cycle.rs
- chain-abci/src/app/app_init.rs
- chain-abci/src/app/macros.rs
- chain-abci/src/app/mod.rs
- chain-abci/src/app/validate_tx.rs
- chain-abci/src/main.rs
- chain-abci/tests/abci_app.rs
- chain-core/src/init/coin.rs
- chain-storage/src/buffer.rs
- chain-storage/src/jellyfish.rs
- client-cli/src/command.rs
Solution:
- Record utxo coins
- Do the check at the end of commit events.
- Optimize `sum_coins` to use `try_fold`
```
utxo = withdraw - deposit - utxo transfer fee
utxo + staking + reward_pool = initial distribution + minted
minted <= expansion_cap
initial distribution + expansion_cap = max supply
```
> Problem (Fix #1038): no total supply sanity checks

- Cargo.lock
- Cargo.toml
- chain-core/Cargo.toml
- chain-tx-enclave/enclave-ra/ra-enclave/Cargo.toml
- chain-tx-enclave/tx-query-next/app-runner/src/main.rs
- chain-tx-enclave/tx-query-next/app-runner/src/zmq_helper.rs
- chain-tx-enclave/tx-query-next/enclave-app/.cargo/config
- chain-tx-enclave/tx-query-next/enclave-app/Cargo.toml
- chain-tx-enclave/tx-query-next/enclave-app/src/handler.rs
- chain-tx-enclave/tx-query-next/enclave-app/src/handler/decryption_request.rs
- chain-tx-enclave/tx-query-next/enclave-app/src/handler/encryption_request.rs
- chain-tx-enclave/tx-query-next/enclave-app/src/main.rs
- client-core/Cargo.toml
- client-core/src/cipher.rs
- client-core/src/cipher/default.rs
- client-core/src/lib.rs
- enclave-protocol/Cargo.toml
Solution:
- Implemented `tx-query` code using EDP in `tx-query-next`
- Added `"edp"` feature flag in `chain-core` (compiles `secp256k1` with
`"edp"` flag)
- Added `"edp-obfuscation"` and `"sgx-obfuscation"` feature flags in
client-core. `"edp-obfuscation"` compiles client with remote attestation
using EDP for connecting to `tx-query`. `"sgx-obfuscation"` compiles
client with remote attestation using SGX SDK for connecting to `tx-query`.
- `tx-query-next` internally uses a thread from a thread pool for each connection.
- Modified `ZmqHelper` in `app-runner`
Fixes #1301.
> Problem: tx-query not yet ported to EDP

- Dockerfile
- Makefile
- integration-tests/multinode/reward_test.py
Solution:
- Make reward integration tests more stable
- Also upgrade the tendermint version in Dockerfile and Makefile
> Problem (Fix #1518): reward multi-node integration test fails on TM 0.33.3/4

- Cargo.lock
- chain-abci/Cargo.toml
- chain-abci/fuzz/Cargo.toml
- chain-storage/Cargo.toml
- chain-storage/src/jellyfish.rs
- dev-utils/Cargo.toml
- test-common/Cargo.toml
Solution: Update version of `kvdb` crates to latest. Fixes #1542.
> Problem: `kvdb` crates not updated to their latest versions

- CHANGELOG.md
- Cargo.lock
- client-cli/Cargo.toml
- client-cli/src/command.rs
Solution: storage opened only once
> Problem: v0.5.x client-cli cannot sync (fixes #1552)

- Cargo.lock
- chain-abci/Cargo.toml
- chain-storage/Cargo.toml
- chain-tx-enclave/tx-query/enclave/Cargo.toml
- chain-tx-filter/src/filter.rs
- client-core/Cargo.toml
Solution: Removed calls to deprecated functions. Fixes #1554.
> Problem: Cannot compile chain code with latest version of bit-vec (0.6.2)

- dev-utils/src/commands/genesis_command.rs
- dev-utils/src/commands/init_command.rs
Solution: Added a new option in genesis generation command (`unbonded_address`). If `unbonded_address` is provided, all other staking addresses will be marked as `Bonded` except for the one provided in `unbonded_address`, which will be marked as `UnbondedFromGenesis`. If `unbonded_address` is not provided, everything will work the same.
> Problem: `dev-utils` cannot generate `genesis.json` for testnet

- chain-abci/fuzz/fuzz_targets/abci_cycle.rs
Solution: updated default app hash + genesis
> Problem: fuzzer crashed due to wrong default app hash (fixes #1581)

- Cargo.lock
Bump futures-util from 0.3.4 to 0.3.5
Bumps [futures-util](https://github.com/rust-lang/futures-rs) from 0.3.4 to 0.3.5.
- [Release notes](https://github.com/rust-lang/futures-rs/releases)
- [Changelog](https://github.com/rust-lang/futures-rs/blob/master/CHANGELOG.md)
- [Commits](https://github.com/rust-lang/futures-rs/compare/0.3.4...0.3.5)
Signed-off-by: dependabot-preview[bot] <support@dependabot.com>
> Problem (Fix #1573): new version of futures-util fails to compile

- client-cli/src/command/address_command.rs
- client-cli/src/command/multisig_command.rs
- client-core/src/service/root_hash_service.rs
- client-core/src/wallet.rs
- client-core/src/wallet/default_wallet_client.rs
* add command `new-address` in `client-cli multisig`
* classify the transfer addresses in client-cli print out, it looks like:
```
Address: dcro18cae94afx0qxjm3cvayyavxu9vnvuqrlexxhgqyt3vyumfm2spnq0f5kcf
MultiSig Address: dcro1w489pglfzv9lam9r6e656tmdu28sxhtgk6psfcw7rghhhfcx2qkq7qk9mr(3/4)
```
> Problem: (fix #1437) No multisignature address generation in client-cli

- chain-tx-enclave/common.mk
- chain-tx-enclave/tx-query/enclave/build.rs
- chain-tx-enclave/tx-validation/enclave/build.rs
Solution: updated Makefile + build.rs flags
Note that this covers the Intel SDK-related C code.
For Rust code, there's a pending PR to update LLVM
https://github.com/rust-lang/llvm-project/pull/58/commits/88008b8cd7b5e165a830f33b7d946b8bd3ec2a51#diff-c9b310226bd6dbea006b9c172ffed354R2331
> Problem: lvi hardening not enabled

- chain-tx-enclave/enclave-ra/ra-client/src/verifier.rs
- chain-tx-enclave/enclave-ra/ra-enclave/src/certificate.rs
- chain-tx-enclave/enclave-ra/ra-enclave/src/lib.rs
- chain-tx-enclave/tx-query-next/enclave-app/src/main.rs
- client-core/src/cipher/default.rs
Solution: Added constructs for creating attested enclave-to-enclave TLS connections
- `EnclaveCertVerifier` now implements `ClientCertVerifier`
- Added some utility functions for creating `rustls::ServerConfig` and `rustls::ClientConfig`
Related to #1549.
> Problem: No way to create mutually attested enclave-to-enclave TLS connections

- architecture-docs/adr-002.md
Solution:
- Put edp related crates in a standalone directory
> Problem: edp related crates conflicts with hacks for old enclave code

- client-cli/src/command.rs
- client-core/src/wallet/syncer.rs
- client-rpc/server/src/server.rs
- client-rpc/src/handler.rs
- client-rpc/src/lib.rs
- cro-clib/Cargo.toml
- cro-clib/chain.h
- cro-clib/src/jsonrpc.rs
- cro-clib/src/types.rs
- docker/build.sh
Solution:
- consolidate the client-rpc setup code
- cro-clib add mock mode api when build in debug
- build cro-clib as cdylib, can be used directly by other language.
- make callback parameter in c api optional
> Problem (#1483): client rpc setup code is duplicated between server and c-api

- CHANGELOG.md
- Cargo.lock
- client-cli/Cargo.toml
- client-cli/src/command/transaction_command.rs
- client-network/Cargo.toml
- client-network/src/network_ops.rs
- client-network/src/network_ops/default_network_ops_client.rs
- client-rpc/Cargo.toml
Solution:
- Remove the restriction from client network ops code
- Add check and double confirmation in client-cli
> Problem (Fix #1621): Can't deposit into other's new staking address

- chain-tx-enclave/enclave-ra/ra-client/src/config.rs
- chain-tx-enclave/enclave-ra/ra-client/src/lib.rs
- chain-tx-enclave/enclave-ra/ra-client/src/verifier.rs
- client-core/src/cipher/default.rs
Solution: Added optional verification of enclave measurement and svn info if `enclave_info` is provided in verifier config.
Fixes #1622.
> Problem: Remote attestation does not verify enclave measurement and svn information

- cro-clib/src/jsonrpc.rs
- integration-tests/bot/chainbinding.py
- integration-tests/bot/chainbot.py
- integration-tests/bot/chainrpc.py
- integration-tests/bot/setup.py
- integration-tests/multinode/byzantine_test.py
- integration-tests/multinode/common.py
- integration-tests/multinode/join_test.py
- integration-tests/multinode/multitx_test.py
- integration-tests/multinode/reward_test.py
- integration-tests/pytests/common.py
- integration-tests/pytests/conftest.py
- integration-tests/pytests/test_pending_tx.py
- integration-tests/pytests/test_small.py
- integration-tests/pytests/test_wallet_offline.py
- integration-tests/pytests/test_watch_only_wallet.py
- integration-tests/run.sh
- integration-tests/run_multinode.sh
Solution:
- python call the rpc shared library directly
- chainbot don't start client-rpc by default,
but integration tests still starts client-rpc for type script tests.
fast forward is disabled by default through c API, because it's problematic in zero-fee test env.
Opened an issue to configure it through c API: #1627
> Problem (Fix #1483): client-rpc process is not necessary for python integration tests

- chain-tx-enclave/tx-query-next/enclave-app/Cargo.toml
- chain-tx-enclave/tx-query-next/enclave-app/src/handler/decryption_request.rs
- chain-tx-enclave/tx-query-next/enclave-app/src/handler/encryption_request.rs
- chain-tx-enclave/tx-query-next/enclave-app/src/main.rs
Solution:
- Moved the code to set TLS certificate inside of individual connection threads.
- Some `clippy` fixes.
> Problem: `tx-query-next` does not create a new certificate after old one is expired.

- Cargo.lock
- chain-tx-enclave/enclave-ra/ra-client/Cargo.toml
- chain-tx-enclave/enclave-ra/ra-client/src/verifier.rs
Solution:
- Remove time dependency
- Only handle the seconds part of time when checking certificate validity
for simplicity
> Problem (Fix #1645): 0.2.* time crate fails to compile

- Cargo.lock
- chain-tx-enclave-next/mls/Cargo.toml
- chain-tx-enclave-next/mls/src/credential.rs
- chain-tx-enclave-next/mls/src/extensions.rs
- chain-tx-enclave-next/mls/src/group.rs
- chain-tx-enclave-next/mls/src/key.rs
- chain-tx-enclave-next/mls/src/keypackage.rs
- chain-tx-enclave-next/mls/src/lib.rs
- chain-tx-enclave-next/mls/src/message.rs
- chain-tx-enclave-next/mls/src/tree.rs
- chain-tx-enclave-next/mls/src/utils.rs
Solution:
- added basic data types + serialization helpers
- tree math + tests: https://github.com/mlswg/mls-protocol/blob/master/draft-ietf-mls-protocol.md#tree-math-tree-math
- creator group initilizations + some skeleton code
NOTE / WIP: As this turns out to be quite large, it may be better to split this over more PRs.
What's still missing:
- plaintext msg signing -- creation of add proposal messages
- secret derivations, ecnryptions... -- creation of commit and welcome messages
- welcome message processing / group creation from it
(and more tests)
> Problem: no MLS group creation procedure (WIP #1617)

- chain-abci/fuzz/fuzz_targets/abci_cycle.rs
Solution:
- Rename cert -> keypackage
> Problem (Fix #1664): fuzzer crashes because of missing keypackage field in its default genesis

- client-network/src/network_ops.rs
- client-network/src/network_ops/default_network_ops_client.rs
- client-rpc/src/handler.rs
- client-rpc/src/rpc.rs
- client-rpc/src/rpc/info_rpc.rs
to display unbonded time in sample wallet client.
use evidence,max_age_duration in genesis(which is nano seconds)
added genesis, status api to client-rpc, which uses tendermint rpc (26657 port)
also when withdrawal fails by unbonded time, also returns remaining time for withdrawal
> Problem: (fix #1658) no api for `minimum unbonded time` in client-rpc

- chain-abci/fuzz/fuzz_targets/abci_cycle.rs
Solution:
- update the reference app hash in fuzz test
> Problem (Fix #1672): incorrect app hash in the default fuzzer genesis

- dev-utils/src/commands/genesis_command.rs
solution: use `include_str!` instead of reading from the file.
> Problem: (fix #1585)cargo kcov occasionally crashing on test_dev_config_file

- client-cli/src/command.rs
- client-common/src/tendermint/rpc_client/async_rpc_client.rs
- client-common/src/tendermint/rpc_client/sync_rpc_client.rs
- send `close` websocket message before shutting down websocket
- to fix two `EOF` errors per syncing
> Problem:(fix #1649) no graceful close in client-cli after sync

- Cargo.lock
- chain-tx-enclave-next/mls/Cargo.toml
- chain-tx-enclave-next/mls/src/group.rs
- chain-tx-enclave-next/mls/src/tree.rs
Solution: confirmation is derived from the updated secrets
+ constant time equality is used for comparing the confirmation mac
--
NOTE: some things aren't done yet or broken, e.g. tree integrity checking
a follow up issues are created: https://github.com/crypto-com/chain/issues/1703
> Problem: no MLS group creation procedure (fixes #1617)

- chain-abci/src/staking/tx.rs
- client-rpc/Cargo.toml
- client-rpc/server/Cargo.toml
- client-rpc/src/rpc/staking_rpc.rs
- cro-clib/Cargo.toml
- docker/build.sh
- integration-tests/bot/chainbot.py
- integration-tests/bot/chainrpc.py
Solution:
- in mock mode, provide empty key package, client and abci don't verify
> Problem (Fix #1699): mock mode multinode integration tests fails

- chain-tx-enclave-next/enclave-ra/ra-client/src/verifier.rs
- chain-tx-enclave-next/tx-query-next/enclave-app/src/sgx_module.rs
Solution: Explicitly add supported TLS version to 1.3 in client and server configs. Fixes #1709.
> Problem: TLS 1.3 may not be used

- .drone.yml
- chain-tx-enclave-next/enclave-ra/ra-client/src/verifier.rs
- chain-tx-enclave-next/mls/Cargo.toml
- chain-tx-enclave-next/mls/src/main.rs
- client-cli/src/command/transaction_command.rs
- client-common/Cargo.toml
- client-common/src/lib.rs
- client-rpc/src/rpc/staking_rpc.rs
- dev-utils/Cargo.toml
- dev-utils/src/commands.rs
- dev-utils/src/commands/init_command.rs
- dev-utils/src/commands/keypackage_command.rs
- dev-utils/src/dev_utils.rs
- dev-utils/src/keypackage.rs
- dev-utils/src/main.rs
- integration-tests/bot/chainrpc.py
added `keyspace generation` in dev-utils.
> Problem: no gen keypackage command in dev-utils (fix #1692)

- client-network/src/network_ops.rs
- cro-clib/src/transaction.rs
because, to fetch synced state, `sync` is required,
so added more comment in error message
> Problem: staking not found error does not provide enough detail (fix #1823)

- client-cli/src/command/address_command.rs
Solution: activate `create watch-only transfer address`
source already coded, just re-activated
> Problem: no create new_watch_transfer_address in client-cli (fix #1809)

- Cargo.lock
- chain-abci/Cargo.toml
- chain-abci/fuzz/Cargo.toml
- chain-storage/Cargo.toml
- cro-clib/chain.h
- dev-utils/Cargo.toml
- test-common/Cargo.toml
Solution: bumped all related crates together
> Problem: kvdb 0.7 (and related crates) fail to compile (fixes #1821)

- integration-tests/bot/chainrpc.py
- integration-tests/multinode/reward_test.py
- integration-tests/run_multinode.sh
Solution:
- increase blocks waited in reward test
- wait for ra-sp-server to startup before running multinode tests
> Problem (Fix #1870): multi-node integration tests occasionally randomly fail

- cro-clib/chain.h
- cro-clib/examples/Makefile
- cro-clib/examples/rpc.c
- cro-clib/src/jsonrpc.rs
- cro-clib/src/types.rs
Solution: update sync json-rpc protocol  and added automatic `chain.h` modification for gcc
> Problem: outdated c-binding example (wip #1845)

- ci-scripts/fuzzit.sh
Solution: updated the path to the fuzzer binary
(as cargo fuzz now runs/builds in the release mode?)
> Problem: fuzzer not being uploaded (fixes #1879)

- Cargo.lock
- chain-tx-enclave-next/enclave-ra/ra-common/Cargo.toml
- chain-tx-enclave-next/enclave-ra/ra-common/src/report.rs
Fixing #1884 
Solution:
1. Adding field attributes to specify the field names in serialized form.
I hereby certify that my contribution is in accordance with the Developer Certificate of Origin (https://developercertificate.org/).
> Problem: Failed to deserialize fields advisoryURL and advisoryIDs in AttestationReportBody (ra-common) (fixes #1884)

- Makefile
Solution: Add make chown-path command
---
Sample usage:
```
sudo make chown-path user=$(id -u) group=$(id -g)
```
> Problem: Makefile does not have command to change created path owner

- Makefile
Solution: set SGX_DEVICE by checking which sgx or isgx exist on machine
> Problem (Fix #1906): Makefile miss auto-detect SGX_DEVICE

- chain-tx-enclave-next/enclave-ra/ra-client/src/verifier.rs
Solution:
1. As rustls aborts the connection when ClientCertVerifier returns none for server trusted CA, an empty CA list is now returned. It doesn't matter for the verification as for remote attestation, the client certificate is always a self-signed certfiicate
I hereby certify that my contribution is in accordance with the Developer Certificate of Origin (https://developercertificate.org/).
> Problem: EnclaveCertVerifier aborts TLS connection (fixes #1904)

- client-common/src/error.rs
Solution:
- print origin error as `{:?}`
> Problem (Fix #1919): client don't print inner error details

- Cargo.lock
- Cargo.toml
- chain-core/src/tx/mod.rs
- chain-tx-enclave-next/tx-validation-next/Cargo.toml
- chain-tx-enclave-next/tx-validation-next/src/main.rs
- chain-tx-enclave-next/tx-validation-next/src/sgx_module.rs
- chain-tx-enclave-next/tx-validation-next/src/sgx_module/obfuscate.rs
- chain-tx-enclave-next/tx-validation-next/src/sgx_module/validate.rs
- cro-clib/chain-core.h
- docker/build.sh
Solution:
- ported the tx-validation enclave logic to EDP
-- instead of "ecall", there's a loop reading off
TcpStream (expected to be "usercall extension")
- ported the SGX sealing test
(before it needs to be executed in that custom SGX_TEST=1 compilation,
here the normal cargo test works) + added
the test execution to the drone
NOTE: runner is not yet implemented for the sake of smaller PR
and it's blocked by finalization of
https://github.com/crypto-com/chain/pull/1910
> Problem: tx-validation not yet ported to EDP (fixes #1867)

- client-core/src/service/wallet_service.rs
- client-core/src/signer/wallet_signer.rs
- client-core/src/wallet/default_wallet_client.rs
- client-core/src/wallet/syncer.rs
refactoring to improve sync speed ,
load_wallet now called only in export, import
1. changed load_wallet called only in export, import
2.  update Wallet in address recovering instead of fetching all
> Problem: slow wallet operation for over 4,000,000 addresses (fix #1922)

- Cargo.lock
Solution:
regenerating Cargo.lock updated some of the transitive
dependencies which seems to have caused a problem in running
integration tests (ra-sp-server can't start up / connect to AESM).
Hence, I instead created the Cargo.lock with the same
dependencies using `cargo lock translate`
> Problem: Cargo.lock still uses the old format (fixes #1927)

- Cargo.lock
- chain-tx-enclave-next/mls/src/group.rs
- cro-clib/Cargo.toml
- cro-clib/src/jsonrpc.rs
Solution:
- initialize env_logger
Maybe better to make it into an option, but currently the only use case is the integration tests, so I guess it's good so far.
> Problem (Fix #1959): cro-clib don't enable log

- .drone.yml
- .travis.yml
- Cargo.lock
- chain-abci/Cargo.toml
- chain-abci/src/app/app_init.rs
- chain-abci/src/app/commit.rs
- chain-abci/src/app/end_block.rs
- chain-abci/src/app/mod.rs
- chain-abci/src/app/query.rs
- chain-abci/src/app/rewards.rs
- chain-abci/src/app/validate_tx.rs
- chain-abci/src/enclave_bridge/edp/mod.rs
- chain-abci/src/enclave_bridge/edp/server.rs
- chain-abci/src/enclave_bridge/mock.rs
- chain-abci/src/enclave_bridge/mod.rs
- chain-abci/src/enclave_bridge/real/mod.rs
- chain-abci/src/main.rs
- chain-tx-enclave-next/tx-validation-next/src/sgx_module.rs
- chain-tx-enclave-next/tx-validation-next/src/sgx_module/obfuscate.rs
- chain-tx-enclave/tx-validation/enclave/src/lib.rs
- docker/build.sh
- enclave-protocol/src/lib.rs
- integration-tests/cleanup.sh
- integration-tests/run.sh
- integration-tests/run_multinode.sh
Solution:
- added a basic req-rep runner writing/reading from two vectors
-- it's using std::sync::* primitives,
because EnclaveProxy is synchronous +
for some, it doesn't matter or may even be preferred
(e.g. tokio Mutex isn't preferred if locks are short-lived
and don't cross multiple await points)
- temporary zmq server to faciliate tx-query
-- because of the treading, EnclaveProxy also needed to
accept lifetime of 'static
- one extra variant in the enclave protocol (mainly used for testing)
- old code temporarily hidden under "legacy" flag
- since EDP runner only compiles on nightly,
there's a fix/hack on Travis to exclude EDP
> Problem: no runner for EDP-based tx-validation (fixes #1950)

- client-common/src/key/private_key.rs
- client-core/src/service/mock_hw_key_service.rs
- dev-utils/src/commands/test_vector_command.rs
- dev-utils/src/dev_utils.rs
solution: use `schnorr_sign_aux` instead of `schnorr_sign` and allow users input a `aux_payload`
> Problem: (fix #1949) non-deterministic test-vectors with upstream schnorrsig

- ci-scripts/Dockerfile.fuzzer
Solution: updated the fuzzer dockerfile to include protoc
> Problem: fuzzer fails to compile on the latest master (fixes #1975)

- client-cli/src/command/wallet_command.rs
- client-common/src/tendermint/types/block_results.rs
- client-core/src/service.rs
- client-core/src/service/wallet_service.rs
- client-core/src/signer/wallet_signer.rs
- client-core/src/transaction_builder/default_wallet_transaction_builder.rs
- client-core/src/wallet.rs
- client-core/src/wallet/default_wallet_client.rs
- client-core/src/wallet/syncer.rs
- client-core/src/wallet/syncer_logic.rs
- client-network/src/network_ops/default_network_ops_client.rs
- client-rpc/src/rpc/sync_rpc.rs
- client-rpc/src/rpc/wallet_rpc.rs
1. removed temporary transfer, staking addresses storing in Wallet
2. query address to sled-storage directly, which is fast in massive address
3. replace 1:1 compare with db-query
1. in massive addresses(over 4,000,000),
sync and other wallet functions will work as fast as when there are small number of addresses
2. also it will not store addresses in memory, which will save some memory space, also memory copying cost.
3. in a block, which contains a lot of txs, it will work very efficiently.
to query directly, added WalletStorage to Wallet.
WalletStorage is proxy for the storage using `dyn trait` with Arc+Mutex.
1. staking_addresses_contains -> for query
2. transfer_addresses_contains  -> for query
3. get_public_keys -> for import, export
4. get_roothashes -> for import, export
> Problem: wallet operations slow down with a large number of addresses (fix #1939)

- client-cli/src/command.rs
- client-core/src/wallet/syncer.rs
- client-rpc/server/src/program.rs
- client-rpc/server/src/server.rs
- cro-clib/src/jsonrpc.rs
Solution: add --disable-light-client option to skip `light client`
because need to skip `light client` when fee is zero.
also with zero fee, we cannot use fast forward option.
so this option is necessary.
default is
1. not use fastward
2. use light client check
which is the most safest option
> Problem:no option for disabling light client (fix #2012)

- chain-tx-enclave-next/tx-validation-next/src/sgx_module.rs
Solution: changed the inner listening loop level to trace,
as otherwise it'd spam the integration test logs
> Problem: inappropriate log level in tx_validation_next (fixes #2021)

- .travis.yml
Solution: patch chain-abci's cargo.toml temporarily (comment out legacy sgx-test feature)
> Problem: kcov fails on the latest master

- chain-tx-enclave-next/mls/Cargo.toml
- chain-tx-enclave-next/mls/src/ciphersuite.rs
- chain-tx-enclave-next/mls/src/group.rs
- chain-tx-enclave-next/mls/src/key.rs
- chain-tx-enclave-next/mls/src/keypackage.rs
- chain-tx-enclave-next/mls/src/message.rs
- chain-tx-enclave-next/mls/src/tree.rs
Solution:
- verify decrypted secret against public key
- also verify leaf keypackage against leaf secret
> Problem: didn't verify secrets against public key in DirectPath

- client-core/src/service/wallet_state_service.rs
- client-core/src/wallet/syncer.rs
Solution: pre-check memento before fetch & update
it will do writing when there is change(it's maximum 2 per block), so speed will be OK
in case , a lot of utxo updates in the block, just one group of mementos will be applied at once.
> Problem: un-necessary WalletState writing to DB (fix #2032)

- client-cli/src/command/address_command.rs
- client-cli/src/command/transaction_command.rs
- client-core/src/service/wallet_service.rs
- client-core/src/wallet.rs
- client-core/src/wallet/default_wallet_client.rs
- client-core/src/wallet/syncer.rs
- client-rpc/src/rpc/wallet_rpc.rs
add paging to client-rpc, and cli
this is breaking change to current protocol
also check_staking_address_for_deposit is refactored ( get rid of staked addresses copying)
with this pr, after 4,000,000 addresses, query address is very fast.
previously it fetches all, it hangs `postman`
> Problem: no paging in client-rpc, address_list (fix #2023)

- ci-scripts/Dockerfile.fuzzer
Solution: updated the docker image to be based off buster (instead of stretch),
as a newer LLVM is needed for libfuzzer-sys compilation
> Problem: fuzzer fails to compile (fixes #2039)

- Cargo.lock
- Cargo.toml
- chain-tx-enclave-next/mls/Cargo.toml
- chain-tx-enclave-next/mls/src/extras/dleq.rs
- chain-tx-enclave-next/mls/src/extras/mod.rs
- chain-tx-enclave-next/mls/src/group.rs
- chain-tx-enclave-next/mls/src/key.rs
- chain-tx-enclave-next/mls/src/message.rs
- chain-tx-enclave-next/mls/src/tree.rs
Solution: sketched out core of "NACK" mechanism
which involves revealing shared secrets from invalid
message parts and including DLEQ proofs.
-- currently, needs:
1) latest master of p256 which contains scalar arithmetic (not yet released)
2) for the high-level API, it needs to directly decrypt HPKE ciphertext
from a shared secret -- this may not ever be released
also needs "verify_node_private_key" from https://github.com/crypto-com/chain/pull/2018
> Problem: no way for mls member to prove invalid ciphertext (fixes #1797)

- .drone.yml
- Cargo.lock
- Cargo.toml
- chain-tx-enclave-next/enclave-ra/ra-enclave/src/certificate.rs
- chain-tx-enclave-next/enclave-ra/ra-enclave/src/config.rs
- chain-tx-enclave-next/enclave-ra/ra-enclave/src/context.rs
- chain-tx-enclave-next/enclave-ra/ra-enclave/src/lib.rs
- chain-tx-enclave-next/mls/src/main.rs
- chain-tx-enclave-next/tdbe/enclave-app/Cargo.toml
- chain-tx-enclave-next/tdbe/enclave-app/src/sgx_module.rs
- chain-tx-enclave-next/tx-query-next/enclave-app/Cargo.toml
- chain-tx-enclave-next/tx-query-next/enclave-app/src/main.rs
- chain-tx-enclave-next/tx-query-next/enclave-app/src/sgx_module.rs
- chain-tx-enclave-next/tx-validation-next/Cargo.toml
- docker/build.sh
- integration-tests/pytests/test_client_cli.py
- integration-tests/rust_tests/test_cert_expiration/Cargo.toml
- integration-tests/rust_tests/test_cert_expiration/src/main.rs
solution:
* make certificate expiration as a compile-time parameter
* set default validity_duration to 90 days, which is as same as certificate expiration
* add a small time duration when check certificate is expired or not
* use the min(default validity_duration, cert_expiration) as the validity_duration to check the certificate is expired or not
> Problem: (fix #1951) no certificate expiration handling tests

- chain-tx-enclave-next/mls/Cargo.toml
Solution: updated the mls dependency specification to include std feature (for error type)
> Problem: fuzzer compilation fails (fixes #2052)

- Cargo.lock
- chain-abci/fuzz/Cargo.toml
Solution: patch crates.io in fuzzer manifest
> Problem: fuzzer still fails to compile

- Cargo.lock
- chain-abci/Cargo.toml
- chain-abci/src/app/query.rs
- chain-abci/tests/abci_app.rs
- chain-core/Cargo.toml
- chain-core/src/lib.rs
- chain-core/src/mls/mod.rs
- chain-core/src/state/account.rs
- chain-core/src/state/account/op/data/deposit.rs
- chain-core/src/state/account/op/data/unbond.rs
- chain-core/src/state/account/op/data/withdraw.rs
- chain-core/src/state/validator/nodejoin.rs
- chain-core/src/state/validator/unjail.rs
- chain-core/src/tx/data/mod.rs
- chain-core/src/tx/mod.rs
- client-common/src/cipher/mock.rs
- client-common/src/key/private_key.rs
- client-common/src/transaction.rs
- client-core/src/signer/wallet_signer.rs
- client-core/src/transaction_builder/default_wallet_transaction_builder.rs
- client-core/src/types/transaction_change.rs
- client-core/src/wallet/default_wallet_client.rs
- client-core/src/wallet/syncer.rs
- client-core/src/wallet/syncer_logic.rs
- cro-clib/chain-core.h
- docker/config/devnet/tendermint/genesis.json
- enclave-protocol/Cargo.toml
- enclave-protocol/src/lib.rs
Solution: currently the data types are distinct, but it could happen
in the future that two TX types have the same/similar schema,
so the txid would be the same and one may potentially "swap"
tx type (e.g. one may sign unjailtx, but malicious party
would broadcast it as unbondtx -- currently not possible,
bu just an example of what this aims to prevent).
- a trait "TransactionType" was added and implemented for all tx payloads
- txid is now calculated as blake3(\<type tag\>||scale_payload(tx))
- note this "breaks" 0.5 signing code
(as even though the payload is the same, wallets will be
using a different message digest) -- for that reason,
it's feature-guarded under "new-txid"
> Problem: no domain separation of hashed data types (fixes #1715)

- Cargo.lock
- Cargo.toml
- Dockerfile
- chain-abci/Cargo.toml
- chain-core/Cargo.toml
- chain-tx-enclave-next/tx-query-next/enclave-app/Cargo.toml
- chain-tx-enclave-next/tx-validation-next/Cargo.toml
- chain-tx-filter/Cargo.toml
- chain-tx-validation/Cargo.toml
- client-common/Cargo.toml
- client-core/Cargo.toml
- client-network/Cargo.toml
- cro-clib/Cargo.toml
- dev-utils/Cargo.toml
- docker/build.sh
- docker/sgx_test.sh
- enclave-protocol/Cargo.toml
- test-common/Cargo.toml
Solution: updated the C dependencies to insert
"-mlvi-hardening -mllvm -x86-experimental-lvi-inline-asm-hardening"
flags (supported by latest LLVM 11)
+ updated docker image building to use later EDP nightly
> Problem: rust compilation currently doesn't apply LVI mitigations (fixes #1746)

- chain-abci/Cargo.toml
- chain-abci/src/enclave_bridge/edp/mod.rs
- chain-tx-enclave-next/tx-query-next/enclave-app/src/sgx_module/handler/decryption_request.rs
Solution: replaced the code with a unix domain socket pair
(one socket is used inside chain-abci, the other is passed in
/ wrapped in tokio usercall extesion)
- should reduce the busy-waiting
> Problem: unnecessary handling of tx validation usercalls (fixes #2104)

- client-cli/src/command.rs
- client-core/src/wallet/syncer.rs
- client-rpc/server/src/program.rs
- client-rpc/server/src/server.rs
- client-rpc/src/handler.rs
- client-rpc/src/rpc/sync_rpc.rs
- cro-clib/src/jsonrpc.rs
- integration-tests/bot/client_cli.py
Solution: add trust block setting, and removed un-necessary spawning light-client
fix integration test
`--disable-light-client` will not create `light client handle`
if you don't specify light-client info, it will ask (for client-cli)
you can give options (for client-rpc, not interactive)
if you give full light-client options, it will not ask.
if not, it will ask questions, and fetch the block, you can confirm it
```
./client-cli sync --name a    <- it will ask  trusting period, height, blockhash
./client-cli sync --name a --light-client-peers 0000000000000000000000000000000000000000@127.0.0.1:26657,1000000000000000000000000000000000000000@127.0.0.1:26657 --light-client-trusting-period 1000000000 --light-client-trusting-height 111 --light-client-trusting-blockhash ""
./client-cli sync …
```
> Problem: light client trusted block can't be set in client-* (fix #2005)

- Cargo.lock
- chain-abci/Cargo.toml
- chain-abci/fuzz/Cargo.toml
- test-common/Cargo.toml
Solution: specified the dependency against a git fork repository
> Problem: not possible to update to the latest unpublished rust-abci

- integration-tests/multinode/common.py
- integration-tests/multinode/join_test.py
- integration-tests/multinode/reward_test.py
Solution:
- reward test, wait for target block committed in abci by query chain state.
- join test, accept the case when `CouncilNode` is None, since it
verified the `last_slash` field.
> Problem (Fix #2116): multinode integration test unstable

- Cargo.lock
- Cargo.toml
- chain-abci/fuzz/Cargo.toml
- chain-tx-enclave-next/mls/Cargo.toml
- chain-tx-enclave-next/mls/src/ciphersuite.rs
- chain-tx-enclave-next/mls/src/crypto.rs
- chain-tx-enclave-next/mls/src/extras/dleq.rs
- chain-tx-enclave-next/mls/src/key.rs
- chain-tx-enclave-next/mls/src/message.rs
Solution: update the fork library to 0.2
and migrated the code to the new API (main changes were
renaming marshal/unmarshal traits and not exposing KeyExchange trait
in root)
> Problem: hpke library is not up to date with upstream (fixes #2133)

- .github/workflows/rust.yml
- .travis.yml
- Cargo.lock
- chain-tx-enclave-next/enclave-ra/ra-client/src/config.rs
- chain-tx-enclave-next/enclave-ra/ra-client/src/verifier.rs
- chain-tx-enclave/enclave-macro/Cargo.toml
- chain-tx-enclave/enclave-macro/src/lib.rs
- client-common/Cargo.toml
- client-common/src/cipher/default.rs
- client-common/src/lib.rs
- docker/build.sh
- docker/sgx_test.sh
Solution:
- added proc macros to extract hex-encoded MRSIGNER and MRENCLAVE values
- extended client-common attested TLS config for veryfiyng enclave measurements
- reordered integration test building + parsing of sigstruct to extract TQE MRSIGNER and MRENCLAVE values + dummy values in non-sgx tests
> Problem: client-* isn't configured with enclave measurements to verify against tx-query connection (fixes #2079)

- ci-scripts/fuzzit.sh
Solution: added dummy environment variables to the fuzzer compilation script
> Problem: fuzzer fails to compile due to missing environment variables

- Cargo.lock
- chain-tx-enclave-next/enclave-ra/ra-client/src/config.rs
- chain-tx-enclave-next/enclave-ra/ra-client/src/verifier.rs
- chain-tx-enclave-next/tdbe/enclave-app/src/sgx_module.rs
- client-common/src/cipher/default.rs
- integration-tests/rust_tests/test_cert_expiration/Cargo.toml
- integration-tests/rust_tests/test_cert_expiration/src/main.rs
Solution: Modified the code to allow the configuration of parameters
There are three modes of connections:
- One-way attested TLS connection (client verifies all the details and server does not verify anything)
- Mutually attested TLS connection between different enclaves (client verifies all the details and server everything except MRENCLAVE)
- Mutually attested TLS connection between same enclaves (both client and server verifies all the details)
> Problem: Enclave certificate verifier does not allow configuration of parameters to verify

- ci-scripts/Dockerfile.fuzzer
Solution: updated the fuzzer dockerfile to install libudev dependencies
> Problem: fuzzer fails to build inside the docker image

- Cargo.lock
- chain-tx-enclave-next/mls/Cargo.toml
- chain-tx-enclave-next/mls/src/extras/dleq.rs
- chain-tx-enclave-next/mls/src/extras/mod.rs
- chain-tx-enclave-next/mls/src/group.rs
Solution:
- updated p256 to upstream
- split up confirmation computation
- extended the testing commit "corruption" code, so that commit can be processed in tests
- fixed the incorrect assertions in NACK unit tests
> Problem: incorrect NACK unit test assertions (fixes #2151)

- chain-abci/fuzz/fuzz_targets/abci_cycle.rs
- chain-abci/tests/abci_app.rs
- chain-core/src/init/config.rs
- chain-core/src/init/mod.rs
- chain-core/src/init/params.rs
- chain-core/src/init/params_compile.rs
- chain-core/tests/verify_config.rs
- chain-tx-enclave-next/enclave-ra/ra-client/src/lib.rs
- chain-tx-enclave-next/enclave-ra/ra-common/src/lib.rs
- chain-tx-enclave-next/enclave-ra/ra-enclave/src/context.rs
- chain-tx-enclave-next/enclave-ra/ra-enclave/src/lib.rs
- client-common/src/tendermint/mock.rs
- cro-clib/chain-core.h
- dev-utils/example-dev-conf.json
- dev-utils/src/commands/genesis_command.rs
- dev-utils/src/commands/genesis_dev_config.rs
- docker/config/devnet/dev-conf.json
- docker/config/devnet/tendermint/genesis.json
- integration-tests/bot/chainbot.py
- test-common/src/block_generator.rs
- test-common/src/chain_env.rs
Solution:
- extended the genesis config with TDBE-related parameters that will only be used by chain-abci
- the other timing parameters I've put as compile-time parameters,
because future TDBE code will be based its logic on them (e.g. when it'll generate self-update)
+ for expiration, there is a lot of places, where it uses the default expiration,
so it'd need more work (it's to be revisited when these things are implemented
-- e.g. if it'll make sense to include them in the app hash,
as they are unlikely/hard to change, like e.g. evidence age)
- fixed tests
> Problem: genesis parameters are not up to date (fixes #1997)

- Cargo.lock
- chain-abci/Cargo.toml
- chain-abci/src/enclave_bridge/edp/mod.rs
- chain-abci/src/enclave_bridge/edp/tdbe.rs
- chain-abci/src/enclave_bridge/mod.rs
- chain-abci/src/main.rs
- chain-storage/src/api.rs
- chain-storage/src/lib.rs
- chain-tx-enclave-next/tdbe/enclave-app/src/sgx_module.rs
- chain-tx-enclave-next/tdbe/enclave-app/src/sgx_module/handler.rs
- chain-tx-enclave-next/tdbe/tdbe-common/src/lib.rs
- enclave-protocol/src/tdbe_protocol.rs
Solution: Added TDBE runner and persistence stream for transactions fetched by TDBE. Fixes #1995.
Note: There are still few things missing in the TDBE runner:
- Fetching remote TDBE details from RPC
- Fetching transaction IDs using light client
- Attested TVE <-> TDBE stream
> Problem: Missing runner for TDBE + No persistence of TDBE fetched transactions

- Cargo.lock
- chain-abci/Cargo.toml
- chain-abci/src/staking/table.rs
- integration-tests/bot/chainbot.py
- integration-tests/multinode/join_cluster.json
- integration-tests/multinode/join_test.py
Solution:
- deduplicate staking address when doing cleanup
- index used_validator_addresses when initialize after load from storage
- changed integration test to covert the use case
> Problem (Fix #2203): validator crash after re-joined with different validator key

- Cargo.lock
- Cargo.toml
- chain-abci/fuzz/Cargo.toml
- chain-tx-enclave-next/mls/Cargo.toml
- chain-tx-enclave-next/mls/src/extras/dleq.rs
Solution: updated the hpke fork to have a workaround around the
recent change in `dh` representation (extra trait for
returning the point/pubkey bytes, as only x-coord is now
used in hpke)
> Problem: fuzzer target fails to compile (fixes #2224)

- ci-scripts/install_protoc.sh
Solution: added a check in installation script to verify if protoc doesn't exist before installing it
> Problem: protoc installation fails on Travis with cached protoc (fixes #2233)

- Cargo.lock
- chain-tx-enclave-next/enclave-ra/ra-common/src/sp/attestation_evidence.rs
- chain-tx-enclave-next/enclave-ra/ra-common/src/sp/protocol.rs
- chain-tx-enclave-next/enclave-ra/ra-enclave/Cargo.toml
- chain-tx-enclave-next/enclave-ra/ra-enclave/src/context.rs
- chain-tx-enclave-next/enclave-ra/ra-sp-client/src/client.rs
- chain-tx-enclave-next/enclave-ra/ra-sp-client/src/lib.rs
- chain-tx-enclave-next/enclave-ra/ra-sp-server/src/context.rs
- chain-tx-enclave-next/enclave-ra/ra-sp-server/src/ias_client.rs
- chain-tx-enclave-next/enclave-ra/ra-sp-server/src/server.rs
This was an issue reported by kudelski. Intel claims that the nonce for remote attestation is optional, but I suppose it's better to be safer and include it.
@devashishdxt do you happen to know why it was left out? Maybe I am missing something, or it is truly unnecessary. Thanks
> Problem: no nonce for remote attestation report
